### ISSUE TITLE
Hooks external scripts when greyhole processing events

### ISSUE THREAD

**Issue by gboudreau** [gboudreau/Greyhole#10]
Suggest hooks from greyhole to enable calling external scripts on events occuring. e.g. I have a cron job that goes through my picture directory and produces lower resolution versions in another share (for display on remote machines). would be nice if I could fork a script on an add or a modify to keep these in sync without having to walk the whole pictures directory structure and do date comparisons.

**Comment by taa1** [comment]
This would be a very useful feature for me because I could use a script to trigger one of these: https://blink1.thingm.com/

At a minimum it would be useful if scripts could be based on log level category, e.g., WARN, CRITICAL, etc.

**Comment by gboudreau** [comment]
Would this work for everyone:

    #### Hooks ####
    # Call custom scripts on events.
    #
    # Available events type: create, edit, rename, delete, mkdir, rmdir, warning, error, critical, idle, idle_locked
    # - For create, edit, rename, delete, mkdir, and rmdir, the hooks are called after Greyhole finished processing the operation;
    # - for warning, error and critical, the hooks are called after Greyhole created a log;
    # - for idle and idle_locked, the hooks are called just before the daemon will sleep.
    #   (idle_locked is when the daemon will sleep because there are locked (still being written to) files.)
    #
    # The parameters sent to the custom scripts are:
    #   - event_type (one of the above)
    #   - share (name); if event is related to a share
    #   - path_on_share; if event is related to a folder or file
    
    #	hook[create|edit|rename|delete] = /home/me/bin/greyhole_file_changed.sh
    #	hook[warning|error|critical] = /home/me/bin/greyhole_notify_error.sh
    #	hook[idle] = /home/me/bin/greyhole_is_idle.sh

**Comment by Sparticuz** [comment]
Would be neat to also be able to call a hook instead of an email for the fsck reports and when drives are out of space.

**Comment by gboudreau** [comment]
Drives out of space: will be sent to an error hook. You probably want notifications for all errors really, not just when drives are out of space.
fsck: will add.

**Comment by taa1** [comment]
Your proposal sounds perfect!

One question:

`- event_code: one of the predefined values that define the actual error/event; see ... for the list of possible codes`

What does `...` refer to?

**Comment by gboudreau** [comment]
Most probably a Github link that shows the source file used by Greyhole, where all those codes are defined. That way, the link will always show the latest codes that are available.
Will probably be things like 'warning_drive_full', 'error_all_drives_full', etc. to allow the script to do different things, depending on the type of error or warning.

**Comment by gboudreau** [comment]
Implementation is complete; if anyone wants to beta-test (probably safer to do that on a VM), let me know what rpm/deb you need (arch), and I'll create a test build from the development branch.
Cheers.

**Comment by taa1** [comment]
I definitely want to test. 
Fedora 23, 64bit

**Comment by gboudreau** [comment]
When released, will be 0.10.0, but while beta-testing, I'll use the 0.9.99 version number:

Download links:
- https://greyhole.net/releases/rpm/x86_64/greyhole-0.9.99-1.x86_64.rpm
- https://greyhole.net/releases/rpm/i386/greyhole-0.9.99-1.i386.rpm
- https://greyhole.net/releases/deb/greyhole-0.9.99-1.amd64.deb
- https://greyhole.net/releases/deb/greyhole-0.9.99-1.i386.deb

**Comment by gboudreau** [comment]
The man page for greyhole.conf has the details, same for the sample greyhole.conf found in /usr/share/greyhole/, and example scripts can be found in /usr/share/greyhole/scripts-examples/ (0.9.99-2 and +; 0.9.99-1 was missing those example scripts)

**Comment by gboudreau** [comment]
Merged into master; released as [0.10.0](https://github.com/gboudreau/Greyhole/releases/tag/0.10.0).
