### ISSUE TITLE
Owner and Permissions not properly set on new renamed files and directories

### ISSUE THREAD

**Issue by Lathe26** [gboudreau/Greyhole#135]
# Summary
If a user creates a new file or directory from a remote machine and then immediately renames it, the owner and permissions do not get set correctly.  Instead the default of root:root and 777 is used.

# Example
An example of where this shows up is when a user on a Windows client machine r-clicks inside a folder, selects New->Folder, and then types in a name.

# Possible Reason
What likely is happening is:
1.  When the user selects New->Folder, a new directory is created called "New Folder".
2.  The Greyhole VFS is notified of this and puts the full path for this directory into the queue to be processed a few seconds later.
3.  The user types in the name for the folder (let's call it "MyFiles")
4.  The Greyhole VFS is notified of the rename of "New Folder" to "MyFiles" and puts this into its queue to be processed a few seconds later.
5.  ... a few seconds pass...
6.  Greyhole dequeues that a new folder was created called "New Folder".  As part of copying it to the gh folders and creating a symlink, Greyhole tries to get the owner & permissions of "New Folder" but can't (path doesn't exist anymore because of the rename).  This causes Greyhole to default to root:root 777.
7.  Greyhole dequeues the rename of "New Folder" to "MyFiles".  The directory's name is updated in the gh directories and so is the symlink.

# Reproducibility
This is fairly easy to reproduce.

**Comment by gboudreau** [comment]
I can't reproduce this issue.
