### ISSUE TITLE
Min_Free does not include Trash

### ISSUE THREAD

**Issue by chimpy** [gboudreau/Greyhole#136]
Hello,

I recently replaced a large number of files in my pool. The old, replaced files were placed into the GH Trash. On one drive this caused it to go over the min_free directive and fill until it was full (<8 KB remaining). Ext4's jbd2 went into overdrive and caused the I/O to hit the roof and lag everything.

Doing a sudo greyhole -a solved the issue. In my opinion, the min_free option should not count the trash as free space.

Thanks again for Greyhole :)

**Comment by gboudreau** [comment]
That has nothing to do with the size of the trash.

This happens because the limit you specify in the Greyhole config is a soft limit.
If Greyhole has no choice, it will go over that limit.

Ref: https://github.com/gboudreau/Greyhole/blob/master/greyhole.example.conf#L84

**Comment by chimpy** [comment]
Hi,

Thanks for the reply.

I am aware that it is a soft limit. There were two other drives in the pool that had 2 TB free each. So that doesn't make sense to me. My config is very simple, there was plenty of space available and yet min free was ignored.
