### ISSUE TITLE
--balance should leave file dates intact

### ISSUE THREAD

**Issue by jasker5183** [gboudreau/Greyhole#141]
As of now when a balance is run it moves the file so it also changes the date, it should keep the original date intact if possible.

**Comment by gboudreau** [comment]
--balance uses the same `gh_rename()` and `gh_chperm()` functions that are used everywhere else, so if there is a problem, I doubt it's specific to --balance.
Those functions are the same used when creating new file copies, when a file is added or modified on a share.

I'll try to reproduce your issue.

**Comment by gboudreau** [comment]
Indeed, it looks like files that are worked on with --balance, not just the symlinks, have a modified date = the date that Greyhole balanced them. Will try to debug further; this doesn't happen on normal file operations...

**Comment by gboudreau** [comment]
Will release 0.9.63 soon which will fix this issue.

**Comment by gboudreau** [comment]
0.9.63 released. Let me know if it works for you.
