### ISSUE TITLE
Greyhole not starting automatically on bootup

### ISSUE THREAD

**Issue by Xtropy74** [gboudreau/Greyhole#142]
Been having an issue with Greyhole starting automatically after rebooting my Ubuntu machine which started after a Greyhole software update a few months ago. Running Ubuntu 14.04.3 LTS, Error message states:

Aug 10 13:49:36 CRITICAL test-config: Can't connect to database: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

If I manually start it via: sudo service greyhole start, it runs just fine. This only happens after rebooting my machine.

**Comment by gboudreau** [comment]
Looks like Greyhole starts before MySQL, but it shouldn't, since the upstart script says mysql is required (https://github.com/gboudreau/Greyhole/blob/master/upstart.conf#L4).
You're using the upstart script, right? Not the init.d script?

**Comment by Xtropy74** [comment]
Yes, the greyhole.conf file in /etc/init/greyhole.conf matches the exact code in upstart.conf as confirmed by your link

**Comment by gboudreau** [comment]
Then you have an issue with either Upstart, or MySQL. Greyhole asks to be started only once MySQL has been started, but for some reason, Greyhole is started and MySQL is not responding.

**Comment by Xtropy74** [comment]
I'll add a pause to your script as a workaround. Strange that this happened after an update to greyhole and all my other upstart and applications work fine....
