### ISSUE TITLE
Ubuntu: Greyhole VFS library not loading

### ISSUE THREAD

**Issue by gboudreau** [gboudreau/Greyhole#153]
On Ubuntu, after samba has been updated to 4.3.8 (or any 4.3.x really), the VFS module of Greyhole will fail to load.

smb.log:
```
[2016/04/18 13:31:08.537795, 0] ../lib/util/modules.c:48(load_module)
 Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so': libsmbd_base.so: cannot open shared object file: No such file or directory
[2016/04/18 13:31:08.537817, 0] ../source3/smbd/vfs.c:184(vfs_init_custom)
 error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
```

Creating the missing symbolic link from libsmbd_base.so.0, as described [here](https://github.com/gboudreau/Greyhole/issues/107#issuecomment-35029393) will resolve the above issue, but another dependent library is missing:

```
[2016/04/18 18:00:04.040708,  0] ../lib/util/modules.c:48(load_module)
  Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so': libsmbd-base-samba4.so: cannot open shared object file: No such file or directory
[2016/04/18 18:00:04.040734,  0] ../source3/smbd/vfs.c:184(vfs_init_custom)
  error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
```

The current workaround is to manually compile the Greyhole VFS, as described in the [INSTALL file](https://github.com/gboudreau/Greyhole/blob/master/INSTALL#L85):

```bash
sudo apt-get -y install build-essential python-dev libgnutls-dev

SAMBA_VERSION=`/usr/sbin/smbd --version | awk '{print $2}' | awk -F'-' '{print $1}'`
curl -LO http://samba.org/samba/ftp/stable/samba-${SAMBA_VERSION}.tar.gz
tar zxf samba-${SAMBA_VERSION}.tar.gz && rm -f samba-${SAMBA_VERSION}.tar.gz
cd samba-${SAMBA_VERSION}

curl -Lo source3/modules/vfs_greyhole.c https://raw.githubusercontent.com/gboudreau/Greyhole/master/samba-module/vfs_greyhole-samba-4.3.c
curl -Lo wscript-samba-4.3.patch https://raw.githubusercontent.com/gboudreau/Greyhole/master/samba-module/wscript-samba-4.3.patch
patch -p1 < wscript-samba-4.3.patch

./configure --enable-debug --enable-selftest --disable-symbol-versions --without-acl-support --without-ldap --without-ads && make -j

# Create a symlink in the Samba VFS modules dir pointing to the compiled VFS
if [ -d /usr/lib/x86_64-linux-gnu ]; then LIBDIR=/usr/lib/x86_64-linux-gnu; elif [ "`uname -m`" = "x86_64" ]; then LIBDIR=/usr/lib64; else LIBDIR=/usr/lib; fi
V=`echo ${SAMBA_VERSION} | awk -F'.' '{print $1$2}'`
cp bin/default/source3/modules/libvfs*greyhole.so greyhole-samba${V}.so
sudo rm -f ${LIBDIR}/samba/vfs/greyhole.so
sudo ln -s `pwd`/greyhole-samba${V}.so ${LIBDIR}/samba/vfs/greyhole.so

sudo /etc/init.d/smbd restart
sudo /etc/init.d/mount_shares_locally restart
```

**Comment by bcrook** [comment]
Quick note - this worked for me but I had to modify path for the curl command - looks like there are a few redirects when you hit [http://samba.org/samba/ftp/stable/](http://samba.org/samba/ftp/stable/)

I ended up here:

https://download.samba.org/pub/samba/stable/

**Comment by fantom1** [comment]
On Ubuntu 14.04 I fixed the issue this way:

apt-get install samba-libs
apt-get install samba-dbg

ln -s /usr/lib/x86_64-linux-gnu/samba/libsmbd-base.so.0 /usr/lib/x86_64-linux-gnu/libsmbd-base-samba4.so
ln -s /usr/lib/x86_64-linux-gnu/samba/libsamba-debug.so.0 /usr/lib/x86_64-linux-gnu/libsamba-debug-samba4.so

**Comment by gboudreau** [comment]
Thanks @fantom1; I integrated this in the .deb `postinst` script.

Update to 0.9.66-2 to get the fix:
```
apt-get update && apt-get install greyhole
```

**Comment by Rastalovich** [comment]
I had to add '--without-ad-dc' to my compile line.

**Comment by chimpy** [comment]
Woohoo! Finally found the solution. I was wondering why both of my servers stopped working at the same time. Cheers guys.

**Comment by ralle12345** [comment]
For the record: 

The curl line to pull the vfs module source from github in the above script needs to be changed to:
```
curl -Lo source3/modules/vfs_greyhole.c https://raw.githubusercontent.com/gboudreau/Greyhole/master/samba-module/vfs_greyhole-samba-4.x.c
```
