### ISSUE TITLE
greyhole does not install in debian jessie...

### ISSUE THREAD

**Issue by fantom1** [gboudreau/Greyhole#155]
samba-libs brings libsamba-debug.so.0 in ubuntu, but not in Jessie. Here is a link to the discussion https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1413164.html ...

Error: missing dependent library libsamba-debug.so.0 (libsamba-debug-samba4.so)
dpkg: error processing package greyhole (--configure):
 subprocess installed post-installation script returned error exit status 255
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Processing triggers for sgml-base (1.26+nmu4) ...
Errors were encountered while processing:
 greyhole
E: Sub-process /usr/bin/dpkg returned an error code (1)
bash: line 109: return: can only `return' from a function or sourced scrip

**Comment by gboudreau** [comment]
What if you `cd /usr/lib/x86_64-linux-gnu/ ; ln -s libsamba-util.so.0 libsamba-debug-samba4.so`
Does that resolve this, and allow the VFS module to work as expected?

**Comment by gboudreau** [comment]
Typo; I meant: `cd /usr/lib/x86_64-linux-gnu/samba/ ; ln -s ../libsamba-util.so.0 libsamba-debug-samba4.so`

**Comment by fantom1** [comment]
Thx; it installed this time. I will try running it later. BTW, the minimum Jessie installation is missing one package and the greyhole installation script fails at the very beginning.

OK
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?

**Comment by gboudreau** [comment]
Wow. So the Debian default repositories do not use HTTPS?

**Comment by fantom1** [comment]
No, they do not.
#

# deb cdrom:[Debian GNU/Linux 8.4.0 _Jessie_ - Official amd64 NETINST Binary-1 20160402-14:42]/ jessie main

#deb cdrom:[Debian GNU/Linux 8.4.0 _Jessie_ - Official amd64 NETINST Binary-1 20160402-14:42]/ jessie main

deb http://ftp.ca.debian.org/debian/ jessie main
deb-src http://ftp.ca.debian.org/debian/ jessie main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

# jessie-updates, previously known as 'volatile'
deb http://ftp.ca.debian.org/debian/ jessie-updates main
deb-src http://ftp.ca.debian.org/debian/ jessie-updates main

**Comment by fantom1** [comment]
Yes, the link is working even though "ldd" reports libsamba-debug-samba4.so as not found...


#ldd /usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so | grep libsamba
	libsamba-util.so.0 => /usr/lib/x86_64-linux-gnu/libsamba-util.so.0 (0x00007f558b759000)
	libsamba-debug-samba4.so => not found
	libsamba-cluster-support.so.0 => /usr/lib/x86_64-linux-gnu/samba/libsamba-cluster-support.so.0 (0x00007f5589151000)
	libsamba3-util.so.0 => /usr/lib/x86_64-linux-gnu/samba/libsamba3-util.so.0 (0x00007f5588f47000)
	libsamba-sockets.so.0 => /usr/lib/x86_64-linux-gnu/samba/libsamba-sockets.so.0 (0x00007f5588b2c000)
	libsamba-security.so.0 => /usr/lib/x86_64-linux-gnu/samba/libsamba-security.so.0 (0x00007f558890d000)
	libsamba-hostconfig.so.0 => /usr/lib/x86_64-linux-gnu/libsamba-hostconfig.so.0 (0x00007f5587ed2000)
	libsamba-modules.so.0 => /usr/lib/x86_64-linux-gnu/samba/libsamba-modules.so.0 (0x00007f558511b000)
	libsamba-credentials.so.0 => /usr/lib/x86_64-linux-gnu/libsamba-credentials.so.0 (0x00007f5584cd6000)

**Comment by gboudreau** [comment]
0.9.67 is now available, and should resolve this issue.
