### ISSUE TITLE
other vfs object issue

### ISSUE THREAD

**Issue by Grootent** [gboudreau/Greyhole#159]
This is now 2 times in a month that I have to repair my server Ubuntu 12:04 LTS 
with issue with Samba together with Greyhole after an update.
The first time I managed it with some symlinks now i do not know what to do

```
Greyhole version 0.9.67
Samba Version 4.3.9-Ubuntu
```

In the samba log I found the following error
```
[2016/05/05 13:16:02.998299,  0] ../lib/util/modules.c:48(load_module)
  Error loading module '/usr/lib/i386-linux-gnu/samba/vfs/greyhole.so': /usr/lib/i386-linux-gnu/samba/libutil-setid.so.0: version `SAMBA_4.3.8_UBUNTU' not found (required by /usr/lib/libsmbd-base-samba4.so)
[2016/05/05 13:16:02.998361,  0] ../source3/smbd/vfs.c:184(vfs_init_custom)
  error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
[2016/05/05 13:16:02.998390,  0] ../source3/smbd/vfs.c:349(smbd_vfs_init)
  smbd_vfs_init: vfs_init_custom failed for greyhole
[2016/05/05 13:16:02.998415,  0] ../source3/smbd/service.c:642(make_connection_snum)
  vfs_init failed for service Music
```

Any help here would be grateful.

**Comment by gboudreau** [comment]
How did you install Samba 4.3.9 on Ubuntu 12.04?
They seem to say only 3.6 is available for 12.04 here: http://packages.ubuntu.com/search?keywords=samba

**Comment by Grootent** [comment]
Oh sorry I forgot I upgradede the unbuntu server somtine ago I'm no at 
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

History of the apdates
Start-Date: 2016-05-04  06:44:45
Upgrade: libssl-dev:i386 (1.0.1f-1ubuntu2.18, 1.0.1f-1ubuntu2.19), 
openssl:i386(1.0.1f-1ubuntu2.18, 1.0.1f-1ubuntu2.19), 
libssl1.0.0:i386 (1.0.1f-1ubuntu2.18, 1.0.1f-1ubuntu2.19)
End-Date: 2016-05-04  06:44:54

Start-Date: 2016-05-05  06:28:47
Upgrade: libnss-winbind:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
libpam-smbpass:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
samba:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
samba-common-bin:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
winbind:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1),
samba-dbg:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1),
samba-common:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
libtevent0:i386 (0.9.26-0ubuntu0.14.04.1, 0.9.28-0ubuntu0.14.04.1), 
python-samba:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
samba-vfs-modules:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
samba-dsdb-modules:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
libsmbclient:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
liblcms2-2:i386 (2.5-0ubuntu4, 2.5-0ubuntu4.1), 
libpam-winbind:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 
4.3.9+dfsg-0ubuntu0.14.04.1), 
samba-doc:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
samba-libs:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
smbclient:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1), 
libwbclient0:i386 (4.3.8+dfsg-0ubuntu0.14.04.2, 4.3.9+dfsg-0ubuntu0.14.04.1)
End-Date: 2016-05-05  06:29:27

Start-Date: 2016-05-05  10:29:55
Commandline: apt-get install greyhole
Upgrade: greyhole:i386 (0.9.66-2, 0.9.67-2)
End-Date: 2016-05-05  10:30:35

**Comment by gboudreau** [comment]
I can't reproduce on the same Ubuntu, with the same packages versions. But I am on x86_64, not i386. So maybe that is where the problem is.

Try executing this in a shell, and paste here the result:

```shell
if [ -d /usr/lib/arm-linux-gnueabihf/samba/vfs ]; then
    TARGET_LIBDIR="/usr/lib/arm-linux-gnueabihf"
elif [ -d /usr/lib/x86_64-linux-gnu/samba/vfs ]; then
    TARGET_LIBDIR="/usr/lib/x86_64-linux-gnu"
elif [ "`uname -m`" = "x86_64" ]; then
    TARGET_LIBDIR="/usr/lib64"
    if [ -d /usr/lib/samba/vfs/ ]; then
        TARGET_LIBDIR="/usr/lib"
    fi
else
    TARGET_LIBDIR="/usr/lib"
fi
if [ ! -d ${TARGET_LIBDIR}/samba/vfs/ ]; then
    # Maybe samba-vfs-modules is missing?
    if [ -d /usr/lib/arm-linux-gnueabihf ]; then
        TARGET_LIBDIR="/usr/lib/arm-linux-gnueabihf"
    elif [ -d /usr/lib/x86_64-linux-gnu ]; then
        TARGET_LIBDIR="/usr/lib/x86_64-linux-gnu"
    else
        TARGET_LIBDIR="/usr/lib"
    fi
fi
echo "Target lib dir = ${TARGET_LIBDIR}"
ls -l ${TARGET_LIBDIR}/
ls -l ${TARGET_LIBDIR}/samba/
ls -l ${TARGET_LIBDIR}/samba/vfs/
```

**Comment by Grootent** [comment]
Here is the output of executing the shell commands:

fred@BEDROCK:~$ echo "Target lib dir = ${TARGET_LIBDIR}"
Target lib dir = /usr/lib
fred@BEDROCK:~$ ls -l ${TARGET_LIBDIR}/
total 12632
drwxr-xr-x  2 root root        4096 May 29  2015 accountsservice
drwxr-xr-x  3 root root        4096 Feb 18  2015 apache2
drwxr-xr-x  4 root root        4096 Apr 20 20:10 apt
drwxr-xr-x  2 root root        4096 Mar 25  2015 at-spi2-core
drwxr-xr-x  2 root root        4096 Feb 16  2015 avahi
drwxr-xr-x  3 root root        4096 Feb  4  2015 byobu
drwxr-xr-x  2 root root        4096 Feb  4  2015 cgi-bin
drwxr-xr-x  2 root root        4096 Mar 25  2015 colord
-rwxr-xr-x  1 root root        3274 Apr  3  2014 command-not-found
drwxr-xr-x  2 root root        4096 Apr 20 20:06 compat-ld
drwxr-xr-x  5 root root        4096 Feb 10  2015 ConsoleKit
drwxr-xr-x  2 root root        4096 Apr 20 20:06 coreutils
drwxr-xr-x  3 root root        4096 Feb  4  2015 cups
drwxr-xr-x  2 root root        4096 Feb  4  2015 dbus-1.0
drwxr-xr-x  2 root root        4096 Mar 25  2015 dconf
drwxr-xr-x  3 root root        4096 Apr 20 23:51 debug
drwxr-xr-x  4 root root        4096 Apr  2  2015 dpkg
drwxr-xr-x  2 root root        4096 Feb  4  2015 eject
drwxr-xr-x  3 root root        4096 Apr  2  2015 emacsen-common
drwxr-xr-x  3 root root        4096 Feb  4  2015 gcc
drwxr-xr-x  2 root root        4096 Feb  4  2015 girepository-1.0
drwxr-xr-x  3 root root       20480 Mar 22 06:26 git-core
drwxr-xr-x  2 root root        4096 Apr  2  2015 gnupg
drwxr-xr-x  2 root root        4096 Apr 20 20:06 gold-ld
drwxr-xr-x  2 root root        4096 May  5 10:30 greyhole
drwxr-xr-x  3 root root        4096 Apr 20 20:08 grub
drwxr-xr-x  2 root root        4096 Apr 20 20:08 grub-legacy
drwxr-xr-x  2 root root        4096 Apr 20 20:08 gvfs
drwxr-xr-x 47 root root       36864 May  5 06:29 i386-linux-gnu
drwxr-xr-x  3 root root        4096 Feb  4  2015 initramfs-tools
drwxr-xr-x  2 root root        4096 Feb  4  2015 insserv
drwxr-xr-x  3 root root        4096 Jul 31  2015 jvm
drwxr-xr-x  3 root root        4096 Feb  4  2015 klibc
drwxr-xr-x  2 root root        4096 Feb  4  2015 language-selector
drwxr-xr-x  2 root root       12288 Apr 20 20:06 ldscripts
-rw-r--r--  1 root root     1119360 Sep 16  2015 libbfd-2.24-system.so
lrwxrwxrwx  1 root root          18 Mar  8 15:55 libbind9.so.90 -> libbind9.so.90.0.9
-rw-r--r--  1 root root       50376 Mar  8 15:55 libbind9.so.90.0.9
lrwxrwxrwx  1 root root          19 Dec 18  2013 libcwidget.so.3 -> libcwidget.so.3.0.0
-rw-r--r--  1 root root     1054928 Dec 18  2013 libcwidget.so.3.0.0
lrwxrwxrwx  1 root root          18 Dec 13  2013 libdaemon.so.0 -> libdaemon.so.0.5.0
-rw-r--r--  1 root root       22020 Dec 13  2013 libdaemon.so.0.5.0
lrwxrwxrwx  1 root root          17 Mar  8 15:55 libdns.so.100 -> libdns.so.100.2.2
-rw-r--r--  1 root root     2005012 Mar  8 15:55 libdns.so.100.2.2
lrwxrwxrwx  1 root root          28 Aug  8  2014 libgirepository-1.0.so.1 -> libgirepository-1.0.so.1.0.0
-rw-r--r--  1 root root      219232 Aug  8  2014 libgirepository-1.0.so.1.0.0
lrwxrwxrwx  1 root root          18 Mar  8 15:55 libisccc.so.90 -> libisccc.so.90.0.6
-rw-r--r--  1 root root       34144 Mar  8 15:55 libisccc.so.90.0.6
lrwxrwxrwx  1 root root          19 Mar  8 15:55 libisccfg.so.90 -> libisccfg.so.90.1.0
-rw-r--r--  1 root root       98456 Mar  8 15:55 libisccfg.so.90.1.0
lrwxrwxrwx  1 root root          16 Mar  8 15:55 libisc.so.95 -> libisc.so.95.5.0
-rw-r--r--  1 root root      411840 Mar  8 15:55 libisc.so.95.5.0
lrwxrwxrwx  1 root root          18 Mar  8 15:55 liblwres.so.90 -> liblwres.so.90.0.7
-rw-r--r--  1 root root       75048 Mar  8 15:55 liblwres.so.90.0.7
lrwxrwxrwx  1 root root          34 Apr  2  2015 libmosquittopp.so.1 -> /usr/local/lib/libmosquittopp.so.1
-rw-r--r--  1 root root       30084 Aug 23  2013 libmosquitto.so.0
lrwxrwxrwx  1 root root          32 Apr  2  2015 libmosquitto.so.1 -> /usr/local/lib/libmosquitto.so.1
lrwxrwxrwx  1 root root          16 Jan  8  2014 libonig.so.2 -> libonig.so.2.0.0
-rw-r--r--  1 root root      302596 Jan  8  2014 libonig.so.2.0.0
-rw-r--r--  1 root root      830508 Sep 16  2015 libopcodes-2.24-system.so
lrwxrwxrwx  1 root root          18 Jan 17  2014 libqdbm.so.14 -> libqdbm.so.14.14.0
-rw-r--r--  1 root root      313664 Jan 17  2014 libqdbm.so.14.14.0
-rw-r--r--  1 root root       17936 Apr 21 00:03 libsamba-debug-samba4.so
lrwxrwxrwx  1 root root          24 Apr 22 06:29 libsamba-debug.so.0 -> libsamba-debug-samba4.so
-rw-r--r--  1 root root     3456364 Apr 21 00:01 libsmbd-base-samba4.so
lrwxrwxrwx  1 root root          22 Apr 22 06:29 libsmbd-base.so.0 -> libsmbd-base-samba4.so
lrwxrwxrwx  1 root root          21 Jul 23  2015 libtidy-0.99.so.0 -> libtidy-0.99.so.0.0.0
-rw-r--r--  1 root root      341636 Jul 23  2015 libtidy-0.99.so.0.0.0
lrwxrwxrwx  1 root root          21 Jul 23  2015 libtidy.so -> libtidy-0.99.so.0.0.0
lrwxrwxrwx  1 root root          20 Oct  5  2012 libutempter.so.0 -> libutempter.so.1.1.5
-rw-r--r--  1 root root        5448 Oct  5  2012 libutempter.so.1.1.5
lrwxrwxrwx  1 root root          30 Apr  2  2015 libwebsockets.a -> /usr/local/lib/libwebsockets.a
lrwxrwxrwx  1 root root          37 Apr  2  2015 libwebsockets.so.4.0.0 -> /usr/local/lib/libwebsockets.so.4.0.0
lrwxrwxrwx  1 root root          19 Dec 18  2013 libxapian.so.22 -> libxapian.so.22.6.3
-rw-r--r--  1 root root     2046060 Dec 18  2013 libxapian.so.22.6.3
drwxr-xr-x  3 root root        4096 Apr 20 20:08 linux-boot-probes
drwxr-xr-x  3 root root        4096 Feb  4  2015 locale
drwxr-xr-x  2 root root        4096 Feb  4  2015 man-db
drwxr-xr-x  2 root root        4096 Feb  4  2015 memtest86+
drwxr-xr-x  3 root root        4096 Feb  4  2015 mime
drwxr-xr-x  3 root root        4096 Feb  4  2015 mysql
drwxr-xr-x  2 root root        4096 Apr 20 20:08 openssh
drwxr-xr-x  2 root root        4096 Feb 12  2015 openvpn
drwxr-xr-x  2 root root        4096 Apr 20 20:08 os-prober
drwxr-xr-x  4 root root        4096 Apr 20 20:08 os-probes
drwxr-xr-x  3 root root        4096 Feb 12  2015 pcsc
drwxr-xr-x  3 root root        4096 Feb  4  2015 perl
drwxr-xr-x 13 root root        4096 Aug 20  2015 perl5
drwxr-xr-x  4 root root        4096 Aug 20  2015 php5
drwxr-xr-x  2 root root        4096 Feb 10  2015 pkgconfig
drwxr-xr-x  3 root root        4096 Aug 23  2015 plexmediaserver
drwxr-xr-x  4 root root        4096 Feb  4  2015 pm-utils
drwxr-xr-x  2 root root        4096 Apr 20 20:08 policykit-1
drwxr-xr-x  2 root root        4096 Mar 25  2015 policykit-1-gnome
drwxr-xr-x  3 root root        4096 Feb  4  2015 pppd
-rwsr-xr-x  1 root root        9612 Feb 16 20:20 pt_chown
drwxr-xr-x  3 root root        4096 Feb  4  2015 pyshared
drwxr-xr-x 26 root root       28672 Aug 21  2015 python2.7
drwxr-xr-x  3 root root        4096 Feb  4  2015 python3
drwxr-xr-x 32 root root       20480 Apr 20 20:07 python3.4
drwxr-xr-x  4 root root        4096 Apr  2  2015 rpm
drwxr-xr-x  2 root root        4096 May 17  2015 rsyslog
drwxr-xr-x  4 root root        4096 Apr 20 22:49 samba
drwxr-xr-x  2 root root        4096 Nov  2  2013 sasl2
lrwxrwxrwx  1 root root          19 Jan 27 02:36 sftp-server -> openssh/sftp-server
drwxr-xr-x  2 root root        4096 Apr 20 20:08 software-properties
drwxr-xr-x  2 root root        4096 Feb  4  2015 sse2
drwxr-xr-x  3 root root        4096 May  4 06:44 ssl
drwxr-xr-x  2 root root        4096 Apr 20 20:08 sudo
drwxr-xr-x  2 root root        4096 Feb  4  2015 sysstat
drwxr-xr-x  3 root root        4096 Feb  4  2015 systemd
drwxr-xr-x  2 root root        4096 Feb  4  2014 tar
drwxr-xr-x  5 root root        4096 Feb  4  2015 tasksel
drwxr-xr-x  2 root root        4096 Aug 20  2015 tc
drwxr-xr-x  3 root root        4096 Apr  2  2015 tcltk
drwxr-xr-x  2 root root        4096 May  5 06:29 tmpfiles.d
drwxr-xr-x  2 root root        4096 Apr 20 20:08 ubuntu-release-upgrader
drwxr-xr-x  2 root root        4096 Jul 19  2015 udisks2
drwxr-xr-x  2 root root        4096 Feb  4  2015 update-notifier
drwxr-xr-x  2 root root        4096 Feb  4  2015 upstart
drwxr-xr-x  2 root utempter    4096 Apr  2  2015 utempter
drwxr-xr-x  2 root root        4096 Feb  4  2015 valgrind
drwxr-xr-x  3 root root        4096 Feb  4  2015 w3m
drwxr-xr-x  2 root root        4096 Dec 10  2014 X11
fred@BEDROCK:~$ ls -l ${TARGET_LIBDIR}/samba/
total 8
lrwxrwxrwx 1 root root   49 Apr 20 22:49 libsamba-debug-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsamba-debug.so.0
lrwxrwxrwx 1 root root   49 Apr 20 21:52 libsamba-debug.so.0 -> /usr/lib/i386-linux-gnu/samba/libsamba-debug.so.0
lrwxrwxrwx 1 root root   47 Apr 20 22:47 libsmbd-base-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
lrwxrwxrwx 1 root root   47 Apr 20 21:43 libsmbd-base.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
lrwxrwxrwx 1 root root   47 Apr 20 21:48 libsmbd-base.so.0 -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
drwxr-xr-x 2 root root 4096 Jun 25  2014 nss_info
drwxr-xr-x 2 root root 4096 May  5 10:30 vfs
fred@BEDROCK:~$ ls -l ${TARGET_LIBDIR}/samba/vfs/
total 0
lrwxrwxrwx 1 root root 37 May  5 10:30 greyhole.so -> /usr/lib/greyhole/greyhole-samba43.so
lrwxrwxrwx 1 root root 47 Apr 20 23:42 libsmbd-base-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
fred@BEDROCK:~$

**Comment by gboudreau** [comment]
Pretty sure you should not have those files in `/usr/lib`:
```
-rw-r--r--  1 root root       17936 Apr 21 00:03 libsamba-debug-samba4.so
lrwxrwxrwx  1 root root          24 Apr 22 06:29 libsamba-debug.so.0 -> libsamba-debug-samba4.so
-rw-r--r--  1 root root     3456364 Apr 21 00:01 libsmbd-base-samba4.so
lrwxrwxrwx  1 root root          22 Apr 22 06:29 libsmbd-base.so.0 -> libsmbd-base-samba4.so
```
My guess: you manually copied the 4.3.8 versions of those in there, and those are now used, instead of the 4.3.9 versions that are in `/usr/lib/i386-linux-gnu/samba/`.

**Comment by Grootent** [comment]
Okay that is possible I copied somefiles 2 or 3 weeks ago then I also got stuck with broken samba.
From the logging it says that the aspected libraries overthere so copied them over there and then it works. Now they fixed that I ques, and now I have to redo those actions. Monday evening i have time and i will try to fixed this. And let you know the results, thanks !!!

**Comment by Grootent** [comment]
its running again 

removed the files in /usr/lib
then i have create to links back 

when i run your script it looks like this

fred@BEDROCK:~$ echo "Target lib dir = ${TARGET_LIBDIR}"
Target lib dir = /usr/lib
fred@BEDROCK:~$ ls -l ${TARGET_LIBDIR}/
total 9236
drwxr-xr-x  2 root root        4096 May 29  2015 accountsservice
drwxr-xr-x  3 root root        4096 Feb 18  2015 apache2
drwxr-xr-x  4 root root        4096 Apr 20 20:10 apt
drwxr-xr-x  2 root root        4096 Mar 25  2015 at-spi2-core
drwxr-xr-x  2 root root        4096 Feb 16  2015 avahi
drwxr-xr-x  3 root root        4096 Feb  4  2015 byobu
drwxr-xr-x  2 root root        4096 Feb  4  2015 cgi-bin
drwxr-xr-x  2 root root        4096 Mar 25  2015 colord
-rwxr-xr-x  1 root root        3274 Apr  3  2014 command-not-found
drwxr-xr-x  2 root root        4096 Apr 20 20:06 compat-ld
drwxr-xr-x  5 root root        4096 Feb 10  2015 ConsoleKit
drwxr-xr-x  2 root root        4096 Apr 20 20:06 coreutils
drwxr-xr-x  3 root root        4096 Feb  4  2015 cups
drwxr-xr-x  2 root root        4096 Feb  4  2015 dbus-1.0
drwxr-xr-x  2 root root        4096 Mar 25  2015 dconf
drwxr-xr-x  3 root root        4096 Apr 20 23:51 debug
drwxr-xr-x  4 root root        4096 Apr  2  2015 dpkg
drwxr-xr-x  2 root root        4096 Feb  4  2015 eject
drwxr-xr-x  3 root root        4096 Apr  2  2015 emacsen-common
drwxr-xr-x  3 root root        4096 Feb  4  2015 gcc
drwxr-xr-x  2 root root        4096 Feb  4  2015 girepository-1.0
drwxr-xr-x  3 root root       20480 Mar 22 06:26 git-core
drwxr-xr-x  2 root root        4096 Apr  2  2015 gnupg
drwxr-xr-x  2 root root        4096 Apr 20 20:06 gold-ld
drwxr-xr-x  2 root root        4096 May  5 10:30 greyhole
drwxr-xr-x  3 root root        4096 Apr 20 20:08 grub
drwxr-xr-x  2 root root        4096 Apr 20 20:08 grub-legacy
drwxr-xr-x  2 root root        4096 Apr 20 20:08 gvfs
drwxr-xr-x 47 root root       36864 May 11 23:57 i386-linux-gnu
drwxr-xr-x  3 root root        4096 Feb  4  2015 initramfs-tools
drwxr-xr-x  2 root root        4096 Feb  4  2015 insserv
drwxr-xr-x  3 root root        4096 Jul 31  2015 jvm
drwxr-xr-x  3 root root        4096 Feb  4  2015 klibc
drwxr-xr-x  2 root root        4096 Feb  4  2015 language-selector
drwxr-xr-x  2 root root       12288 Apr 20 20:06 ldscripts
-rw-r--r--  1 root root     1119360 Sep 16  2015 libbfd-2.24-system.so
lrwxrwxrwx  1 root root          18 Mar  8 15:55 libbind9.so.90 -> libbind9.so.90.0.9
-rw-r--r--  1 root root       50376 Mar  8 15:55 libbind9.so.90.0.9
lrwxrwxrwx  1 root root          19 Dec 18  2013 libcwidget.so.3 -> libcwidget.so.3.0.0
-rw-r--r--  1 root root     1054928 Dec 18  2013 libcwidget.so.3.0.0
lrwxrwxrwx  1 root root          18 Dec 13  2013 libdaemon.so.0 -> libdaemon.so.0.5.0
-rw-r--r--  1 root root       22020 Dec 13  2013 libdaemon.so.0.5.0
lrwxrwxrwx  1 root root          17 Mar  8 15:55 libdns.so.100 -> libdns.so.100.2.2
-rw-r--r--  1 root root     2005012 Mar  8 15:55 libdns.so.100.2.2
lrwxrwxrwx  1 root root          28 Aug  8  2014 libgirepository-1.0.so.1 -> libgirepository-1.0.so.1.0.0
-rw-r--r--  1 root root      219232 Aug  8  2014 libgirepository-1.0.so.1.0.0
lrwxrwxrwx  1 root root          18 Mar  8 15:55 libisccc.so.90 -> libisccc.so.90.0.6
-rw-r--r--  1 root root       34144 Mar  8 15:55 libisccc.so.90.0.6
lrwxrwxrwx  1 root root          19 Mar  8 15:55 libisccfg.so.90 -> libisccfg.so.90.1.0
-rw-r--r--  1 root root       98456 Mar  8 15:55 libisccfg.so.90.1.0
lrwxrwxrwx  1 root root          16 Mar  8 15:55 libisc.so.95 -> libisc.so.95.5.0
-rw-r--r--  1 root root      411840 Mar  8 15:55 libisc.so.95.5.0
lrwxrwxrwx  1 root root          18 Mar  8 15:55 liblwres.so.90 -> liblwres.so.90.0.7
-rw-r--r--  1 root root       75048 Mar  8 15:55 liblwres.so.90.0.7
lrwxrwxrwx  1 root root          34 Apr  2  2015 libmosquittopp.so.1 -> /usr/local/lib/libmosquittopp.so.1
-rw-r--r--  1 root root       30084 Aug 23  2013 libmosquitto.so.0
lrwxrwxrwx  1 root root          32 Apr  2  2015 libmosquitto.so.1 -> /usr/local/lib/libmosquitto.so.1
lrwxrwxrwx  1 root root          16 Jan  8  2014 libonig.so.2 -> libonig.so.2.0.0
-rw-r--r--  1 root root      302596 Jan  8  2014 libonig.so.2.0.0
-rw-r--r--  1 root root      830508 Sep 16  2015 libopcodes-2.24-system.so
lrwxrwxrwx  1 root root          18 Jan 17  2014 libqdbm.so.14 -> libqdbm.so.14.14.0
-rw-r--r--  1 root root      313664 Jan 17  2014 libqdbm.so.14.14.0
lrwxrwxrwx  1 root root          49 May 11 23:53 libsamba-debug-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsamba-debug.so.0
lrwxrwxrwx  1 root root          24 May 11 23:57 libsamba-debug.so.0 -> libsamba-debug-samba4.so
lrwxrwxrwx  1 root root          47 May 11 23:47 libsmbd-base-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
lrwxrwxrwx  1 root root          22 May 11 23:57 libsmbd-base.so.0 -> libsmbd-base-samba4.so
lrwxrwxrwx  1 root root          21 Jul 23  2015 libtidy-0.99.so.0 -> libtidy-0.99.so.0.0.0
-rw-r--r--  1 root root      341636 Jul 23  2015 libtidy-0.99.so.0.0.0
lrwxrwxrwx  1 root root          21 Jul 23  2015 libtidy.so -> libtidy-0.99.so.0.0.0
lrwxrwxrwx  1 root root          20 Oct  5  2012 libutempter.so.0 -> libutempter.so.1.1.5
-rw-r--r--  1 root root        5448 Oct  5  2012 libutempter.so.1.1.5
lrwxrwxrwx  1 root root          30 Apr  2  2015 libwebsockets.a -> /usr/local/lib/libwebsockets.a
lrwxrwxrwx  1 root root          37 Apr  2  2015 libwebsockets.so.4.0.0 -> /usr/local/lib/libwebsockets.so.4.0.0
lrwxrwxrwx  1 root root          19 Dec 18  2013 libxapian.so.22 -> libxapian.so.22.6.3
-rw-r--r--  1 root root     2046060 Dec 18  2013 libxapian.so.22.6.3
drwxr-xr-x  3 root root        4096 Apr 20 20:08 linux-boot-probes
drwxr-xr-x  3 root root        4096 Feb  4  2015 locale
drwxr-xr-x  2 root root        4096 Feb  4  2015 man-db
drwxr-xr-x  2 root root        4096 Feb  4  2015 memtest86+
drwxr-xr-x  3 root root        4096 Feb  4  2015 mime
drwxr-xr-x  3 root root        4096 Feb  4  2015 mysql
drwxr-xr-x  2 root root        4096 May 10 06:41 openssh
drwxr-xr-x  2 root root        4096 Feb 12  2015 openvpn
drwxr-xr-x  2 root root        4096 Apr 20 20:08 os-prober
drwxr-xr-x  4 root root        4096 Apr 20 20:08 os-probes
drwxr-xr-x  3 root root        4096 Feb 12  2015 pcsc
drwxr-xr-x  3 root root        4096 Feb  4  2015 perl
drwxr-xr-x 13 root root        4096 Aug 20  2015 perl5
drwxr-xr-x  4 root root        4096 Aug 20  2015 php5
drwxr-xr-x  2 root root        4096 Feb 10  2015 pkgconfig
drwxr-xr-x  3 root root        4096 Aug 23  2015 plexmediaserver
drwxr-xr-x  4 root root        4096 Feb  4  2015 pm-utils
drwxr-xr-x  2 root root        4096 Apr 20 20:08 policykit-1
drwxr-xr-x  2 root root        4096 Mar 25  2015 policykit-1-gnome
drwxr-xr-x  3 root root        4096 Feb  4  2015 pppd
-rwsr-xr-x  1 root root        9612 Feb 16 20:20 pt_chown
drwxr-xr-x  3 root root        4096 Feb  4  2015 pyshared
drwxr-xr-x 26 root root       28672 Aug 21  2015 python2.7
drwxr-xr-x  3 root root        4096 Feb  4  2015 python3
drwxr-xr-x 32 root root       20480 Apr 20 20:07 python3.4
drwxr-xr-x  4 root root        4096 Apr  2  2015 rpm
drwxr-xr-x  2 root root        4096 May 17  2015 rsyslog
drwxr-xr-x  4 root root        4096 May 11 23:24 samba
drwxr-xr-x  2 root root        4096 Nov  2  2013 sasl2
lrwxrwxrwx  1 root root          19 May  5 16:17 sftp-server -> openssh/sftp-server
drwxr-xr-x  2 root root        4096 Apr 20 20:08 software-properties
drwxr-xr-x  2 root root        4096 Feb  4  2015 sse2
drwxr-xr-x  3 root root        4096 May  4 06:44 ssl
drwxr-xr-x  2 root root        4096 Apr 20 20:08 sudo
drwxr-xr-x  2 root root        4096 Feb  4  2015 sysstat
drwxr-xr-x  3 root root        4096 Feb  4  2015 systemd
drwxr-xr-x  2 root root        4096 Feb  4  2014 tar
drwxr-xr-x  5 root root        4096 Feb  4  2015 tasksel
drwxr-xr-x  2 root root        4096 Aug 20  2015 tc
drwxr-xr-x  3 root root        4096 Apr  2  2015 tcltk
drwxr-xr-x  2 root root        4096 May 10 06:41 tmpfiles.d
drwxr-xr-x  2 root root        4096 Apr 20 20:08 ubuntu-release-upgrader
drwxr-xr-x  2 root root        4096 Jul 19  2015 udisks2
drwxr-xr-x  2 root root        4096 Feb  4  2015 update-notifier
drwxr-xr-x  2 root root        4096 Feb  4  2015 upstart
drwxr-xr-x  2 root utempter    4096 Apr  2  2015 utempter
drwxr-xr-x  2 root root        4096 Feb  4  2015 valgrind
drwxr-xr-x  3 root root        4096 Feb  4  2015 w3m
drwxr-xr-x  2 root root        4096 Dec 10  2014 X11
fred@BEDROCK:~$ ls -l ${TARGET_LIBDIR}/samba/
total 8
lrwxrwxrwx 1 root root   49 May 11 23:23 libsamba-debug-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsamba-debug.so.0
lrwxrwxrwx 1 root root   49 May 11 23:11 libsamba-debug.so.0 -> /usr/lib/i386-linux-gnu/samba/libsamba-debug.so.0
lrwxrwxrwx 1 root root   47 May 11 23:24 libsmbd-base-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
lrwxrwxrwx 1 root root   47 Apr 20 21:43 libsmbd-base.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
lrwxrwxrwx 1 root root   47 May 11 23:12 libsmbd-base.so.0 -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
drwxr-xr-x 2 root root 4096 Jun 25  2014 nss_info
drwxr-xr-x 2 root root 4096 May 11 23:26 vfs
fred@BEDROCK:~$ ls -l ${TARGET_LIBDIR}/samba/vfs/
total 0
lrwxrwxrwx 1 root root 37 May  5 10:30 greyhole.so -> /usr/lib/greyhole/greyhole-samba43.so
lrwxrwxrwx 1 root root 47 May 11 23:26 libsmbd-base-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
fred@BEDROCK:~$ ls -l /usr/lib/libsmbd-base-samba4.so
lrwxrwxrwx 1 root root 47 May 11 23:47 /usr/lib/libsmbd-base-samba4.so -> /usr/lib/i386-linux-gnu/samba/libsmbd-base.so.0
fred@BEDROCK:~$ strings /usr/lib/libsmbd-base-samba4.so | grep UBUNTU
SAMBA_4.3.9_UBUNTU
