### ISSUE TITLE
Clarify minimum recommended file size for files shared with Greyhole

### ISSUE THREAD

**Issue by RollingStar** [gboudreau/Greyhole#160]
>[Using Greyhole to store a lot of small files is not-a-good-idea™.](https://greyhole.net/)

How small can the files be? Is Greyhole acceptable for digital photos (1 MB to 8 MB each)? More broadly, what file size should users target?

**Comment by gboudreau** [comment]
The file size doesn't really matter, as long as you don't have millions of them. The issue with a lot of small files is that the Greyhole overhead will be very noticeable. With larger files, the time it takes to copy the files to other drives and such is much longer than the Greyhole overhead, so you don't really notice it.
Digital photos collections is a perfect use. I have 150k photos in my library, and while the weekly fsck takes a while, everything works fine with that share.

**Comment by RollingStar** [comment]
Thank you. That makes me think Greyhole is a good fit for my storage needs. The language on the homepage might scare away potential users. At a minimum it might be a good idea to explain what you wrote above in the [wiki page it links to](https://github.com/gboudreau/Greyhole/wiki/WhatNotToPutInGreyholeShares).

**Comment by gboudreau** [comment]
Good idea; will do.
