### ISSUE TITLE
Crash after setting drive gone

### ISSUE THREAD

**Issue by Sperryfreak01** [gboudreau/Greyhole#161]
Had a drive fail, so I marked it as gone
`greyhole -g /mnt/drive1`

> Storage pool drive /mnt/drive1 has been removed from your pool, which means the missing file copies that are in this drive will be re-created during the next fsck.
> Sadly, file copies that were only on this drive, if any, are now lost!

I then went to queue up a fsck
`sudo greyhole -f`

> fsck of all shares has been scheduled. It will start after all currently pending tasks have been completed.
> PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[HY000]: General error: 126 Incorrect key file for table './greyhole/du_stats.MYI'; try to repair it' in /usr/bin/greyhole:599
> Stack trace:
> #0 /usr/bin/greyhole(5131): DB::execute('DELETE FROM du_...', Array)
> #1 /usr/bin/greyhole(3573): gh_fsck_reset_du('Apps', '')
> #2 /usr/bin/greyhole(3326): execute_next_task()
> #3 /usr/bin/greyhole(3353): DaemonRunner->run()
> #4 {main}
>   thrown in /usr/bin/greyhole on line 599

Wierd, when in doubt restart it, 

`bash-4.1$ sudo service greyhole restart`

> Shutting down Greyhole ...                                 [  OK  ]
> Starting Greyhole ...                                      [  OK  ]
> PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[HY000]: General error: 126 Incorrect key file for table './greyhole/du_stats.MYI'; try to repair it' in /usr/bin/greyhole:599
> Stack trace:
> #0 /usr/bin/greyhole(5131): DB::execute('DELETE FROM du_...', Array)
> #1 /usr/bin/greyhole(3573): gh_fsck_reset_du('Apps', '')
> #2 /usr/bin/greyhole(3326): execute_next_task()
> #3 /usr/bin/greyhole(3353): DaemonRunner->run()
> #4 {main}
>   thrown in /usr/bin/greyhole on line 599

Not sure what to do now but greyhole will not start.

**Comment by Sperryfreak01** [comment]
plot thickens, I issued a 
`sudo greyhole -C` and then restarted the greyhole daemon and it started without issue.

**Comment by gboudreau** [comment]
The problem is that a MySQL table used during fsck is broken.
Connect to mysql, using either root, or the credentials from greyhole.conf, and execute this command:
`repair table du_stats;`
Then you should be able to run a fsck.

**Comment by Sperryfreak01** [comment]
Worked, thanks for the great support as always.
