### ISSUE TITLE
Greyhole Daemon won't start, MYSQL error.

### ISSUE THREAD

**Issue by brendog** [gboudreau/Greyhole#172]
greyhole, version 0.10.4

```
PHP Fatal error:  Uncaught Exception: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'complete' at row 1 in /usr/bin/greyhole:624
Stack trace:
#0 /usr/bin/greyhole(5144): DB::execute('UPDATE tasks SE...', Array)
#1 /usr/bin/greyhole(5047): close_task('fwrite', 'TV', '40', Array)
#2 /usr/bin/greyhole(3626): parse_samba_spool()
#3 /usr/bin/greyhole(3601): DaemonRunner->initialize()
#4 /usr/bin/greyhole(3635): DaemonRunner->run()
#5 {main}
  thrown in /usr/bin/greyhole on line 624
```

**Comment by gboudreau** [comment]
Could you run this in MySQL, and paste here what you get?

    DESCRIBE tasks;

**Comment by brendog** [comment]
`mysql>  DESCRIBE tasks;
+-----------------+-------------------------------------------+------+-----+-------------------+----------------+
| Field           | Type                                      | Null | Key | Default           | Extra          |
+-----------------+-------------------------------------------+------+-----+-------------------+----------------+
| id              | bigint(20) unsigned                       | NO   | PRI | NULL              | auto_increment |
| action          | varchar(10)                               | NO   | MUL | NULL              |                |
| share           | varchar(255)                              | NO   |     | NULL              |                |
| full_path       | varchar(255)                              | YES  |     | NULL              |                |
| additional_info | varchar(255)                              | YES  |     | NULL              |                |
| complete        | enum('yes','no','frozen','thawed','idle') | NO   | MUL | NULL              |                |
| event_date      | timestamp                                 | NO   |     | CURRENT_TIMESTAMP |                |
+-----------------+-------------------------------------------+------+-----+-------------------+----------------+
7 rows in set (0.01 sec)
`

**Comment by gboudreau** [comment]
0.10.5 should resolve this.
