### ISSUE TITLE
Use HTTPS in bit.ly link on homepage

### ISSUE THREAD

**Issue by RollingStar** [gboudreau/Greyhole#173]
>Installing Greyhole

>Step 1

>Using APT (Ubuntu, Debian) or Yum (CentOS, Fedora, RHEL)

    curl -Ls http://bit.ly/gh-install-package | sudo bash

Adding an S to the http seems to work fine and should make things more secure. Currently, an attacker with network access (Wifi host, ISP, government) could hijack the bit.ly request and direct it to malicious terminal commands. Right?

**Comment by gboudreau** [comment]
Good catch. Fixed.

**Comment by RollingStar** [comment]
One more. I think that's all the plain http links that would be dangerous if intercepted. https://github.com/gboudreau/Greyhole/wiki/GetHelp
