### ISSUE TITLE
Greyhole wont start after update to greyhole 0.10.5 on Ubuntu 14.04 

### ISSUE THREAD

**Issue by spacezorro** [gboudreau/Greyhole#174]
Error message:
PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[HY000]: General error: 1089 Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys' in /usr/bin/greyhole:624
Stack trace:
#0 /usr/bin/greyhole(786): DB::execute('ALTER TABLE `du...')
#1 /usr/bin/greyhole(701): DB::migrate_8_du_stats()
#2 /usr/bin/greyhole(600): DB::migrate()
#3 /usr/bin/greyhole(3410): DB::connect(false)
#4 /usr/bin/greyhole(3372): CommandLineHelper->getRunner()
#5 /usr/bin/greyhole(3606): CommandLineHelper->processCommandLine()
#6 {main}
  thrown in /usr/bin/greyhole on line 624

**Comment by spacezorro** [comment]
mysql> DESCRIBE du_stats;
+-----------+---------------------+------+-----+---------+-------+
| Field     | Type                | Null | Key | Default | Extra |
+-----------+---------------------+------+-----+---------+-------+
| share     | varchar(255)        | NO   |     | NULL    |       |
| full_path | varchar(255)        | NO   |     | NULL    |       |
| depth     | tinyint(3) unsigned | NO   |     | NULL    |       |
| size      | bigint(20) unsigned | NO   |     | NULL    |       |
+-----------+---------------------+------+-----+---------+-------+
4 rows in set (0.00 sec)

**Comment by gboudreau** [comment]
No idea how your `share` and `full_path` columns can be `varchar`, while that index wouldn't exist, but try executing this MySQL command, and restarting Greyhole:
```
ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`);
```

**Comment by spacezorro** [comment]
mysql> ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`);
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0

Greyhole started OK after this.

**Comment by spacezorro** [comment]
Would you like anything else to figure why my database is wierd?

**Comment by gboudreau** [comment]
Will look into it if someone else reports a similar problem. Otherwise, let's assume this was just a one time thing...
