### ISSUE TITLE
Debian 9 - Removal of MySQL

### ISSUE THREAD

**Issue by Armoryh** [gboudreau/Greyhole#175]
In the future, MySQL has been removed from the upcoming Debian 9.
Will Greyhole add support for MariaDB instead?

This will be a future issue either way, the way i see it. But i apologise if this post is in the wrong place.

**Comment by gboudreau** [comment]
Totally the right place for this.

The RPM already allows MariaDB as an alternative:

```
Depends: [...], mysql-server | mysql-server-5.5 | mysql-server-5.6 | mariadb-server | mariadb-server-5.5 | mariadb-server-5.6, [...]
```
Ref: https://github.com/gboudreau/Greyhole/blob/master/DEBIAN/control#L8

If the Debian 9 MariaDB package(s) are listed above, it should work fine.

Cheers.
