### ISSUE TITLE
Error with Disk Utilization Web App

### ISSUE THREAD

**Issue by bigfoot65** [gboudreau/Greyhole#178]
Hello,

When drilling down with the Disk Utilization web app, there is an error.  Once there are no more folders, it comes up with a message:  

SQL Error

The greyhole.log file reflects:
Jun 26 19:34:57 WARN initialize: PHP Warning [8]: Undefined property: stdClass::
$error in /usr/share/greyhole/web-app/index.php on line 690; BT: index.php[L1] i
nclude(/usr/share/greyhole/web-app/index.php) => index.php[L2313] error()
Jun 26 19:34:57 ERROR initialize: PHP Fatal Error: Undefined index: warning; BT:
 index.php[L961]

An Amahi user also reported the same issue today.  Please advise.

BTW, using Fedora 25, Greyhole version 0.10.6.  I realize there is an updated version, but did not see where this issue was previously reported.

**Comment by gboudreau** [comment]
0.10.10 contains the fix
