### ISSUE TITLE
Everything seems to be locked by Samba

### ISSUE THREAD

**Issue by Sparticuz** [gboudreau/Greyhole#179]
Yesterday I noticed that my LZ had completely filled so I checked the Greyhole logs and it looked like it wasn't talking with Samba correctly. Greyhole would just stop when it was trying to process the samba pool. So I downgraded to 4.5, ran a fsck overnight, and everything looked good this morning. However, when I started to work on my server this morning, it's looking like I'm having some file locking problems. The first file complains that samba-vfs-writer has locked it, then it goes through every file I've added or changed telling me everything is locked. I've tried restarting greyhole and samba. I've even tried upgrading back to 4.6 (which seems to be loading the vfs module just fine now), but it's still giving me the same locking error.

````
Jun 29 09:19:43 INFO daemon: Greyhole (version 0.10.10) daemon started.
Jun 29 09:19:43 INFO daemon: Optimizing MySQL tables...
Jun 29 09:19:43 DEBUG daemon: Loading metadata store backup directories...
Jun 29 09:19:43 DEBUG daemon:   Found 2 directories in the settings table.
Jun 29 09:19:44 DEBUG daemon: Checking symlink at /usr/lib/samba/vfs/greyhole.so...
Jun 29 09:19:44 DEBUG daemon:   Is OK.
Jun 29 09:19:44 INFO write: Now working on task ID 498189: write Movies/Home Alone (1990)/Home Alone (1990).mkv
Jun 29 09:19:44 INFO write: File created: Movies/Home Alone (1990)/Home Alone (1990).mkv - 4.37GB
Jun 29 09:19:44 DEBUG write: Loading metafiles for Movies/Home Alone (1990)/Home Alone (1990).mkv ...
Jun 29 09:19:44 DEBUG write:   Got 0 metadata files.
Jun 29 09:19:44 DEBUG write: 0 metafiles loaded.
Jun 29 09:19:44 DEBUG write:   File Movies/Home Alone (1990)/Home Alone (1990).mkv is locked by another process (samba-vfs-writer). Will wait until it's unlocked to work on any file in this share.
Jun 29 09:19:44 INFO write: Now working on task ID 498190: write Movies/Home Alone 2 - Lost in New York (1992)/Home Alone 2 Lost In New York (1992).mkv
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
Jun 29 09:19:44 INFO write: Now working on task ID 498191: write Movies/Home Alone (1990)/.steve
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
Jun 29 09:19:44 INFO write: Now working on task ID 498192: write Movies/Home Alone 2 - Lost in New York (1992)/.steve
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
Jun 29 09:19:44 INFO write: Now working on task ID 498193: write Movies/Fireproof (2008)/.steve
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
Jun 29 09:19:44 INFO write: Now working on task ID 498196: write Movies/Hitch (2005)/.steve
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
Jun 29 09:19:44 INFO write: Now working on task ID 498197: write Movies/I, Robot (2004)/.steve
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
Jun 29 09:19:44 INFO write: Now working on task ID 498198: write Movies/Independence Day (1996)/.steve
Jun 29 09:19:44 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
````

**Comment by Sparticuz** [comment]
`smbstatus` says No locked files

**Comment by Sparticuz** [comment]
Not sure if related, it looks like rows are being added into the database, but nothing is being said about those files in the log.

**Comment by gboudreau** [comment]
You seem to have a single file locked; anything you do on this share after that will NOT be worked on until that locked is released, because Greyhole needs to replay operations in the same order they were executed on the Samba share, or risk losing files.
That's why the daemon log says "Share is locked".

As for the reason why that file is locked:
```
Jun 29 09:19:44 DEBUG write:   File Movies/Home Alone (1990)/Home Alone (1990).mkv is locked by another process (samba-vfs-writer). Will wait until it's unlocked to work on any file in this share.
```

here's the command Greyhole uses to check for locks:

```
lsof -M -n -P -l $REAL_PATH
```

Where `$REAL_PATH` is the path to the file in question, in your case:

```
/path/to/share/Movies/Home Alone 2 - Lost in New York (1992)/Home Alone 2 Lost In New York (1992).mkv
```

If the file at `$REAL_PATH` is a symlink, the `lsof` command is run on the full path of the target of the symlink, instead of the full path of the symlink.

**Comment by Sparticuz** [comment]
(those should be two seperate files)

when I issue that command on both of those files, I get nothing returned.

**Comment by gboudreau** [comment]
Ah, wait... `samba-bytes-writer` is a special name Greyhole uses, not a real process name!

Can you run this:

```
grep -e 'File is still being written to|Only locked files operations pending' /var/log/greyhole.log
```

That first string is when the Greyhole daemon detects the file in question is still being written to, by looking for changes in the file size of that file.
And the second string is when that lock (cache) should be deleted (to be checked again next time the op would need to be processed).

**Comment by Sparticuz** [comment]
The grep command doesn't return anything

**Comment by gboudreau** [comment]
Ah, sorry... There is a distinction between `samba-vfs-writer` and `samba-bytes-writer`. My bad, I confused the two.
The one you hitting is `samba-vfs-writer`.
That means the DB has a write operation that has the `complete` flag set to `no`. That flag is changed to `yes` when the Samba VFS module notify Greyhole that a file write is complete.
If Samba somehow crashes, that could leave such a write operation with `complete=no`.
To fix it, you can either reboot, or execute this manually, as root:
```
/usr/bin/greyhole --boot-init
```

This command is executed by `cron` on reboot, and changes all the `complete` flags in the DB to `yes`.

**Comment by Sparticuz** [comment]
Hmm, I did try a reboot this morning, but oh well, --boot-init seems to have fixed it. Thank you!
