### ISSUE TITLE
Mount Shares Locally on CentOS

### ISSUE THREAD

**Issue by astrom0** [gboudreau/Greyhole#181]
Finally made it through [USAGE](https://raw.githubusercontent.com/gboudreau/Greyhole/master/USAGE) and made it to the bottom. Just so we're clear, for [reasons specific to my hardware](https://github.com/ipilcher/n5550/issues/13), I'm running Centos 7 via USB on a Thecus N5550 sporting 5 x 3TB HDDs.

I'm seeing this when I run the relevant command:
`$ greyhole --logs`

> Jul 22 22:45:08 DEBUG sleep: Nothing to do... Sleeping.
> Jul 22 22:45:18 DEBUG sleep: Nothing to do... Sleeping.
> ^C

`$ journalctl -xe`

> No journal files were found.
> -- No entries --

So, I must have done something right.

My issue is when I try to [Mount Shares Locally](https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally). I get to the 2nd command in Step 2 and get the response noted below:
`$ sudo update-rc.d mount_shares_locally defaults`

> sudo: update-rc.d: command not found

Following on, I've discovered that Centos (and I'm pretty sure Fedora) does not employ _**update-rc.d**_ as a system command. Apparently, what's used is **_chkconfig_** but it's not a simply copy/paste. I'm riding on Linux trainer wheels, so can anyone offer some useful suggestions as to how I should make this final step in the process work?

I've searched the open and closed issues and couldn't spot anything relevant (apologies if I missed anything obvious).

Thanks in advance for any help. Hopefully it's a simple one. Cheers.

**Comment by uSlackr** [comment]
I don't run Centos, but do run Linux. Sounds like you need to make that script a service.  Here is a link to doing so on Centos.  Hope it helps.
https://superuser.com/questions/284410/how-do-i-create-a-service-using-chkconfig-in-centos
A Centos support forum would be a good place to ask further questions.

\\\\Greg
________________________________

**Comment by gboudreau** [comment]
You can simply run the third command, which uses chkconfig to enable the script on startup. I'll update the instructions do that no error is returned to users who are running Greyhole without update-rc.d.

**Comment by astrom0** [comment]
@uSlackr thanks for the tip.

This piece of advice made better sense to me:
[](http://www.abhigupta.com/2010/06/how-to-auto-start-services-on-boot-in-centos-redhat/)
but you put me on the right track.

To be explicit for any other CentOS/Fedora noobs following in my footsteps, refer below for greyhole specific instructions.

So, using the guidance mentioned, when I apply [Mount Shares Locally](https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally) and at the 2nd command in Step 2 replace:
`$ sudo update-rc.d mount_shares_locally defaults`
with:
`sudo chkconfig --add mount_shares_locally`
Default run levels appear to be applied. Running this command:
`sudo chkconfig --list`
shows that the _mount_shares_locally_ script shares the same run levels as the _ _ script.

I then ran the [Mount Shares Locally](https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally) steps after applying the noted substitution and got to the end without further issue.

Cheers ;-)

**Comment by astrom0** [comment]
> gboudreau commented:
> You can simply run the third command, which uses  chkconfig to enable the script on startup. I'll update the instructions  do that no error is returned to users who are running Greyhole without  update-rc.d.
> 

Thanks for that Guillaume. Over to you to use my comments as you think appropriate.

**Comment by gboudreau** [comment]
Instructions updated
