### ISSUE TITLE
How To: ? - Mount Greyhole Landing Zone for LAN Access

### ISSUE THREAD

**Issue by astrom0** [gboudreau/Greyhole#182]
Apologies if I've missed the obvious - I might not be searching with the right key word or in the right place.

I did a rewind from a previous installation that I think was messed up. So, I went back and did a:
1. 	clean CentOS 7 install
2. 	applied the start up script provided at [Greyhole Install](https://www.greyhole.net/#install) 
3. 	then invoked [USAGE](https://raw.githubusercontent.com/gboudreau/Greyhole/master/USAGE)
4. 	[Mounted Shares Locally](https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally) - revised version

Just to be safe, I've rebooted and greyhole --logs is telling me its sleeping happily, i.e. _**Nothing to do... Sleeping**_, and I can see my landing zone (in my case **_ghLZ_** ) at /mnt/samba:
`$ ls -la /mnt/samba`

> total 16
> drwxr-xr-x. 4 root root 4096 Jul 24 16:16 .
> drwxr-xr-x. 8 root root 4096 Jul 24 16:09 ..
> drwxr-xr-x. 2 root root 4096 Jul 24 16:16 ghLZ
> drwxr-xr-x. 2 root root 4096 Jul 24 16:16 print$

I'm seeing this response to 
`$ testparm`

> Load smb config files from /etc/samba/smb.conf
> rlimit_max: increasing rlimit_max (1024) to minimum Windows limit (16384)
> Processing section "[homes]"
> Processing section "[printers]"
> Processing section "[print$]"
> Processing section "[ghLZ]"
> Loaded services file OK.
> Server role: ROLE_STANDALONE
> 

I'm dropping in my /etc/samba/smb.conf file to show what I've set up there.
[smb.conf.txt](https://github.com/gboudreau/Greyhole/files/1169145/smb.conf.txt)
And my .smb_credentials file is plain vanilla.

Where's the info on how to mount shares across the LAN as opposed to locally to the server? Or is [MountSharesLocally](https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally) meant to deal with this? If I use Windows 10 or an Ubuntu VM (that both happily see each other with minimal fuss), Greyhole doesn't appear to show up as a LAN network folder / directory.

Do I need to apply modifications like this?
[https://wiki.centos.org/HowTos/SetUpSamba](https://wiki.centos.org/HowTos/SetUpSamba)
Where I need to edit iptables, set TCP/UDP ports and do other messing about.
Or is there a Greyhole specific recommended plan?

And if I've missed something basic, where to look to provide more info to help or run a diagnostic?

Hopefully this is a case of, "so close, almost there".
Thanks in advance.

**Comment by gboudreau** [comment]
Nothing special to do to connect to the Samba shares remotely.
Whatever tutorial you can find that explains how to connect to a Samba share from another computer will do the trick.

It shouldn't be complicated... Did you try to enter `\\LAN_ip_of_greyhole_server\` in the Windows Explorer address bar?
If that doesn't work, you might need to open ports for remote access on iptables, or whatever firewall is running by default.

**Comment by astrom0** [comment]
Thanks for the quick reply. Much appreciated because at least I don't have to wonder about what I might have overlooked. My Linux leaning is toward Ubuntu - seems to be a lot simpler than CentOS. No matter. I'll get there.

Regarding the question - Yes, I tried both the server name and the IP address but no joy.

**Comment by vzjrz** [comment]
Your samba config is supposed to be pointing to the greyhole landing zone. I think for your case you should change `path = /mnt/n5550a/shares/ghLZ` to `path = /mnt/samba/ghLZ` or to something else.

**Comment by gboudreau** [comment]
_[ Closing old support issues; you can re-open if needed. ]_
