### ISSUE TITLE
Greyhole VFS issue

### ISSUE THREAD

**Issue by tamorgen** [gboudreau/Greyhole#190]
I'm running Fedora 26 server with the Amahi distro on top of it, which runs amahi-greyhole.service.  I'm not sure how divergent this is form the vanilla greyhole install, but it's causing me an issue.  The amahi-greyhole.service is as up to date as it'll get. (dnf update amahi-greyhole does nothing).

I installed netatalk so I can run Time Machine backups for my Macs, and netatalk updates Samaba to version 4.6.11.

I've tried updating greyhole, both on it's own and the amahi distro:

```
[root@galactica greyhole]# dnf update greyhole
Last metadata expiration check: 0:10:17 ago on Wed 27 Dec 2017 10:22:43 AM EST.
Package greyhole available, but not installed.
No match for argument: greyhole
Error: No packages marked for upgrade.

[root@galactica greyhole]# dnf update amahi-greyhole
Last metadata expiration check: 0:10:26 ago on Wed 27 Dec 2017 10:22:43 AM EST.
Dependencies resolved.
Nothing to do.
Complete!

[root@galactica greyhole]# dnf install greyhole
Last metadata expiration check: 0:10:44 ago on Wed 27 Dec 2017 10:22:43 AM EST.
Package amahi-greyhole-0.10.14-1.x86_64 is already installed, skipping.

Dependencies resolved.
Nothing to do.
Complete!
[root@galactica greyhole]#
```

All the symlinks are showing up as missing (red text for file, red background/white text for symlink)

```
[root@galactica greyhole]# ls -l /usr/lib*/samba/vfs/greyhole.so
lrwxrwxrwx 1 root root 39 Dec 27 04:12 /usr/lib64/samba/vfs/greyhole.so -> /usr/lib64/greyhole/greyhole-samba46.so

[root@galactica greyhole]# pwd
/usr/lib64/greyhole
[root@galactica greyhole]# ls -al
total 324
drwxr-xr-x 2 root root 4096 Dec 27 05:02 .
dr-xr-xr-x. 93 root root 98304 Dec 27 10:01 ..
-rw-r--r-- 1 root root 40126 Jun 21 2017 greyhole-samba40.so
-rw-r--r-- 1 root root 40594 Jun 21 2017 greyhole-samba41.so
-rw-r--r-- 1 root root 44306 Jun 21 2017 greyhole-samba43.so
-rw-r--r-- 1 root root 44106 Jun 21 2017 greyhole-samba44.so
-rw-r--r-- 1 root root 53056 Jun 27 2017 greyhole-samba45.so
lrwxrwxrwx 1 root root 39 Dec 27 05:02 greyhole-samba46.so -> /usr/lib64/greyhole/greyhole-samba46.so
```

I'm a bit unclear on how to fetch a new greyhole-samba46.so.  Can anyone assist?

**Comment by gboudreau** [comment]
Try:
```
rm /usr/lib64/greyhole/greyhole-samba46.so
curl -o /usr/lib64/greyhole/greyhole-samba46.so https://github.com/gboudreau/Greyhole/raw/master/samba-module/bin/4.6/greyhole-x86_64.so
```

**Comment by tamorgen** [comment]
Hi Guillaume,
Well, this did fix the symlink, however, my shares are still inaccessible remotely.  I was hoping the symlink would fix the problem.  Any suggestions?

**Comment by tamorgen** [comment]
it looks like the problem is with smb.  It’s pretty much the same problem you answered in the wiki.

https://github.com/gboudreau/Greyhole/wiki/Inaccessible-Greyhole-Shares <https://github.com/gboudreau/Greyhole/wiki/Inaccessible-Greyhole-Shares>

I do not have AppArmor installed, so it appears to be a problem between Greyhole and Samba.

[tmorgenthaler@galactica bluray]$ systemctl status smb
● smb.service - Samba SMB Daemon
   Loaded: loaded (/usr/lib/systemd/system/smb.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-12-27 16:33:19 EST; 27min ago
 Main PID: 1333 (smbd)
   Status: "smbd: ready to serve connections..."
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/smb.service
           ├─1333 /usr/sbin/smbd
           ├─1342 /usr/sbin/smbd
           ├─1343 /usr/sbin/smbd
           └─1578 /usr/sbin/smbd

Dec 27 16:58:40 galactica smbd[8586]: [2017/12/27 16:58:40.808040,  0] ../source3/smbd/service.c:604(make_connection_snum)
Dec 27 16:58:40 galactica smbd[8586]:   vfs_init failed for service Bluray
Dec 27 16:58:40 galactica smbd[8586]: [2017/12/27 16:58:40.898692,  0] ../lib/util/modules.c:48(load_module)
Dec 27 16:58:40 galactica smbd[8586]:   Error loading module '/usr/lib64/samba/vfs/greyhole.so': /usr/lib64/samba/vfs/greyhole.so: invalid ELF header
Dec 27 16:58:40 galactica smbd[8586]: [2017/12/27 16:58:40.898715,  0] ../source3/smbd/vfs.c:184(vfs_init_custom)
Dec 27 16:58:40 galactica smbd[8586]:   error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
Dec 27 16:58:40 galactica smbd[8586]: [2017/12/27 16:58:40.898731,  0] ../source3/smbd/vfs.c:379(smbd_vfs_init)
Dec 27 16:58:40 galactica smbd[8586]:   smbd_vfs_init: vfs_init_custom failed for greyhole
Dec 27 16:58:40 galactica smbd[8586]: [2017/12/27 16:58:40.898740,  0] ../source3/smbd/service.c:604(make_connection_snum)
Dec 27 16:58:40 galactica smbd[8586]:   vfs_init failed for service Bluray
[tmorgenthaler@galactica bluray]$ ls -l /usr/lib*/samba/vfs/greyhole.so
lrwxrwxrwx 1 root root 39 Dec 27 11:19 /usr/lib64/samba/vfs/greyhole.so -> /usr/lib64/greyhole/greyhole-samba46.so
[tmorgenthaler@galactica bluray]$ smbd --version
Version 4.6.11
[tmorgenthaler@galactica bluray]$ 



Any suggestions would be appreciated.  Please let me know if you need additional logs or config files.

**Comment by gboudreau** [comment]
```
Error loading module '/usr/lib64/samba/vfs/greyhole.so': /usr/lib64/samba/vfs/greyhole.so: invalid ELF header
```

`invalid ELF header` seems to indicate a problem with the binary.
And indeed, if you would `vi` that file, you'd see HTML! :)

```
curl -Lo /usr/lib64/greyhole/greyhole-samba46.so https://github.com/gboudreau/Greyhole/raw/master/samba-module/bin/4.6/greyhole-x86_64.so
```

Damn `curl` not following redirects by default!

**Comment by tamorgen** [comment]
Thank you, that solved my issue!
