### ISSUE TITLE
Empty folders are deleted from the LZ but not from the pools

### ISSUE THREAD

**Issue by ghrasko** [gboudreau/Greyhole#191]
Hi,

I have an issue the is either related to this one or not: https://github.com/gboudreau/Greyhole/issues/186

Enviroment is fresh Amahi 10 implementation:

```
uname -a
Linux nas.home.hu 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/fedora-release
Fedora release 25 (Twenty Five)
rpm -q samba amahi-greyhole
samba-4.5.14-0.fc25.x86_64
amahi-greyhole-0.10.14-1.x86_64
```
I just installed Fedora 25 with Amahi 10. From the Amahi Dashboard I installed the Greyhole UI and I am experiencing a similar problem. Earlier I used Greyhole UI with Amahi 8/Fedora 21 without problems.

Sometimes odd filenames appear when I create an empty dirextory in Samba shares (mkdir routines in Greyhole). If I copy a folder with files from my Windows PC to the shared folder (Greyhole ZL), the directory is created correctly as it is not using the mkdir routins this case. However for my installation if I delete a folder with the LZ, the empty folders are not deleted from the Greyhole pool(s). This is not obvious for a normal Samba user as the shared directory is fine. But if you check the pool drive, the empty folders are there for ever.

I also checked the Samba and Greyhole codes and realized that the mkdir and rmdir event routiness parameter had been changed and my assumption was that there is something uninitialized structure field was retrieved. However my other guess was also some encoding issue.

The description with logs and spool files can be seen here. I don't know if this is the same issue or another one:

https://forums.amahi.org/viewtopic.php?f=4&t=7077

Gábor

**Comment by ghrasko** [comment]
The following test cases are copied from the [Amahi forum](https://forums.amahi.org/viewtopic.php?f=4&t=7077&p=40200). I tested it with a single and with two storage pools as well. The serious consequence of the problem is that the empty folders (having either garbage or correct name) are not deleted from the storage pools, but they are deleted from the LZ. The log and spool files are not signing any errors except that they show the garbage names. But the problem occures also when the folder names are correct. In that case nothing refers to the problem, only the remaining folders in the pool directories.

# Scenario 1

Copy test1-folder with files test1a.txt and test1b.txt to Samba shared testuser directory via Windows 10 file Explorer. Copy is successful and also checked on the HDA terminal. In the landing zone it is absolutelly OK, in the drive pools an extra empty directory appears with a strange name.

Greyhole log:

```
Mar 17 15:04:08 INFO write: Now working on task ID 36: write testuser/test1-folder/test1a.txt
Mar 17 15:04:08 INFO write: File created: testuser/test1-folder/test1a.txt
Mar 17 15:04:08 INFO write: Now working on task ID 37: write testuser/test1-folder/test1b.txt
Mar 17 15:04:08 INFO write: File created: testuser/test1-folder/test1b.txt
```

In the pools (the two pools look identical):

```
[root@nas testuser]# pwd
/var/hda/files/drives/drive2/gh/testuser
[root@nas testuser]# ls -lRh
.:
total 8.0K
drwxrwxrwx 2 root root 4.0K Mar 17 15:04 ''$'\240\234\215''C(V'
drwxrwxr-x 2 testuser users 4.0K Mar 17 15:04 test1-folder

'./'$'\240\234\215''C(V':

./test1-folder:
total 8.0K
-rwxrw-r-- 1 testuser users 1.1K Mar 17 13:05 test1a.txt
-rwxrw-r-- 1 testuser users 1.1K Mar 17 13:05 test1b.txt
total 0
```

# Scenario 2

Delete the test1-folder with the two text files via Windows 10 file Explorer. The shared folder becomes empty and that is also reflected by checking in the terminal. However in the pools only the files are deleted and not the directory. Again the two pools look identical.

Greyhole log:

```
Mar 17 15:14:09 INFO unlink: Now working on task ID 38: unlink testuser/test1-folder/test1a.txt
Mar 17 15:14:09 INFO unlink: File deleted: /var/hda/files/testuser/test1-folder/test1a.txt
Mar 17 15:14:09 INFO unlink: Now working on task ID 39: unlink testuser/test1-folder/test1b.txt
Mar 17 15:14:09 INFO unlink: File deleted: /var/hda/files/testuser/test1-folder/test1b.txt
Mar 17 15:14:09 INFO rmdir: Now working on task ID 40: rmdir testuser/N�C(V
Mar 17 15:14:09 INFO rmdir: Directory deleted: /var/hda/files/testuser/N�C(V
```

In the pools (the two pools look identical):

```
[root@nas testuser]# ls -lRh
.:
total 8.0K
drwxrwxrwx 2 root root 4.0K Mar 17 15:04 ''$'\240\234\215''C(V'
drwxrwxr-x 2 testuser users 4.0K Mar 17 15:14 test1-folder

'./'$'\240\234\215''C(V':
total 0

./test1-folder:
total 0
total 0
```

During the tests I patiently waited for the automatic processes (every 10 minutes) and had not forced with FSCK. I later scheduled FSCK and when ran, it gave these log lines:

```
Mar 17 16:24:10 INFO fsck_file: Now working on task ID 52: fsck_file testuser/test2-folder/test2b.txt
Mar 17 16:24:10 WARN fsck_file: WARNING! No copies of this file are available in the Greyhole storage pool: "testuser/test2-folder/test2b.txt". 
Mar 17 16:24:10 INFO fsck_file: Now working on task ID 53: fsck_file testuser/test2-folder/test2a.txt
Mar 17 16:24:10 WARN fsck_file: WARNING! No copies of this file are available in the Greyhole storage pool: "testuser/test2-folder/test2a.txt". 
```

If I repeate the test with another folder name and folders, the result is the same. Another strangely named empty directory is created in the pools together with the correct directory with the files. After deleting only the files are deleted. The file's folder and the strange folder remains there. Thus more and more garbage directories remain in the LZ folders. They don't disappear after FSCK or trash deletion. 

# Scenario 3

I create an emty folder on my Windows 10 desktop named as test2folder. Then I drag (move) it to the testuser shared folder.

FIles generated in /var/spool/greyhole directory:

```
[root@nas greyhole]# ls -ls
total 36
4 -rw-rw-rw- 1 testuser users 19 Mar 18 08:57 1521359829398448
4 -rw-rw-rw- 1 testuser users 19 Mar 18 08:57 1521359829502594
4 -rw-rw-rw- 1 testuser users 18 Mar 18 08:57 1521359829522859
4 -rw-rw-rw- 1 testuser users 19 Mar 18 08:57 1521359829582545
4 -rw-rw-rw- 1 testuser users 23 Mar 18 08:57 1521359829596210
4 -rw-rw-rw- 1 testuser users 18 Mar 18 08:57 1521359829602795
4 -rw-rw-rw- 1 testuser users 18 Mar 18 08:57 1521359829636247
4 -rw-rw-rw- 1 testuser users 18 Mar 18 08:57 1521359829645450
4 -rw-rw-rw- 1 testuser users 19 Mar 18 08:57 1521359829722163
0 drwxrwxrwt 2 root root 40 Mar 18 07:56 mem
```

The content of the files are as follows. See the one with mkdir markd with red:

```
[root@nas greyhole]# cat 1*
close
testuser
38

close
testuser
38

close
testuser
9

close
testuser
35

mkdir
testuser
▒J▒U

close
testuser
9

close
testuser
9

close
testuser
9

close
testuser
35
```

# Scenario 4

In similar way I move in a folder test5folder but now it contains a text file test5.txt. The spool file items are correct:

```
open
testuser
test5folder/test5.txt
9
for writing
close
testuser
9
```

# Scenario 5

When deleting that folder (that contains the file), the file within the folder is deleted correctly, but not the folder itself:

```
close
testuser
37

close
testuser
37

close
testuser
37

close
testuser
9

close
testuser
9

unlink
testuser
test5folder/test5.txt

rmdir
testuser
`▒U

close
testuser
9
```

The corresponding Greyhole database task records:

```
id,action,share,full_path,additional_info,complete,event_date
12,write,testuser,test4folder/test4.txt,,yes,2018-03-18 09:06:30
13,unlink,testuser,test4folder/test4.txt,,yes,2018-03-18 09:16:31
14,rmdir,testuser, `ìU,,yes,2018-03-18 09:16:31
```

**Comment by gboudreau** [comment]
Your problem is this: `amahi-greyhole-0.10.14-1` + `samba-4.5.14-0`.
Ref: https://github.com/gboudreau/Greyhole/releases/tag/0.10.15
