### ISSUE TITLE
tail: cannot open '/var/log/greyhole.log​' for reading: No such file or directory

### ISSUE THREAD

**Issue by ronkmd** [gboudreau/Greyhole#194]
After having used Greyhole on Amahi for a while, I've migrated over to Ubuntu 18.04 and am trying to get Greyhole up and running. Unfortunately, I didn't save my smb.conf, greyhole.conf and fstab, so I kind of had to start from scratch. 
I ended up getting a lot of empty folders with oddly/invalid encoded names  as in https://github.com/gboudreau/Greyhole/issues/186

Somehow, in trying to sort this out, I've encountered a situation where if I try to "tail" the greyhole.log i get the error "tail: cannot open '/var/log/greyhole.log​' for reading: No such file or directory". I can open this (1.1 GB!) file in a text editor and see it in Nautilus and with an ls command in Terminal. I fI try to remove the file I get another tail: cannot open "No such file or directory" error. Any thoughts?

**Comment by uSlackr** [comment]
Why would tail report an error if you are trying to rm a file?  You could try to rename the file `mv /var/log/greyhole.log /var/log/greyhole_old.log`

\\Greg

________________________________

**Comment by ronkmd** [comment]
Restored a prior Ubuntu image from when things seemed ok. Closing topic.
