### ISSUE TITLE
Ubuntu 16.04 no symlink masking in CIFS-Utils? 

### ISSUE THREAD

**Issue by Burden50** [gboudreau/Greyhole#197]
I am setting up a new ubuntu 16.04 install of greyhole and everything is working correctly but in ubuntu  14.04 my CIFS mounted local shares had masked symlinks like this...

```
root@HOST1:/mnt/samba/TV# ls -la
total 5
drwxrwxrwx+ 2 administrator root    0 Aug  9 02:09 .
drwxr-xr-x  8 root          root 4096 Aug  8 04:43 ..
-rwxr-xr-x 1 administrator root     0 Aug  8 03:57 test123.txt
```

In Ubuntu 16.04 the symlink path is exposed.
```
root@HOST2:/mnt/samba/TV# ls -la
total 5
drwxrwxrwx+ 2 administrator root    0 Aug  9 02:09 .
drwxr-xr-x  8 root          root 4096 Aug  8 04:43 ..
lrwxrwxrwx  1 administrator root   26 Aug  9 02:09 test123.txt -> /mnt/a1/d2/TV/test123.txt
```

Is there a way to get the masked symlinks in 16.04 I think it is causing rsync to treat the symlinks as new files and try to recopy.

**Comment by gboudreau** [comment]
I would guess you are missing those lines in your smb.conf:
https://github.com/gboudreau/Greyhole/blob/master/USAGE#L24-L25

**Comment by Burden50** [comment]
When I set unix `extensions = no` on ubuntu 16.04 i can't `ls` the directory
