### ISSUE TITLE
Request for an option for detecting and fixing bitrot/ silent errors 

### ISSUE THREAD

**Issue by j4nl** [gboudreau/Greyhole#199]
Occasionally, harddisks experience what is called silent errors or bitrot, where bits flip without detection, corrupting a file. This can be caused by a number of things, from minor disk surface defects to the earth's background radiation.  However bitrot can be detected and corrected.  

If a hash is generated for each file written to disk, it is possible to detect bitrot, if, when a file is later read and a new hash is calculated, it does not match the original hash.  Moreover if two or more copies are kept, it is possible to correct the bitrot by verifying the other copies against their stored hashes and use a good copy to restore the corrupted file. This will maintain the long-term integrity of storage - ideally indefinitely.

It would therefore be an extremely cool and useful addition to Greyhole if:

1) Greyhole can calculate and store hashes of the files written to disk, enabling either an on-the-fly file corruption detection (when the file is later read) or can do a periodic scan for errors.
2) When having num_copies in /etc/greyhole.conf set to more than one, have an ability to either manually (i.e. once a week or month) or automatically (when the file is read) scan for and correct silent errors.

There is already bitrot code on github that could possible be reused/repurposed here: https://github.com/ambv/bitrot

**Comment by j4nl** [comment]
A bitrot feature would help with this problem, btw: 
https://www.pommepause.com/2016/02/the-case-of-the-dying-hard-drive-that-flipped-bits/

**Comment by gboudreau** [comment]
FYI, starting a few versions ago (since 0.11.0), Greyhole is now calculating new/changed files MD5 hash, while copying them to storage pool drives, and is storing those hash in the greyhole database.
It is not yet doing anything with those, but it should be simple enough to read those, and compare them to the calculated MD5 of all files, during a fsck using `--checksums`.

**Comment by old-square-eyes** [comment]
I just noticed a lot of my files are 0kb. I'm pretty upset. I found this. Not sure if it's the cause or some race condition somewhere using backup software to SAMBA shares in relation to removing locked files before they could be written. In any case @gboudreau, I ran a fsck with checksum and don't have email configured. I can't see the report in /usr/share/greyhole/ as suggested [here](https://serverfault.com/a/388416/170360). Any ideas where I find the report?

**Comment by old-square-eyes** [comment]
What's the best way to run a scan to see if there are good copies of the zero kb files (without actually browsing through the /gh directories file by file?

**Comment by gboudreau** [comment]
@old-square-eyes Please open a new Github issue; I will reply to both questions there. Thank you.

**Comment by gboudreau** [comment]
@old-square-eyes I opened a new issue for this: #231
Use the Subscribe button on the right of the issue to receive notifications when I add comments in that issue.

**Comment by gboudreau** [comment]
Auto-fixing invalid file copies (per stored checksums) has been implemented in v0.13 (to be released). It needs to be scheduled manually; I added a note about this at the bottom of the USAGE file.
