### ISSUE TITLE
setup greyhole on centos 7

### ISSUE THREAD

**Issue by richardlrzjw** [gboudreau/Greyhole#201]
Hello  I have followed the installation instruction to setup greyhole on my fresh installed centos 7 by using script posted on http://bit.ly/greyhole-package, I installed mysql by following https://www.hostinger.com/tutorials/how-to-install-mysql-on-centos-7#gref; everything seems okay except greyhole failed to start.
here is the information collected. http://ix.io/1x14

**Comment by richardlrzjw** [comment]
Thanks for feedback, I have reinstall the greyhole by following https://raw.githubusercontent.com/gboudreau/Greyhole/master/INSTALL and finally get it running but I don't see it working, I have checked log file:it says:
Dec 29 23:46:57 INFO daemon: Greyhole (version 0.10.17) daemon started.
Dec 29 23:46:57 INFO daemon: Optimizing MySQL tables...
Dec 29 23:46:57 DEBUG daemon: Loading metadata store backup directories...
Dec 29 23:46:57 DEBUG daemon:   Found 2 directories in the settings table.
Dec 29 23:46:57 DEBUG daemon: Checking symlink at /usr/lib64/samba/vfs/greyhole.so...
Dec 29 23:46:57 WARN daemon:   Greyhole VFS module for Samba was missing, or the wrong version for your Samba. It will now be replaced with a symlink to /usr/lib64/greyhole/greyhole-samba48.so
Dec 29 23:46:57 WARN daemon: PHP Warning [2]: symlink(): No such file or directory in /usr/bin/greyhole on line 1760; BT: greyhole[L3635] run() => greyhole[L3601] initialize() => greyhole[L3624] samba_check_vfs() => greyhole[L4983] gh_symlink(/usr/lib64/greyhole/greyhole-samba48.so,/usr/lib64/samba/vfs/greyhole.so) => greyhole[L1760] symlink(/usr/lib64/greyhole/greyhole-samba48.so,/usr/lib64/samba/vfs/greyhole.so)
Dec 29 23:46:57 INFO daemon: The Samba daemon will now restart...
Dec 29 23:46:57 DEBUG sleep: Nothing to do... Sleeping.
Dec 29 23:47:07 DEBUG sleep: Nothing to do... Sleeping.

in the /etc/samba/smb.conf share portion, I have added following by following usage:
#        dfree command = /usr/bin/greyhole-dfree
        vfs objects = greyhole
I am not able to access share from client machine and if I remove the # to get those two lines it does not work also so.  P.S. I have checked my samba version it is 4.8  I lost my idea, any help is appreciated.

**Comment by richardlrzjw** [comment]
also while I follow https://raw.githubusercontent.com/gboudreau/Greyhole/master/INSTALL, section 3 is for samba >4.9 so I did not do any thing for section 3, am I correct or not?

Thanks

**Comment by gboudreau** [comment]
INSTALL is an alternative to the RPM/DEB packages, in case the OS you use can't install those; in your case, you should use the RPM, not install manually (that will prevent you from receiving any updates, amongst other things).
You can easily re-install the RPM at this point, and it should work. Just keep your /etc/greyhole.conf as it is right now.
