### ISSUE TITLE
Files in GH folders have wrong permissions after processing

### ISSUE THREAD

**Issue by brian11337** [gboudreau/Greyhole#202]
Hello. I recently upgraded from Amahi 10 to Amahi 11 and moved my existing storage drives to my new system. All my existing Greyhole shares moved and seem to work fine. My problem is with anything new that I save, after it's processed by greyhole it has permissions of 0764. This makes it not visible but no accessible to other users. It seems that all of my previous files were saved with permission of 0775. The ownership for files and folders saves correctly, but not the permissions. Am i missing something simple?

Thanks,
Brian

**Comment by gboudreau** [comment]
With linux extensions off (a requirement for Greyhole, in smb.conf), the permissions of new files is defined by the shares config from smb.conf

```
$ sudo testparm
[...]
[Books]
	comment = Books
	path = /mnt/hdd2/shares/Books
	dfree command = /usr/bin/greyhole-dfree
	create mask = 0775
	directory mask = 0775
	force create mode = 0664
	force directory mode = 0775
	read only = No
	vfs objects = greyhole
```

**Comment by brian11337** [comment]
Here is the output from the command you asked for:
[http://ix.io/1yaL](url)

And here are the results of the two ls -l commands:
```
[root@hda Docs]# ls -ld test
drwxrwxr-x 2 brian users 4096 Jan 12 20:56 test
```
```
[root@hda test]# ls -l
total 0
-rwxrw-r-- 1 brian users 0 Jan 12 20:50 test.doc
```

Thanks again for your help

**Comment by gboudreau** [comment]
In what folder were you, when you executed the `ls` commands?

**Comment by brian11337** [comment]
I created the "test" directory in the "Docs" folder. So the first ls was executed in the Docs folder, the second one was executed in the "test" directory. The name of the empty file I created was "test.doc"

**Comment by gboudreau** [comment]
I mean, were you connected to the Amahi server, or on a client computer?
If on the Amahi server, in what (absolute) folder were you?
`/mnt/samba/Docs` ? `/var/hda/files/Docs` ? `/var/hda/files/drives/drive#/gh/Docs/` ?

**Comment by brian11337** [comment]
Sorry, misunderstood what you wanted. SSH'd in from my desktop and was in
`/var/hda/files/drives/drive5/gh/Docs/`
`/var/hda/files/drives/drive5/gh/Docs/test/`

**Comment by gboudreau** [comment]
Try:
```
ls -la /mnt/samba/Docs/test/
ls -la /var/hda/files/docs/test/
ls -la /var/hda/files/drives/drive*/gh/Docs/test/
```

**Comment by brian11337** [comment]
```
[root@hda test]# ls -la /mnt/samba/Docs/test/
total 0
drwxrwx--- 2 brian users 0 Jan 12 20:56 .
drwxrwx--- 2 brian users 0 Jan 12 20:51 ..
-rw-rw---- 1 brian users 0 Jan 12 20:50 test.doc
```
```
[root@hda test]# ls -la /var/hda/files/docs/test/
total 4
drwxrwxr-x  2 brian users   22 Jan 12 20:56 .
drwxrwxrwx 29 brian users 4096 Jan 12 20:51 ..
lrwxrwxrwx  1 root  root    50 Jan 12 20:56 test.doc -> /var/hda/files/drives/drive5/gh/Docs/test/test.doc
```
```
[root@hda test]# ls -la /var/hda/files/drives/drive*/gh/Docs/test/
/var/hda/files/drives/drive2/gh/Docs/test/:
total 8
drwxrwxr-x   2 brian users 4096 Jan 12 20:56 .
drwxrwxrwx 157 brian users 4096 Jan 12 20:56 ..
-rwxrw-r--   1 brian users    0 Jan 12 20:50 test.doc

/var/hda/files/drives/drive3/gh/Docs/test/:
total 8
drwxrwxr-x  2 brian users 4096 Jan 12 20:56 .
drwxrwxrwx 29 brian users 4096 Jan 12 20:56 ..
-rwxrw-r--  1 brian users    0 Jan 12 20:50 test.doc

/var/hda/files/drives/drive5/gh/Docs/test/:
total 8
drwxrwxr-x  2 brian users 4096 Jan 12 20:56 .
drwxrwxrwx 16 brian users 4096 Jan 12 20:56 ..
-rwxrw-r--  1 brian users    0 Jan 12 20:50 test.doc
```

**Comment by gboudreau** [comment]
That all looks fine.
The permissions of the files in `/var/hda/files/drives/` doesn't matter, as they should never be accessed directly. On the server, they should be accessed using `/mnt/samba/Share`, and the permission there is as expected (`660`, per the `mount_shares_locally` init script).

**Comment by brian11337** [comment]
If I try and access them as another user from a Windows PC using Samba, I can't open the files. I can see them, but it says I don't have permission to execute/open. If I change the permission of the files in `/var/hda/files/drives/` to 0775 then I can (since the Docs folder is readable/writeable by all in Samba). 
On my old server it always saved them as 0775, now they are being saved as 0764.

**Comment by gboudreau** [comment]
The permissions they end with in `/var/hda/files/drives/*` is based on the permissions they had before Greyhole processed them.
i.e. try to stop the Greyhole daemon, create a file on a share, and check the file permissions in `/var/hda/files/Share`, then restart the Greyhole daemon, let it process that file, and compare with the permissions of the files that end up in `/var/hda/files/drives/*`; they should be the same.

So that means your file was initially created as 764, which seems in line with the smb.conf options you use: `force create mode = 0664` (force mode is the _minimum_ for newly-created files; eg. if you try to create a file with permissions 000, the file will end up being 664; if you try to create a file with permissions 700, the file will end up being 764, etc.)

If you want the files to end up as 775, you need to change your `smb.conf` to `force create mode = 0775`.

**Comment by brian11337** [comment]
Hmm, I see. So I compared the `smb.conf` files from my old HDA, and it's identical. I'm at a loss for why they are different, but I do know that anything I save from my Win machine isn't accessible from another Win PC logged into samba as a different user (even though, almost all my directories should be). And also, the permissions on new files aren't saved the same as my old HDA saved them. So anytime I need to execute a file from another user, I need to execute `chmod 775 -R /var/hda/files/drives/`

**Comment by brian11337** [comment]
But, it does work exactly as you said, the new file is created with a 764, so I'm guessing my issue is with samba and not greyhole? Do you agree?

**Comment by gboudreau** [comment]
Yes. Changing `force create mode = 0775` in your smb.conf will do what you want.
