### ISSUE TITLE
PHP Fatal error on fsck

### ISSUE THREAD

**Issue by vonj** [gboudreau/Greyhole#203]
Whenever I run greyhole --fsck or -q I get this crash:

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /usr/bin/greyhole on line 613
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /usr/bin/greyhole on line 1905

I am on Ubuntu 16.04, with nothing special in it. It used to work, but it doesn't anymore.
I tried compiling the latest PHP 7 and tested with that, almost same error, except it doesn't complain about line 1905 anymore, only 613:

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /usr/bin/greyhole on line 613

**Comment by gboudreau** [comment]
Try to run a fsck, wait for the crash, then do this: 
https://github.com/gboudreau/Greyhole/wiki/GetHelp#gather-system-information
Reply with the link it gives you.

**Comment by vonj** [comment]
Crash is immediate. I will run command as soon as I get home.

**Comment by vonj** [comment]
http://ix.io/1yHr

**Comment by gboudreau** [comment]
Greyhole log shows:
```
SQLSTATE[HY000]: General error: 144 Table './greyhole/tasks' is marked as crashed and last (automatic?) repair failed. Will now try to repair the MySQL tables.
```

Try to connect to MySQL using the root user, and repair the `tasks` table manually.

**Comment by vonj** [comment]
I looked at that file and I realised the same. It works now, thanks a lot!  It was such a long time I set up Greyhole I had even forgotten it uses mysql behind the scenes. :-D

**Comment by gboudreau** [comment]
I fixed the infinite loop that caused the out of memory error you saw, when a table is crashed.
Thanks for your help debugging this.
