### ISSUE TITLE
Extra copy feature 'outside of pool'

### ISSUE THREAD

**Issue by Rastalovich** [gboudreau/Greyhole#210]
Thought I'd share a real life setup I have, due to a question asked of me - 'I know all our files are on the server, but what do I do if something happens to you?' 'what's ext4??'. etc.

At present, my extensive use of Greyhole has in the .conf:

num_copies[Myfiles]=2
num_copies[Herfiles]=2
.. which works as intended and is fine.

In addition to the Greyhole handling, I've also attached a USB drive to the server, formated deliberately exfat, and run an rsync on the locally mounted shares of the above. -- anything 'happens to me' she pulls the USB drive and therein are all the files. The server could crash and burn, but the USB will have a copy of everything (actually have 2x USB drives attached).

What would save time for me (and I honestly don't know if this is useful to anyone else), is if in-addition to specifying 'num_copies' above, I could specify:

additional_copy[Myfiles]=/mnt/UD00
.. in which a folder [Myfiles] would be created and kept inline with the pool's copy. Removing files as they're deleted and adding new ones as they join the pool.

Plus, if you added another line the same, but '/mnt/UD1' (another USB drive), a second USB drive would have a [Myfiles] folder created on it.

This of course comes with many loose ends, one of which being the pool may be 30Tb in size and the size of [Myfiles] share would have to be smaller than the USB (or /mnt used) - it could just error log it I suppose. The size of my [Myfiles] in my case is around 800g and the USB is 4Tb, so I'm ok.

**Comment by gboudreau** [comment]
Unless I misunderstand what you are trying to achieve, you can already do this.
What you need to do is create two groups of drives: the `NORMAL` group, and the `USB` group (choose group names that talk to you), for the share `Myfiles`:

Example config:

    storage_pool_drive = /mnt/hdd1/gh, min_free: 10gb
    storage_pool_drive = /mnt/hdd2/gh, min_free: 10gb
    storage_pool_drive = /mnt/hdd3/gh, min_free: 10gb
    ...
    storage_pool_drive = /mnt/UD0/gh,  min_free: 10gb

    num_copies[Myfiles] = 3

    drive_selection_groups[Myfiles] = NORMAL: /mnt/hdd1/gh, /mnt/hdd2/gh, /mnt/hdd3/gh
	                                  USB:    /mnt/UD0/gh

    drive_selection_algorithm[Myfiles] = forced (all USB, all NORMAL) most_available_space

So when you add a file in the `Myfiles` share, Greyhole will first create a copy on all drives from the `USB` group (you only have one drive in that group, but you could have any number), then it will create 2 other copies, because you asked for 3 copies.
If you later want another copy of all the `Myfiles` files on `/mnt/UD1`, add that drive in the `USB` group, and change the `num_copies[Myfiles] = 4`.

Other `drive_selection_algorithm` values you could use:

    forced (2xNORMAL, all USB) most_available_space

to have the copies on the `NORMAL` drives created first, before the copies on the USB drive(s).

**Comment by Rastalovich** [comment]
I see what you mean.

In my conf, I also have 5 other samba references, [Utlities], [Media], etc... which have num_copies=1, as I'm not bothered about losing them.

Would I have to add an algorithm line for them? My usual grouping for drives is merely New: xxx, Old: xxx, etc. and have it state what drives are fair game for that 1 copy?

**Comment by gboudreau** [comment]
You can define your USB drives in a new group defined by `drive_selection_groups`, and then use those groups in different `drive_selection_groups`, one global, and one per share that you want to use another config for. So if you want all shares except `Myfiles` to use a specific drives, define that using `drive_selection_groups`, then add another `drive_selection_groups[Myfiles]` that overrides the default, just for that share.

**Comment by Rastalovich** [comment]
I think I'm with you, I'll try some edits tomorrow.

In terms of the 5 other shares that only deserve 1 copy of their files, and of course I don't want them on the USB group drives, do I have to edit in a way to exclude the USB drives from main group, or will that lead me to making a long list of share groupings?

Once you name a group of drives, NEW: for example, are you able to use the term NEW from that point to reference the same drives? (that'd prevent having to name the mounts more than once)

**Comment by gboudreau** [comment]
You should not list the USB drives in the groups you user for all drives. Thus why in my example, I created a new group called `USB`. If you then only use that group in the `drive_selection_groups[Myfiles]` and NOT in `drive_selection_groups`, no files except the ones in `Myfiles` will go on your USB drives.

If the USB drives are not available for any reason, it will try to create a 3rd file copy on another drive, if possible, so you'd end up with 3 file copies on your normal drives.

```
storage_pool_drive = /mnt/hdd1/gh, min_free: 10gb
storage_pool_drive = /mnt/hdd2/gh, min_free: 10gb
storage_pool_drive = /mnt/hdd3/gh, min_free: 10gb
...
storage_pool_drive = /mnt/UD0/gh,  min_free: 10gb

num_copies[Media] = 1
num_copies[Myfiles] = 3

drive_selection_groups = OK:  /mnt/hdd1/gh, /mnt/hdd2/gh
                         NEW: /mnt/hdd3/gh
                         BROKEN: 

drive_selection_algorithm = forced (all OK, all NEW, all BROKEN) most_available_space

drive_selection_groups[Myfiles] = OK:  /mnt/hdd1/gh, /mnt/hdd2/gh
                                  NEW: /mnt/hdd3/gh
                                  BROKEN: 
                                  USB:    /mnt/UD0/gh

drive_selection_algorithm[Myfiles] = forced (all USB, all OK, all NEW, all BROKEN) most_available_space
```

You might not have to define the OK, NEW and BROKEN groups in `drive_selection_groups[Myfiles]`; not sure.

**Comment by gboudreau** [comment]
If fact, you might be able to define all the groups in `drive_selection_groups`, and use them in both `drive_selection_algorithm` and `drive_selection_algorithm[Myfiles]`:

```
drive_selection_groups = OK:  /mnt/hdd1/gh, /mnt/hdd2/gh
                         NEW: /mnt/hdd3/gh
                         BROKEN: 
                         USB:    /mnt/UD0/gh

drive_selection_algorithm = forced (all OK, all NEW, all BROKEN) most_available_space
drive_selection_algorithm[Myfiles] = forced (all USB, all OK, all NEW, all BROKEN) most_available_space
```

**Comment by Rastalovich** [comment]
I'll be implementing in the above fashion.

When a new file gets sent to one of the shares that wants 1 copy, do all the drives in the OK group get filled up (to the quota) until NEW drives become the next option? i.e. does most_available_space apply to single drives or groups of drives?

Lastly, what would happen if I were to issue a balance? Are the global groups ignored and all disks treated equally?

(Many thanks for your help btw.)

**Comment by gboudreau** [comment]
With the above configuration, for the Media share (`num_copies = 1`), the drive with the most available space from the OK group will be selected to receive all new files (or new copies of modified files). When all the OK drives are filled, then it would choose one of the NEW drives, etc.

A `greyhole --balance` will balance your drives, per the specified algorithm groups. It's a good way to move file after changing the `drive_selection_algorithm` and `drive_selection_groups` configs.

**Comment by Rastalovich** [comment]
I edited my conf thus:
`num_copies[Utilities] = 1
num_copies[Cinema] = 1
num_copies[Scratch] = 1
num_copies[HerStore] = 3
num_copies[MyStore] = 3
num_copies[GameStore] = 1`
`        storage_pool_drive = /mnt/PD00/gh, min_free: 30gb
        storage_pool_drive = /mnt/PD01/gh, min_free: 30gb
        storage_pool_drive = /mnt/PD02/gh, min_free: 30gb
      ...........
        storage_pool_drive = /mnt/UD01/gh, min_free: 30gb`
`drive_selection_groups= NEW: /mnt/PD00/gh, /mnt/PD09/gh, /mnt/PD11/gh
                        OK: /mnt/PD04/gh, /mnt/PD07/gh, /mnt/PD08/gh, /mnt/PD10/gh
                        OLD: /mnt/PD01/gh, /mnt/PD03/gh
                        LOWERR: /mnt/PD06/gh
                        HIERR: /mnt/PD02/gh, /mnt/PD05/gh
                        USB: /mnt/UD00/gh, /mnt/UD01/gh`
`        drive_selection_algorithm = forced (all NEW, all OK, all OLD, all LOWERR, all HIERR) most_available_space
        drive_selection_algorithm[MyStore] = forced (all USB, all NEW, all OK, all OLD, all LOWERR, all HIERR) most_available_space
        drive_selection_algorithm[HerStore] = forced (all USB, all NEW, all OK, all OLD, all LOWERR, all HIERR) most_available_space
`

.. restarted Gh and did an fsck to see what would happen. Something I forgot was I had a bunch of files on the root of UD00.. so although it's the same model 4Tb USB drive, it had 1Tb or so already used.
Result of the above was. [HerStore] was not put on UD00. Looking at the drive capacities under --stats:
`Storage Pool
                 Total -   Used =   Free +  Trash = Possible
  /mnt/PD00/gh:  3667G -  3460G =   207G +     0G =   207G
  /mnt/PD01/gh:  1834G -  1600G =   234G +     0G =   234G
  /mnt/PD02/gh:  1834G -  1598G =   235G +     0G =   235G
  /mnt/PD03/gh:  2751G -  2512G =   239G +     0G =   239G
  /mnt/PD04/gh:  2751G -  2540G =   211G +     0G =   211G
  /mnt/PD05/gh:  1834G -  1599G =   234G +     0G =   234G
  /mnt/PD06/gh:  3667G -  3456G =   211G +     0G =   211G
  /mnt/PD07/gh:  2751G -  2520G =   230G +     0G =   230G
  /mnt/PD08/gh:  1834G -  1593G =   241G +     0G =   241G
  /mnt/PD09/gh:  3667G -  3531G =   137G +     0G =   137G
  /mnt/PD10/gh:  1834G -  1592G =   241G +     0G =   241G
  /mnt/PD11/gh:  3667G -  3455G =   213G +     0G =   213G
  /mnt/UD00/gh:  3726G -  1107G =  2619G +     0G =  2619G
  /mnt/UD01/gh:  3726G -  1107G =  2619G +     0G =  2619G
                ==========================================
  Total:        39542G - 31670G =  7872G +     0G =  7872G`
So it effectively took the 'available space' of the drive in preference over making sure one of the 3 copies request went on the drive.
I assume if I remove the files I forgot were on the root of UD00, and ran a fsck again, it'd equalise itself. I didn't expect this outcome.

**Comment by Rastalovich** [comment]
Gh is fine. I believe I can see what's happening. Of course changing num_copies to 3, there are already 2 copies on the main pool. What I should have done is set all num_copies to 1, do an fsck, then add the USB to algorithm, and increase the num_copies after.
