### ISSUE TITLE
mysqld.service not found in Ubuntu 19.04

### ISSUE THREAD

**Issue by robojerk** [gboudreau/Greyhole#211]
Hello, I just upgraded to Ubuntu 19.04 and things were okay for a day, rebooted the machine this morning and am now getting this error.
`Failed to restart greyhole.service: Unit mysqld.service not found.`
There's a mysql.service but no mysqld.service

**Comment by robojerk** [comment]
I purged the old install and reinstalled.  Working now...

**Comment by gboudreau** [comment]
Thanks for the update.
I think the dpkg install script checks to see if mysqld or mysql is available, and will use the proper requirement for the greyhole service based on that. So force re-installing the dpkg should resolve this.
