### ISSUE TITLE
Ubuntu 19.10 -  libgenrand-samba4.so not found

### ISSUE THREAD

**Issue by johnruck** [gboudreau/Greyhole#212]
Well, I made the mistake of trying to setup Greyhole on a > 18.04 ubuntu system, and this time I am determined to try to hack it together to make it work.  Using greyhole release 0.10.24 and as best as I can following the instructions in https://github.com/gboudreau/Greyhole/blob/master/INSTALL (had to install php-7.3* instead of php5-* to get working packages, According to the script I am using samba 4.10, so I have copied that version into the right directory 

root@halo3:/usr/lib/x86_64-linux-gnu/samba/vfs# cp /root/greyhole/greyhole-0.10.24/samba-module/bin/4.10/greyhole-x86_64.so greyhole.so

My problem now is that whenever I try to access a greyhole share, I get the following in the samba log file - 

[2019/11/08 18:33:42.586455,  0] ../../lib/util/modules.c:49(load_module)
  Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so': libgenrand-samba4.so: cannot open shared object file: No such file or directory

For the life of me I cant find any packages that seem to contain this libgenrand-samba4.so library.  I have even installed the samba-devs package in hope that it would work.

For what it is worth, this is the apt-get install line I used 

apt-get -y install mysql-server php7.3-cli php7.3-mysql php7.3-mysqlnd php7.3-intl samba samba-common samba-common-bin php-pear rsync lsof sysstat.

Any suggestions or is this another case of wipe the machine and install pure 18.04 again ?

**Comment by gboudreau** [comment]
Maybe try `sudo /usr/share/greyhole/build_vfs.sh`
That will build the VFS module on your server, and thus ensure you have all the libraries you need on there.

**Comment by gboudreau** [comment]
Also, I think you can create a symlink to resolve the issue with this particular library:

    ln -s /usr/lib/x86_64-linux-gnu/samba/libgenrand.so.0 /usr/lib/x86_64-linux-gnu/samba/libgenrand-samba4.so

**Comment by johnruck** [comment]
Nice thought, but even with creating the symlink at that level and in the same directory with the greyhole.so it still says it cant find it - would it report if something it needs isnt available ? (I dont know how many levels of dependencies ubuntu will report as missing).

**Comment by gboudreau** [comment]
Maybe you don't have the `samba-libs` package installed?

`ldd /usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so`
will list all shared libraries it needs, and if it can't find any of them, it will show `not found`; otherwise, it will show the full path to the .so

On my Debian system, I get this about `libgenrand` (i.e. no need for a symlink; it finds the `libgenrand.so.0` file and that's enough):
```
$ ldd /usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so | grep 'libgenrand'
	libgenrand.so.0 => /usr/lib/x86_64-linux-gnu/samba/libgenrand.so.0 (0x00007fd7b63be000)
```

**Comment by johnruck** [comment]
Ok, tried the rebuild, in looking in the log file it generates it hit a snafu 

['/usr/bin/python3', '-c', "from distutils.sysconfig import get_config_var, get_python_lib\n\nprint(repr(get_python_lib(standard_lib=0, prefix='/usr/local/samba') or ''))"]
err: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils.sysconfig'

what do I need to do to force a re-run (when I run that command a second time it just starts with the samba build which fails because of this error).

**Comment by johnruck** [comment]
well, doing a rm -rf on the vfs_build directory got it to restart (when all else fails brute force it :) )  Once I installed the python3-distutils package it was able to complete the install and I can now at least connect to the shares, so yea :) .  Thanks for your insight on this.  I guess that that build_vfs command is the easy way to do that install script nowadays.
