### ISSUE TITLE
I broke it..

### ISSUE THREAD

**Issue by robojerk** [gboudreau/Greyhole#213]
I upgraded to Eoan, things were misbehaving and I noticed the `dfree command = /usr/bin/greyhole-dfree vfs objects = greyholeobjects` in the smb.conf were missing on my shares so I re added them and now I cant get into the shares.  Stayed up too late and I think I broke it even more being tired and all..  Help please..

http://ix.io/23qP

**Comment by gboudreau** [comment]
Maybe this is the problem?
```
[2019/12/03 00:14:03.412429,  0] ../../source3/auth/user_util.c:372(map_username)
  can't open username map /etc/samba/user.map. Error No such file or directory
```

Test if you can connect to a share when you comment-out the greyhole lines for the share.
If you can connect, but re-adding the greyhole lines you can't connect, tail you Samba logs while trying to connect, to see why it fails: `tail -F /var/log/samba/*`
If you can't see anything logged when trying (and failing) to connect, try a higher `log level` in smb.conf

**Comment by robojerk** [comment]
Thank for the help. I commented out that line, I get this now, same symptoms of no access to shares....
`[2019/12/03 08:34:51.184189,  0] ../../lib/param/loadparm.c:1015(lpcfg_service_ok)`

**Comment by robojerk** [comment]
Can't access it with the greyhole stuff enabled in the smbd.conf
http://ix.io/23tq

**Comment by gboudreau** [comment]
```
[2019/12/03 11:54:07.589629,  5, pid=13043, effective(0, 0), real(0, 0)] ../../lib/util/modules.c:158(load_module_absolute_path)
  load_module_absolute_path: Loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so'
[2019/12/03 11:54:07.589782,  0, pid=13043, effective(0, 0), real(0, 0)] ../../lib/util/modules.c:49(load_module)
  Error loading module '/usr/lib/x86_64-linux-gnu/samba/vfs/greyhole.so': libgenrand-samba4.so: cannot open shared object file: No such file or directory
[2019/12/03 11:54:07.589805,  0, pid=13043, effective(0, 0), real(0, 0), class=vfs] ../../source3/smbd/vfs.c:184(vfs_init_custom)
  error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
[2019/12/03 11:54:07.589819,  0, pid=13043, effective(0, 0), real(0, 0), class=vfs] ../../source3/smbd/vfs.c:380(smbd_vfs_init)
  smbd_vfs_init: vfs_init_custom failed for greyhole
```
Check which (apt/yum) package you need to install to get `libgenrand-samba4.so`

Or you can build the VFS module on your system, to ensure all the required libs are available:
```shell
sudo /usr/share/greyhole/build_vfs.sh current
```

**Comment by robojerk** [comment]
Seems like it's working now..  I tried that last night, admittedly I was tired as it approached 1am, so I might have fudged something somewhere.....

**Comment by robojerk** [comment]
Hello, so it's been working..  It hasn't been running for awhile I guess, now I'm getting this message

"Currently working on task ID 666242: write Videos/TV Shows/ShowName/Season 1/episode.nfo"
It's stuck on this

**Comment by gboudreau** [comment]
Is it still stuck ? If the daemon still running? Did you try to restart it?

**Comment by robojerk** [comment]
Yes, I had to reboot.  A simple service restart wasn't working for some reason.
