### ISSUE TITLE
Unable to install dpkg >= 0.10.16 on Debian Jessie

### ISSUE THREAD

**Issue by bsiegel** [gboudreau/Greyhole#214]
Debian packages of Greyhole starting with 0.10.16 list a dependency on `php5-mbstring | php-mbstring`. This breaks installation on Debian Jessie, because neither package exists in the repo. For Jessie, [the mbstring module is built in](https://packages.debian.org/en/jessie/php5-cli).

**Comment by bsiegel** [comment]
FWIW, I was able to work around this by creating a fake `php5-mbstring` dpkg using the `equivs` tool and installing it.

**Comment by gboudreau** [comment]
That can indeed be removed; install script installs it, if it is available, and the PHP wrapper I use also checks if it is available, which will make it pretty evident what is wrong, if it is missing for some reason.
