### ISSUE TITLE
New PHP breaks Greyhole

### ISSUE THREAD

**Issue by futz** [gboudreau/Greyhole#215]
Ubuntu Server 18.04 updated itself to PHP7.4, which broke mbstring for a month or two - it couldn't be installed. They finally fixed that, and now Greyhole is broken because of: PHP Fatal Error: Array and string offset access syntax with curly braces is deprecated; BT: greyhole[L3669]

Parts of Greyhole still work, but it's basically broken now. I don't know how to roll back to an earlier version of PHP.

**Comment by gboudreau** [comment]
You sure you are still on Ubuntu 18.04 (bionic), and are using the Ubuntu-provided apt repos?
Tat version of Ubuntu seems to be using PHP 7.2 still:
https://packages.ubuntu.com/bionic/php

**Comment by futz** [comment]
**Repos**
futz@junker:~$ cat /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu bionic main universe
deb http://archive.ubuntu.com/ubuntu bionic-security main universe
deb http://archive.ubuntu.com/ubuntu bionic-updates main universe

I added universe while trying to get mbstring installed. It didn't help.


**Ubuntu version**
futz@junker:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic


**PHP version:**
futz@junker:~$ php --version
PHP 7.4.3 (cli) (built: Feb 21 2020 17:50:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Comment by gboudreau** [comment]
What about `/etc/apt/sources.list.d/*`?

**Comment by gboudreau** [comment]
Greyhole 0.11.0 should resolve the issue with the curly braces at least; didn't test much more than that on PHP 7.4, so not sure if there are other incompatibilities. Let me know.
