### ISSUE TITLE
Greyhole in Docker - cron jobs

### ISSUE THREAD

**Issue by TheLastCicada** [gboudreau/Greyhole#218]
I know this is poor form, but I'm actually opening an issue here about the Greyhole in Docker repo https://github.com/gboudreau/samba-greyhole-docker because that repo doesn't have Issues for some reason.  If you'd like to discuss the Docker project elsewhere, just let me know where. 

One thing I noticed.... you do the standard Greyhole installation in the container, including adding cron jobs on line 24-26 (https://github.com/gboudreau/samba-greyhole-docker/blob/master/Dockerfile#L24-L26).  However, these will never run as the container doesn't run cron by default.  Two options I can see to solve that:

1. Run the cron jobs from the host system via a `docker exec` command.
2. Run `crond` with supervisor, which is already managing the other processes.  

Thanks for this project, I've had a great experience running Greyhole for many years now!

**Comment by gboudreau** [comment]
I added a proper README in that repo, with some quick instructions and pointers, including how I am running the Greyhole cron jobs.  
Let me know if something seems missing, or not working.

**Comment by TheLastCicada** [comment]
This looks great, going to look at applying this on my system and see how it goes.  Thanks!
