### ISSUE TITLE
 ERROR write: PHP Fatal Error: Call to undefined function is_iterable(); BT: greyhole[L5769]

### ISSUE THREAD

**Issue by polymathp** [gboudreau/Greyhole#219]
This was triggered after I updated samba on centos 7.7 to samba-4.9.1-10.el7.x86_64 from samba-4.9.1-6.el7.x86_64.

Also seeing

```
Greyhole VFS module (/usr/lib64/samba/vfs/greyhole.so) seems to be missing some required libraries. If you have issues connecting to your Greyhole-enabled shares, try to compile a new VFS module for Samba by running this command: /usr/share/greyhole/build_vfs.sh current
```

Running '/usr/share/greyhole/build_vfs.sh current' fails with

```
Compiling Greyhole VFS module for samba-4.9.1...
Downloading Greyhole source code...
Compiling Samba...

ls: cannot access /usr/share/greyhole/vfs-build/samba-4.9.1/bin/default/source3/modules/libvfs*greyhole.so: No such file or directory
```

samba log has

```
[2020/03/15 15:14:48.509300,  0] ../source3/smbd/vfs.c:379(smbd_vfs_init)
  smbd_vfs_init: vfs_init_custom failed for greyhole
[2020/03/15 15:14:48.509325,  0] ../source3/smbd/service.c:631(make_connection_snum)
  make_connection_snum: vfs_init failed for service 
[2020/03/15 15:14:50.513259,  0] ../lib/util/modules.c:49(load_module)
  Error loading module '/usr/lib64/samba/vfs/greyhole.so': /usr/lib64/samba/vfs/greyhole.so: cannot open shared object file: No such file or directory
```

**Comment by polymathp** [comment]
This was triggered after I updated samba on centos 7.7 to samba-4.9.1-10.el7.x86_64 from samba-4.9.1-6.el7.x86_64.

Also seeing 

 Greyhole VFS module (/usr/lib64/samba/vfs/greyhole.so) seems to be missing some required libraries. If you have issues connecting to your Greyhole-enabled shares, try to compile a new VFS module for Samba by running this command: /usr/share/greyhole/build_vfs.sh current

Running '/usr/share/greyhole/build_vfs.sh current' fails with

Compiling Greyhole VFS module for samba-4.9.1...
  Downloading Greyhole source code...
  Compiling Samba...

ls: cannot access /usr/share/greyhole/vfs-build/samba-4.9.1/bin/default/source3/modules/libvfs*greyhole.so: No such file or directory

**Comment by polymathp** [comment]
Fixed the vfs issue with ldconfig
Still seeing and greyhole stops running
Mar 15 17:02:57 ERROR write: PHP Fatal Error: Call to undefined function is_iterable(); BT: greyhole[L5769]

**Comment by polymathp** [comment]
Is there a way to empty the work queue?

Greyhole Work Queue Statistics
==============================

This table gives you the number of pending operations queued for the Greyhole daemon, per share.

           Write   Delete   Rename    Check
media         86        2        0        0
===========================================
Total         86        2        0        0
           Write   Delete   Rename    Check

The following is the number of pending operations that the Greyhole daemon still needs to parse.
Until it does, the nature of those operations is unknown.
Spooled operations that have been parsed will be listed above and disappear from the count below.

Spooled  0

**Comment by polymathp** [comment]
Emptied the queue.
It started ok but when I ran fsck seeing the same error
Mar 15 17:40:32 ERROR fsck: PHP Fatal Error: Call to undefined function is_iterable(); BT: greyhole[L5769]

**Comment by gboudreau** [comment]
You can work around this by either upgrading PHP to 7.1+ (really recommended; PHP 7.0 is really old).
Or edit `/usr/bin/greyhole` in a text editor, and replace `is_iterable` by `is_array` (there is only one occurrence).
I'll provide a better fix in the next Greyhole release.

**Comment by gboudreau** [comment]
Version 0.11.2 should resolve this issue; so you could update to the latest version to fix this.

**Comment by polymathp** [comment]
You're awesome! Updated PHP to 7.4.3
Cooking with fire again!
Will wait for the rpm package to be added to repo.
