### ISSUE TITLE
Incorrect errror provided when testparms not found

### ISSUE THREAD

**Issue by arnonm-intel** [gboudreau/Greyhole#221]
For some reason, after changing samba versions, the testparm was not copied into the path.
Greyhole depends on it, and when it can't find it, provide an error that share XXX is found in greyhole.conf and not in smb.conf - which is the incorrect error.
Could be resolved with a fix in `ConfigHelper.php` to test if `$config_test` after the following line:
```
exec('testparm -s ' . escapeshellarg(self::$smb_config_file) . ' 2> /dev/null', $config_text);
```

**Comment by gboudreau** [comment]
Version 0.12.0 contains this fix. Thanks for taking the time to report this.
