### ISSUE TITLE
I upgradeded to Ubuntu 20.04 Focal & ran into a few issues but I got it back up.

### ISSUE THREAD

**Issue by robojerk** [gboudreau/Greyhole#223]
I upgraded the OS, I was having issues mounting the drives locally and remotely, so I tried to compile  the vfs with the script but that was throwing an error at me about the source3 directory not existing. I rm -rf the build dir but same error..  Finally just decided to purge and reinstall and that got it working..

These are all the commands I had to do to bring it back up.
```
sudo cp /etc/samba/smb.conf ~/smb.conf && \
sudo cp /etc/greyhole.conf ~/greyhole.conf && \
sudo apt-get remove --autoremove --purge -y greyhole && \
sudo apt-get remove --autoremove --purge -y samba && \
sudo apt-get install -y samba cifs-utils && \
curl -Ls http://bit.ly/greyhole-package | sudo bash && \
sudo systemctl stop smbd.service greyhole.service && \
sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.original && \
sudo cp /etc/greyhole.conf /etc/greyhole.conf.original && \
sudo mv ~/smb.conf /etc/samba/smb.conf && \
sudo mv ~/greyhole.conf /etc/greyhole.conf && \
sudo /etc/init.d/mount_shares_locally stop && \
sudo systemctl start smbd.service greyhole.service && \
sudo /etc/init.d/mount_shares_locally start
```

**Comment by gboudreau** [comment]
How did you update? What version were you using before?
I'll see if I can reproduce the issue with a VM and snapshots.

**Comment by gboudreau** [comment]
`/usr/share/greyhole/build_vfs.sh current` is still failing for you, right?
Could you try this updated version?

```
sudo -i
rm -rf /usr/share/greyhole/vfs-build
curl -Lo /usr/share/greyhole/build_vfs.sh https://gist.githubusercontent.com/gboudreau/3b9bd877a2dba6877a5e45aa81d6b3ad/raw/build_vfs.sh
chmod +x /usr/share/greyhole/build_vfs.sh
/usr/share/greyhole/build_vfs.sh current
```

It should give a better error message, when configure fails, with a hint on how to install missing dependencies.

**Comment by Fabaderheld** [comment]
I have the same issue but reinstalling didn't fix it for me.
Here is the output of the build
`root@backup:~# rm -rf /usr/share/greyhole/vfs-build
root@backup:~# curl -Lo /usr/share/greyhole/build_vfs.sh https://gist.githubusercontent.com/gboudreau/3b9bd877a2dba6877a5e45aa81d6b3ad/raw/build_vfs.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5898  100  5898    0     0  16997      0 --:--:-- --:--:-- --:--:-- 16997
root@backup:~# chmod +x /usr/share/greyhole/build_vfs.sh
root@backup:~# /usr/share/greyhole/build_vfs.sh current
Compiling Greyhole VFS module for samba-4.11.6...
  Downloading Greyhole source code...
  Downloading Samba source code...
  Running 'configure'...
Configuring Samba failed.
Hint : install the required dependencies. See step 3 in https://raw.githubusercontent.com/gboudreau/Greyhole/master/INSTALL

tail /usr/share/greyhole/vfs-build/samba-4.11.6/gh_vfs_build.log :
Checking for variable _res                                                        : ok
Checking for declaration of _res                                                  : ok
Checking for dirfd                                                                : ok
Checking for declaration of dirfd                                                 : ok
Checking for member dd_fd in DIR                                                  : not found
Using in-tree heimdal kerberos defines
Checking for program 'pkg-config'                                                 : not found
Checking for GnuTLS >= 3.2.0                                                      : not found
The configuration failed
(complete log in /usr/share/greyhole/vfs-build/samba-4.11.6/bin/config.log)`

**Comment by gboudreau** [comment]
The actual helpful part is this here:
> Hint : install the required dependencies. See step 3 in https://raw.githubusercontent.com/gboudreau/Greyhole/master/INSTALL

Step 3 in INSTALL is: https://github.com/gboudreau/Greyhole/blob/master/INSTALL#L75-L81

In particular:
    sudo apt -y install build-essential python3-dev libgnutls28-dev pkg-config

**Comment by Fabaderheld** [comment]
Thanks it working now! I thought using the script would install all required dependencies.

**Comment by gboudreau** [comment]
Yeah, I could probably have those dependencies installed in that script. Will look into that.
