### ISSUE TITLE
Slow file copies when (one) target is on same drive as LZ

### ISSUE THREAD

**Issue by gboudreau** [gboudreau/Greyhole#225]
> Hello,
> 
> Really appreciate the work you do! I've been using gh for a while and generally very happy with it!
> 
> Since my previous comment was deleted, I think it had something to do with My LZ on the same drive as one of the data drives, so copies are slow. In general I found that on my machine cat | tee f1 f2 is much slower and avg copy speed is ~24MB/s, where as sequential copies were ~90-100mb/s
> 
> My point was that this needs to be an option, even just for the sake of backward compatibility. greyhole does not have an easy path of roll-backwards. I tried to install 0.11-2 on my machine without success (and I can't apt pin it as it's no longer available from the apt repo).
> 
> Thoughts?

**Comment by gboudreau** [comment]
Parallel copying should NOT happen when one of the target is on the same partition as the source file (normally the LZ). I'll fix that.

Will also look into the apt repo thing; pretty sure all the old versions are still there; will confirm they are not available, and see how I can make them available... Been a while since I created the scripts that updates the packages repos when a new version is created.

And yes, there should be config options to this, (and for the MD5 calculations that were added recently too). I'll add those.

**Comment by gboudreau** [comment]
To install an old version:
```
echo "deb https://www.greyhole.net/releases/deb stable main previous before-previous" > /etc/apt/sources.list.d/greyhole.list
apt update
apt-get install greyhole=0.11.2-1
```

**Comment by gboudreau** [comment]
New config file options:

```
#### Copying ####
# Options for the command that will create file copies

# Calculate MD5 of new/changed files, while making file copies.
#    calculate_md5 = yes

# Create all file copies simultaneously, instead of sequentially.
#    parallel_copying = yes
```

**Comment by gboudreau** [comment]
0.12.2 contains all the above fixes, including the fix that will skip the file copy on the same partition, when creating file copies in parallel; that file copy will be created using a rename, just after the other copies were created.

**Comment by assafw** [comment]
Thanks a lot! fantastic turnover
