### ISSUE TITLE
Greyhole in Docker mem-spool failure

### ISSUE THREAD

**Issue by TheLastCicada** [gboudreau/Greyhole#226]
I'm running Greyhole in Docker using https://github.com/gboudreau/samba-greyhole-docker and overall it is working well.  However, when I view the Docker logs for the container, it always shows the following:

```
2020-04-06 08:09:48,333 INFO exited: greyhole-mem-spool (exit status 0; not expected)
2020-04-06 08:09:48,333 INFO gave up: greyhole-mem-spool entered FATAL state, too many start retries too quickly
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
2020-04-06 08:09:48,375 INFO exited: greyhole-boot-init (exit status 0; not expected)

```
Greyhole and Samba themselves are working fine, but the mem-spool and boot-init seem to always fail.  Any suggestions on how to troubleshoot this or what these processes might depend on that I can check?

**Comment by gboudreau** [comment]
It's normal for those two processes to exit (with status 0); they need to run when the container starts, but they are not expected to continue running past that.

Maybe the supervisord config could be tweaked to expect that, and thus not log what looks like a problem (but isn't), but I didn't find how to do that. I simply instruct supervisord to not try to restart the process once it dies (`autorestart=false`).

**Comment by gboudreau** [comment]
Ah, I think `startsecs=0` in the sections for those two programs should do it:

```
[program:greyhole-mem-spool]
priority=100
command=/usr/bin/greyhole --create-mem-spool
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0
startsecs=0

[program:greyhole-boot-init]
priority=101
command=/usr/bin/greyhole --boot-init
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=false
startretries=0
startsecs=0
```

**Comment by TheLastCicada** [comment]
Much nicer:

```
2020-04-11 17:03:08,513 INFO exited: greyhole-mem-spool (exit status 0; expected)
2020-04-11 17:03:08,662 INFO exited: greyhole-boot-init (exit status 0; expected)
```

Thanks!
