### ISSUE TITLE
Issues after system update

### ISSUE THREAD

**Issue by crl0901** [gboudreau/Greyhole#229]
After updating my CentOS system (yum update), my greyhole shares were no longer accessible.  My Samba version is 4.10.4.  I followed the steps on the wiki to create a new symlink to the samba4-10 file and restarted both samba and greyhole, but I'm getting the following error message:

[2020/05/08 08:38:37.868583,  0] ../../lib/util/modules.c:49(load_module)
  Error loading module '/usr/lib64/samba/vfs/greyhole.so': libgssapi-samba4.so.2: cannot open shared object file: No such file or directory
[2020/05/08 08:38:37.868677,  0] ../../source3/smbd/vfs.c:185(vfs_init_custom)
  error probing vfs module 'greyhole': NT_STATUS_UNSUCCESSFUL
[2020/05/08 08:38:37.868756,  0] ../../source3/smbd/vfs.c:380(smbd_vfs_init)
  smbd_vfs_init: vfs_init_custom failed for greyhole
[2020/05/08 08:38:37.868793,  0] ../../source3/smbd/service.c:633(make_connection_snum)
  make_connection_snum: vfs_init failed for service TV

**Comment by gboudreau** [comment]
Did you check the greyhole.log file? When you restart the daemon, it should tell you something about a non-working VFS module, with instructions on how to fix.
Something about running `/usr/share/greyhole/build_vfs.sh current`

**Comment by crl0901** [comment]
So focused on samba I forgot to check the greyhole log.  Yes, after installing python3 and python3-devel, I was able to run that build_vfs script and get the shares working again.  Thanks!
