### ISSUE TITLE
Status not working after update to 0.12.3

### ISSUE THREAD

**Issue by gazhay** [gboudreau/Greyhole#230]
Using greyhole, version 0.12.3, for linux-gnu (noarch)
updated through apt today.

Greyhole is confirmed as running and --status returns valid information, however, --status always returns 
````
Greyhole daemon is currently stopped.
````

But tailing var/log/greyhole gives valid messages.

**Comment by gboudreau** [comment]
What does `ps auxf | grep greyhole` show? Pretty sure --status uses `ps` to check if the daemon is running or not.

**Comment by gazhay** [comment]
````
$ ~ >>> greyhole --status                                                                                cassie 09:11:08

Greyhole daemon is currently stopped.

$ ~ >>> ps auxf | grep greyhole                                                                          cassie 09:11:09
root       3580  0.0  0.0   4504   796 ?        Ss   09:11   0:00      \_ /bin/sh -c  /usr/bin/greyhole --process-spool --keepalive
root       3581  0.0  0.0  12516  3068 ?        S    09:11   0:00          \_ /bin/bash /usr/bin/greyhole-php /usr/bin/greyhole --process-spool --keepalive
root       3587  0.2  0.5 216916 23932 ?        S    09:11   0:00              \_ /usr/bin/php /usr/bin/greyhole --process-spool --keepalive
gaz        4198  0.0  0.0  14224  1028 pts/2    S+   09:11   0:00              \_ grep --color greyhole
$ ~ >>>          
````

**Comment by gboudreau** [comment]
The daemon is not running. The running process is simply reading the Samba VFS spool, and inserting into the database, but the `greyhole --daemon` processing is not running.

**Comment by gazhay** [comment]
During the upgrade it asked me to replace 

/etc/init.d/greyhole
/etc/init/greyhole

And

/etc/greyhole.conf

I replaced the first 2, but not the last as obvious it would have killed the storage pool.

How do I fix to get a working install again?
I'm not doing anything particularly strange, its apt installed and was working fine.
(It still appears to be working, but given what you have said, I assume my incoming dir will be filling up)

**Comment by gboudreau** [comment]
Start the daemon manually (`systemctl restart greyhole`, or the equivalent on your system to start a service).
If the Greyhole daemon is not running after you manually restarted it, check `/var/log/greyhole.log` or syslog for hints on why.

**Comment by gazhay** [comment]
I found /etc/init.d/greyhole.dpkg.old

When I diffed it 

````
47c47
<     DAEMON_RUNNING=`ps ax | grep "^ *$PID.*greyhole --daemon\|^ *$PID.*greyhole -D" | grep -v grep | grep -v bash | wc -l`
---
>     DAEMON_RUNNING=`ps ax | grep "^ *$PID.*greyhole --daemon\|^ *$PID.*greyhole -D" | grep -v grep | wc -l`
64c64
< 	[ $RETVAL -eq 0 ] && ps ax | grep "greyhole --daemon" | grep -v grep | grep -v bash | tail -1 | awk '{print $1}' > $PIDFILE
---
> 	[ $RETVAL -eq 0 ] && ps ax | grep "greyhole --daemon" | grep -v grep | tail -1 | awk '{print $1}' > $PIDFILE
82c82
<             start-stop-daemon --start --pidfile $PIDFILE --exec /usr/bin/greyhole-php --nicelevel $n --background -- /usr/bin/greyhole --daemon
---
>             start-stop-daemon --start --pidfile $PIDFILE --exec /usr/bin/php --nicelevel $n --background -- -d open_basedir=/ /usr/bin/greyhole --daemon
106c106
< 	[ $RETVAL -eq 0 ] && ps ax | grep "greyhole --daemon" | grep -v grep | grep -v bash | tail -1 | awk '{print $1}' > $PIDFILE
---
> 	[ $RETVAL -eq 0 ] && ps ax | grep "greyhole --daemon" | grep -v grep | tail -1 | awk '{print $1}' > $PIDFILE
123d122
< 	/usr/bin/greyhole --process-spool >/dev/null

````
Swapping this old version back in and rebooting got greyhole daemon up again.

Additionally, a greyhole daemon_start *before* I did the above started the daemon on my system.
