### ISSUE TITLE
fyi - mysql 8 user creation change

### ISSUE THREAD

**Issue by johnruck** [gboudreau/Greyhole#232]
Well, from what I can tell it looks like MySQL 8 wont allow creation of users from the grant command anymore (says there is a syntax error at the identified by clause), so it looks like you might need to update your Usage document on the part of MySQL setup.  Here is an updated line that works by doing an explicit user creation step.  This issue was found on ubuntu 20.04.  

mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS greyhole; CREATE USER IF NOT EXISTS greyhole_user@localhost IDENTIFIED BY '89y63jdwe'; GRANT ALL ON greyhole.* TO greyhole_user@localhost;"

**Comment by gboudreau** [comment]
Thanks, will fix.
