### ISSUE TITLE
exceptions in greyhole-dfree

### ISSUE THREAD

**Issue by cpg** [gboudreau/Greyhole#235]
It appears recent versions of greyhole-dfree.php make reference to class `DaemonRunner` however, this class appears to not be present in the code, resulting in this exception and share sizes being reported as zero:
```
PHP Fatal error:  Uncaught Error: Class 'DaemonRunner' not found in /usr/share/greyhole/greyhole-dfree.php:3388
```

It appears that adding both classes `DaemonRunner` and `AbstractRunner` to greyhole-dfree.php fixes this issue superficially. No idea if that is actually a fix at all.

**Comment by gboudreau** [comment]
Hi Carlos. Long time! I'll take a look at this; should be trivial to fix; an include or two to add!

**Comment by gboudreau** [comment]
v0.13.3 (just pushed to the packages repositories) should resolve this. Cheers.

**Comment by cpg** [comment]
there [appears to be](https://bugs.amahi.org/issues/2427#note-22) some sort of double-inclusion perhaps?
```
PHP Fatal error:  Cannot declare class DaemonRunner, because the name is already in use in /usr/share/greyhole/greyhole-dfree.php on line 7896
```

**Comment by gboudreau** [comment]
Hum. I don't get that error. Weird.

**Comment by gboudreau** [comment]
Probably a bug in the build tool I use to create the binaries...

**Comment by cpg** [comment]
Not too sure how this works, but it looks as if the `greyhole-dfree.php` file in the distribution has `class DaemonRunner extends ...` so, if it's called with greyhole-php it's already included there, hence the error?

**Comment by gboudreau** [comment]
Ah, are you sure it's not because of your previous workaround..? Ref: https://bugs.amahi.org/issues/2427#note-18

**Comment by cpg** [comment]
No, I'm not. It is!

I created a patch file and forgot to take it out! bad `cpg`, no cookie.

**Comment by cpg** [comment]
Question. How can we try greyhole-dfree by hand?

The small man page does not seem to indicate how it knows what share ...

Can we try it through the cli? command line? environment variable? current working directory?

We're getting reports that the error is not there, but it does not report the sizes at all on a system that should. I get `0 0 1024` on a system I can test a bit , but it is without greyhole fully enabled.

**Comment by gboudreau** [comment]
```
cd /path/to/share/as/defined/in/smb.conf
greyhole-dfree .
greyhole-dfree -h .
```
or just `greyhole-dfree /path/to/share/as/defined/in/smb.conf`

It takes the path specified, and looks for that path in smb.conf; it will also find the share, if the path defined in smb.conf is a prefix of the specified path, eg. `greyhole-dfree /path/to/share/as/defined/in/smb.conf/some/dir` also works.

**Comment by cpg** [comment]
We see output like this and it does not seem to be displayed. Is it correct?:
`9611081888 2693765865.3333 102`

**Comment by gboudreau** [comment]
I'm guessing windows expects integers, and thus the 2nd number throws it off.
I'll just round it.

**Comment by gboudreau** [comment]
v0.13.4 fixes this.

FYI, the free space reported by Greyhole now takes into account the number of file copies configured for the share.
So if you have 1TB free, and num_copies = 2, Greyhole will report 500GB free. 1TB was reported (before 0.13).
