### ISSUE TITLE
Installing greyhole on Raspberry Pi 4

### ISSUE THREAD

**Issue by sosojni** [gboudreau/Greyhole#236]
I got my hands on R PI 4 and i'd like to switch my file server from R PI 2. When i try to install greyhole i get this error:

N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://www.greyhole.net/releases/deb stable InRelease' doesn't support architecture 'arm64'

Is there a way to install greyhole on Pi 4?

**Comment by gboudreau** [comment]
I don't build `arm64` packages, thus the error you are receiving.
You can install Greyhole by following the instructions in the [INSTALL](https://github.com/gboudreau/Greyhole/blob/master/INSTALL) file.

Not sure how up to date those instructions are, or if they will work on your OS (Raspbian?)

Please report missing or modified steps you had to execute, so I can updated the INSTALL file as needed.

**Comment by sosojni** [comment]
Now this is funny thing. If i install 64bit system (from Raspberry Pi Imager v1.3) i can not install Greyhole with error i wrote in my first post. In Imager, system is called: Ubuntu 20.04 LTS (Raspberry Pi 3/4) and in description it sais: 64-bit server OS for arm64 architectures.

But if i install 32bit system, using same program, just picking another option, Greyhole can be installed. System is called: Ubuntu 20.04 LTS (Raspberry Pi 2/3/4) and description says: 32-bit server OS for armhf architectures (recommended)

Both systems install without of any errors and everything that i can install works fine (samba, disk mounting etc.)

I must point out that i have very little knowledge of ARM boards / systems so i can't really guess where would problem be or what differences betvean systems are (besides 64 bit vs 32 bit).

To test it out trying to install Greyhole on another borad i have (freshly installed PINE64 LTS + Armbian_20.05.2_Pine64so_bionic) and i get same error just like with Raspberry Pi 4 + 64bit server OS, but this time i get additional error info in form of:

The following packages have unmet dependencies:
 greyhole:armhf : Depends: samba:armhf (>= 3.4.3) but it is not going to be installed
                  Depends: lsof:armhf but it is not going to be installed
                  Depends: sysstat:armhf but it is not going to be installed
                  Depends: mysql-server:armhf or
                           mysql-server-5.5:armhf but it is not installable or
                           mysql-server-5.6:armhf but it is not installable or
                           mysql-server-5.7:armhf but it is not going to be installed or
                           mysql-community-server:armhf but it is not installable or
                           mariadb-server:armhf but it is not installable or
                           mariadb-server-5.5:armhf but it is not installable or
                           mariadb-server-5.6:armhf but it is not installable or
                           mariadb-server-10.1:armhf but it is not going to be installed
                  Depends: php5-cli:armhf (>= 5.5) but it is not installable or
                           php-cli:armhf (>= 5.5)
                  Depends: php-pear:armhf but it is not installable
                  Depends: php5-intl:armhf but it is not installable or
                           php-intl:armhf
                  Depends: php5-mysql:armhf but it is not installable or
                           php5-mysqlnd:armhf but it is not installable or
                           php-mysql:armhf but it is not installable or
                           php-mysqlnd:armhf


After looking at this error and remembering OS description in Raspberry Pi Imager my best guess is that problem lies in "architecture" part of OS descriptio. OS i installed (and where i can not install Greyhole) is arm64 and dependancies are calling for armhf versions.

So, for now, i will keep armhf OS on Raspberry 4 (which in turn means i will not be able to use all 4GB of RAM as it's 32 bit OS), but i need my file storage desperately right now.

What i will be doing is start testing (for starters, manual instalation) on PINE64 LTS board.

**Comment by sosojni** [comment]
Well, today i learned that "architecture" does not refer only to instruction set, but it can refer to something called "Application Binary Interface", which i had no idea it exists. That pretty much explained to me how can one system have one architecture and another system another on same board.

I followed INSTALL instructions and i could not get past this step:
cp samba-module/bin/$SMB_VERSION/greyhole-$(uname -m).so "$LIBDIR/greyhole/greyhole-samba${SMB_VERSION//.}.so"
Error is: cp: cannot stat 'samba-module/bin/4.5/greyhole-aarch64.so': No such file or directory

Is it possible to somehow create .so file for my architecture?

**Comment by gboudreau** [comment]
Yes. There is a script to create that library (.so) file : 
`/usr/share/greyhole/build_vfs.sh current`
(There are instructions to use that script, in the INSTALL file, if your Samba version is not supported. Just follow those instructions; they apply to you, since the library you need is not part of the release.)

**Comment by sosojni** [comment]
To make it as clean as possible, i reinstalled system to new armbian for my board and i am currently running script. It is compiling Samba and doing stuff i have no idea what they are. 
While it was running i noticed it got slower and slower. I was wondering is that normal, so i opened new term and decided to see which processes are running. I found out that there are 5 PHP processes that are eating all CPU.
I am pretty much sure PHP is not part of compiling programs, so i killed those processes and compiling got way faster.
Weird thing is they pop up again every few mins again and i have to kill them.
After some thinking i remembered that there was cron job installed that is running greyhole  and my guess is those php processes are Greyhole trying to do something but can't as it's not installed all the way.
Anyway, if someone is in same problem as i am, feel free to remove /etc/cron.d/greyhole and you will not have php processes spawning all the time and compiling will run faster.
Of course, you have to install it there again after you are finished with compiling.

@gboudreau Maybe installing steps in INSTALL file (at least cron jobs) should be executed later in process of instalation.

**Comment by sosojni** [comment]
Ok, so script did it's job and i got this message:

Greyhole VFS module successfully compiled into /usr/share/greyhole/vfs-build/samba-4.11.6/greyhol                                                                                                                                                                                                                            e-samba411.so

Creating the required symlink in the Samba VFS library folder.
ln: failed to create symbolic link '/usr/lib/samba/vfs/greyhole.so': No such file or directory

As they say, you win some, you loose some. 

What i did next is i copied file that was created by compilation process to /root/greyhole-0.13.4/samba-module/bin/4.11/
I renamed it to: greyhole-aarch64.so so that your INSTALL commands would find it.

After running: 
cp samba-module/bin/$SMB_VERSION/greyhole-$(uname -m).so "$LIBDIR/greyhole/greyhole-samba${SMB_VERSION//.}.so"

I get this error: 
cp: cannot create regular file '/usr/lib/greyhole/greyhole-samba411.so': No such file or directory

I checked and there is no: "usr/lib/greyhole" directory. Should i create it or it should have been created in some steps before this?

**Comment by gboudreau** [comment]
No need to. The file can stay in `/usr/share/greyhole/vfs-build/`
What you need to do is find the `samba/vfs` lib dir (the script thinks it is in `/usr/lib/samba/vfs/`, but it apparently is not there... Maybe `/usr/lib64/samba/vfs/` ?
Once you found that folder, create a symlink in there that points to the `greyhole-samba411.so` file:

    sudo ln -s /usr/share/greyhole/vfs-build/samba-4.11.6/greyhole-samba411.so /path/to/samba/vfs/greyhole.so

**Comment by sosojni** [comment]
- I had some mysql problems (only 2 GB of ram on PINE64 LTS) which made me reinstall mysql, after which i had some error issues with samba vfs folder so to be sure it's not because of mysql problems i just wiped board and reinstalled clear image.
This time, i picked what i was hoping to be more stable version of Armbian:
Armbian_20.05.2_Pine64so_buster_current_5.4.43.img
With it, i ran into problems on very first line of INSTALL file. This version of OS had no mysql-server package so i had to replace it with mariadb-server. Once i had it changed, install line worked.

Went trough installing steps from INSTALL file:
- Same problem with spawning php processes just like in last try, removing "greyhole" cron job from /etc/cron.d/ stops them
- Same error about missing ".so" file
- What i did not write in my last message but i remember i had same problem was that there is no build_vfs.sh script in /usr/share/greyhole/. I had to copy it from source folder (in my last try i just ran it from my source folder and it worked).
- Script successfully created .so file with message:
Greyhole VFS module successfully compiled into /usr/share/greyhole/vfs-build/samba-4.9.5/greyhole-samba49.so
but could not link it to "/usr/lib/samba/vfs/"
- There is no "samba/vfs" dir anywhere in system except source folder and greyhole directory inside /usr/share. After some googleing i found out that in newer systems, samba does not install "samba-vfs-modules" with rest of the samba packages listed in INSTALL file (it used to be dependency for one of samba packages in INSTALL file).
- Installed samba-vfs-modules by: "apt-get install samba-vfs-modules" and now i can find vfs folder here: /usr/lib/aarch64-linux-gnu/samba/vfs
Maybe that package should be added in first line of INSTALL file?
In vfs folder i can find bunch of .so files, so i guess that's good place for greyhole.so link
- After ln -s /usr/share/greyhole/vfs-build/samba-4.9.5/greyhole-samba49.so /usr/lib/aarch64-linux-gnu/samba/vfs/greyhole.so i can see link in there
- installed start script for my system (systemd)
- restarted smbd service
- added greyhole service to list of services that start on boot
- installed cron jos i removed before: install -m 0644 -D -p greyhole.cron.d /etc/cron.d/greyhole
- switched to USAGE file
- i went trough USAGE file and executed every command without of any errors

Now i can see this error in greyhole logs:

Jun 22 00:35:54 INFO daemon: Greyhole (version 0.13.4) daemon started.
Jun 22 00:35:54 INFO daemon: Checking MySQL tables...
Jun 22 00:35:57 DEBUG daemon: Checking symlink at /usr/lib/samba/vfs/greyhole.so...
Jun 22 00:35:57 WARN daemon:   Greyhole VFS module for Samba was missing, or the wrong version for your Samba. It will now be replaced with a symlink to /usr/lib/greyhole/greyhole-samba49.so
Jun 22 00:35:57 WARN daemon: PHP Warning [2]: mkdir(): No such file or directory in /usr/bin/greyhole on line 4309; BT: greyhole[L7840] run() => greyhole[L7807] initialize() => greyhole[L7829] samba_check_vfs() => greyhole[L4309] mkdir(/usr/lib/samba/vfs)
Jun 22 00:35:57 WARN daemon: PHP Warning [2]: symlink(): No such file or directory in /usr/bin/greyhole on line 5285; BT: greyhole[L7840] run() => greyhole[L7807] initialize() => greyhole[L7829] samba_check_vfs() => greyhole[L4311] gh_symlink(/usr/lib/greyhole/greyhole-samba49.so,/usr/lib/samba/vfs/greyhole.so) => greyhole[L5285] symlink(/usr/lib/greyhole/greyhole-samba49.so,/usr/lib/samba/vfs/greyhole.so)
Jun 22 00:35:57 INFO daemon: The Samba daemon will now restart...

Than it restarts and tries again, fails, restarts and goes like that in circles.

I had idea that i could just create samba/vfs in lib directory and see what happens. As soon as i created /usr/lib/samba dir new round of failed deamon created vfs folder and linked .so file.

After that, Greyhole is running with standard: Jun 22 00:40:22 DEBUG sleep: Nothing to do... Sleeping.

I think that is it. I can see greyhole reacting to new files / folders in test shares i created. I will copy paste old samba/greyhole confs from raspberry and connect few of my disks to see it in action, but tha tshould be it.

Thanks for your help. I hope this helps someone else with arm64 architecture systems. I learned a lot.

Maybe you could create one "descriptive" INSTALL file, or maybe section in current INSTALL file that would mention possible problems with mysql vs mariadb, missing .so files and what is really important for system to work after .do file is created.

**Comment by gboudreau** [comment]
Thank you very much for all those details.
I integrated what I could into the INSTALL file, and added an `arm64` arch in my build script, to be created next time I create a new version.
I'll try to dust-off my Pi4 soon, and try those new steps, to ensure I didn't miss something, and if I can, I'll create the necessary .so binaries for arm64 too.

**Comment by gboudreau** [comment]
FYI, Greyhole can now be installed from APT repos on arm64 (aarch64).
Tested on a NanoPi NEO4 running Ubuntu Bionic aarch64.

**Comment by uSlackr** [comment]
Great news!
