### ISSUE TITLE
Have my drive references gotten messed up?

### ISSUE THREAD

**Issue by old-square-eyes** [gboudreau/Greyhole#237]
Have just updated and upgraded. Which I believe took me from 0.12.2 to 0.13.4.

Seems a balance kicked off. But I'm seeing a lot of these errors.

`ERROR balance: The directory at /srv/dev-disk-by-label-gh06/gh doesn't exist. This drive will never be used! See the INSTALL file for instructions on how to prepare partitions to include in your storage pool.`

```
greyhole -s

Greyhole Statistics
===================

Storage Pool
                                   Total -   Used =   Free +  Trash = Possible
  /srv/dev-disk-by-label-gh01/gh:   916G -   554G =   362G +     0G =   362G
  /srv/dev-disk-by-label-gh02/gh:   916G -   675G =   240G +     0G =   240G
  /srv/dev-disk-by-label-gh03/gh:   916G -   663G =   253G +     0G =   253G
  /srv/dev-disk-by-label-gh04/gh:   916G -   582G =   334G +     0G =   334G
  /srv/dev-disk-by-label-gh05/gh:   292G -    32G =   260G +     0G =   260G
  /srv/dev-disk-by-label-gh06/gh:                  Offline                  
                                  ==========================================
  Total:                           3956G -  2507G =  1449G +     1G =  1450G
```

When I `df -h /srv/dev-disk-by-label-gh06` I actually get to an empty dir.

`/dev/sda2        49G  2.5G   44G   6%`

This looks suspiciously like my OS drive, which I never configured GH for.

I'm worried the drive references have gotten messed up.

**Comment by old-square-eyes** [comment]
The offline drive was a 2TB drive I recently installed, and did a balance across to. It was a used, acquired drive, and was working. I wonder if the cable has come loose. Still off GH06 seems to point to my OS drive.

**Comment by old-square-eyes** [comment]
I have just done a   `greyhhole -w /srv/dev-disk-by-label-gh06/gh`

**Comment by gboudreau** [comment]
Looks like your GH06 drive is simply unmounted. Can be numerous reasons.
Try to re-mount it manually: `sudo mount /srv/dev-disk-by-label-gh06`.
Try to reboot, check that your BIOS sees the drive. If not, try to unplug a re-connect the drive; try another SATA cable, try another SATA port, etc.

**Comment by old-square-eyes** [comment]
Cool. So cd /srv/dev-disk-by-label-gh06 being a so called dir on my OS drive is a red herring? And probably just a link to the share?

**Comment by gboudreau** [comment]
It's totally normal; your mount points are on your `/` drive, until the OS mounts your drives there (as defined in `/etc/fstab`).
And once unmounted, they just go back to empty folders on your `/` drive.

Greyhole detects when that happens, and sends an email to notify you, and will stop using that folder until it re-appears. Until then, it launches a `fsck` to fix the now broken symlinks on your shares, which are symlinks pointing to now gone files on GH06. If Greyhole finds other copies on those files on other drives, it will fix the symlinks, and re-create a new file copy, if it can (but you disabled this by running `greyhole -w`).

**Comment by old-square-eyes** [comment]
Great. Good to know thanks. I'll open up the machine in the morning and investigate the cabling. If it's dead GH can do its thing :)

**Comment by old-square-eyes** [comment]
Replacing the sata cable fixed the issue thanks.
