### ISSUE TITLE
vfs not building and greyhole getting stuck on tasks.

### ISSUE THREAD

**Issue by ajwtech** [gboudreau/Greyhole#248]
vfs not building and greyhole getting stuck on tasks. 

Updated Greyhole and Samba (and the os, arch linux). Samba is version 4.13. I used the recently added .so in the repo because generating the library myself failed with: 

```[root@hostnamefastvod greyhole-0.15.0]# ./build_vfs.sh current
Installing build dependencies ...
Installing Parse::Yapp::Driver perl module ...
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/root/.cpan/Metadata'
  Database was generated on Tue, 01 Dec 2020 01:56:21 GMT
Parse::Yapp::Driver is up to date (1.21).

Compiling Greyhole VFS module for samba-4.13.2...
  Downloading Greyhole source code...
  Compiling Samba...

ls: cannot access '/usr/share/greyhole/vfs-build/samba-4.13.2/bin/default/source3/modules/libvfs*greyhole.so': No such file or directory
```
Greyhole is frequently getting stuck on tasks. log has this message in it. 

```Dec 01 19:17:16 INFO daemon: Greyhole (version 0.15.0) daemon started.
Dec 01 19:17:16 INFO daemon: Checking MySQL tables...
Dec 01 19:17:16 WARN daemon:   Greyhole VFS module (/usr/lib/samba/vfs/greyhole.so) seems to be missing some required libraries. If you have issues connecting to your Greyhole-enabled shares, try to compile a new VFS module for Samba by running this command: /usr/share/greyhole/build_vfs.sh current```

**Comment by gboudreau** [comment]
The build script for the VFS had to be updated for Samba 4.13 (it requires an additional --something in the ./configure command, and it also needs an extra apt dependency).
Is the log above from a build_vfs command that you ran after installing Greyhole 0.15.1 (which adds the Samba 4.13 .so )?

Log: I see only INFO and WARN (which seems to indicate the VFS .so you are using is missing required libraries; are you able to connect to your shares..?); is log_level = INFO in your config?
If so, I would suggest using DEBUG instead, and restarting the daemon. You'll have much better logs to understand what the daemon is doing, when it appears stuck.
You could also use strace to check what the daemon process if doing, when stuck.

**Comment by ajwtech** [comment]
So, I just noticed that 0.15.1 was released yesterday and the release I downloaded was 0.15.0.  I am going to update Greyhole again and see if that fixes these 2 problems, and report back. 

To answer your other question, I can access the shares, that doesn't seem to be a problem at all. I'll turn on debug if it gets stuck again, too. 

Thanks.

**Comment by ajwtech** [comment]
I updated to 0.15.1 and see the same behavior from vfs. As for the tasks stalling I have thrown a lot at it and haven't seen it lock up again.  

I still see this message when Greyhole starts but dont have issues accessing the shares, that I am aware of:

``` Dec 01 23:26:08 DEBUG read_smb_spool: Processing Samba spool...
Dec 01 23:26:09 INFO daemon: Greyhole (version 0.15.1) daemon started.
Dec 01 23:26:09 INFO daemon: Checking MySQL tables...
Dec 01 23:26:09 DEBUG daemon: Loading metadata store backup directories...
Dec 01 23:26:09 DEBUG daemon:   Found 2 directories in the settings table.
Dec 01 23:26:09 DEBUG daemon: Checking symlink at /usr/lib/samba/vfs/greyhole.so...
Dec 01 23:26:09 DEBUG daemon:   Is OK.
Dec 01 23:26:10 WARN daemon:   Greyhole VFS module (/usr/lib/samba/vfs/greyhole.so) seems to be missing some required libraries. If you have issues connecting to your Greyhole-enabled shares, try to compile a new VFS module for Samba by running this command: /usr/share/greyhole/build_vfs.sh current
Dec 01 23:26:10 DEBUG read_smb_spool: Processing Samba spool...
```

build_vfs.sh still gives this error as well. 

```[root@hostnamefastvod greyhole-0.15.1]# ./build_vfs.sh current
Installing build dependencies ...
Installing Parse::Yapp::Driver perl module ...
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/root/.cpan/Metadata'
  Database was generated on Tue, 01 Dec 2020 01:56:21 GMT
Parse::Yapp::Driver is up to date (1.21).
Installing zlib-devel ...

Compiling Greyhole VFS module for samba-4.13.2...
  Downloading Greyhole source code...
  Compiling Samba...

ls: cannot access '/usr/share/greyhole/vfs-build/samba-4.13.2/bin/default/source3/modules/libvfs*greyhole.so': No such file or directory
[root@hostnamefastvod greyhole-0.15.1]#
```

Seems like everything is working but I am curious about those issues. Keep in mind I am on arch linux so it isn't a tested architecture.

**Comment by gboudreau** [comment]
`build_vfs.sh` should leave a `gh_vfs_build.log` file in the `/usr/share/greyhole/vfs-build/samba-4.13.2` folder.
Maybe look in there for the error that would cause the compilation to fail.

For the WARN on start, could you run this and paste here what you get:
`ldd /usr/lib/samba/vfs/greyhole.so`
