### ISSUE TITLE
Notifications via Webhooks

### ISSUE THREAD

**Issue by davidbugi** [gboudreau/Greyhole#250]
Rather than just via e-mail, can you add support for webhooks in notifications such as for Slack.

**Comment by gboudreau** [comment]
There are hooks available : https://github.com/gboudreau/Greyhole/blob/master/greyhole.example.conf#L283
Not sure they cover all emails sent though. I'll have a look.

**Comment by gboudreau** [comment]
I added a new hook just for emails in 0.15.2.

To try it:
- Upgrade to 0.15.2
- Add this line in your greyhole.conf:
  `hook[email] = /usr/share/greyhole/scripts-examples/greyhole_sysadmin_notification.sh`
- Restart the daemon
- Edit the `greyhole_sysadmin_notification.sh` script to do whatever you want with the received parameters (`SUBJECT` and `BODY`)
- To try it, run `greyhole --fsck --email-report --dir=/path/to/a/small/folder/on/a/share/lz`

**Comment by davidbugi** [comment]
Thank you!
