### ISSUE TITLE
Greyhole Daemon Not Running

### ISSUE THREAD

**Issue by crl0901** [gboudreau/Greyhole#258]
I'm having issues getting the Greyhole daemon to run.  I'm not sure when it stopped working, I only noticed today because my root volume filled up as Greyhole wasn't processing any of the incoming files.  Restarting it manually doesn't seem to work.  I don't see anything in the `greyhole.log` but I do see a lot of errors in the `log.smbd`:

    mkdir: cannot create directory ‘/var/cache/greyhole-dfree’: Permission denied

`greyhole --status` gives me:

    Greyhole daemon is currently stopped.

What should I check?

EDIT: So running the daemon manually with 'greyhole --daemon' at least gets it to run so that it'll start processing files.  Would this be an issue with the service file maybe?

**Comment by crl0901** [comment]
[root@talos var]# mkdir -p /var/cache/greyhole-dfree && chmod 777 /var/cache/greyhole-dfree
[root@talos var]# /usr/bin/greyhole --create-mem-spool
The in-memory spool folder is now correctly mounted and ready to be used by the Samba VFS module.
[root@talos var]# systemctl restart greyhole
[root@talos var]# greyhole --status

Greyhole daemon is currently stopped.

**Comment by gboudreau** [comment]
Were you able to resolve this issue?
Did you try to reboot?
If `/usr/bin/greyhole --daemon` works, and `systemctl restart greyhole` doesn't, the only thing I can see that would prevent the service from starting would be that `/usr/bin/greyhole --test-config` returns non-zero (i.e. an error), or there is already another `--daemon` process running.
Also, maybe look at `journalctl -u greyhole` after issuing the `systemctl restart greyhole` command. That could give you an idea on why the service is not starting.

**Comment by crl0901** [comment]
Nah, haven't been able to resolve it.  I did reboot, but that didn't resolve anything.  The systemd log doesn't seem to have any errors.  Here's the output of various commands that I've ran to troubleshoot this.

[root@talos ~]# /usr/bin/greyhole --test-config
Config is OK

[root@talos ~]# journalctl -u greyhole
-- Logs begin at Sat 2021-02-06 10:27:44 EST, end at Sat 2021-02-06 10:33:01 EST. --
Feb 06 10:28:28 talos systemd[1]: Starting LSB: Starts the Greyhole daemon....
Feb 06 10:28:30 talos greyhole[2196]: Starting Greyhole ... nice: invalid adjustment ‘false’
Feb 06 10:28:30 talos greyhole[2196]: [17B blob data]
Feb 06 10:28:31 talos systemd[1]: Started LSB: Starts the Greyhole daemon..

[root@talos ~]# systemctl status greyhole
● greyhole.service - LSB: Starts the Greyhole daemon.
   Loaded: loaded (/etc/rc.d/init.d/greyhole; bad; vendor preset: disabled)
   Active: active (exited) since Sat 2021-02-06 10:30:05 EST; 3min 44s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3103 ExecStop=/etc/rc.d/init.d/greyhole stop (code=exited, status=0/SUCCESS)
  Process: 3150 ExecStart=/etc/rc.d/init.d/greyhole start (code=exited, status=0/SUCCESS)
Feb 06 10:30:03 talos systemd[1]: Starting LSB: Starts the Greyhole daemon....
Feb 06 10:30:04 talos greyhole[3150]: Starting Greyhole ... nice: invalid adjustment ‘false’
Feb 06 10:30:04 talos greyhole[3150]: [17B blob data]
Feb 06 10:30:05 talos systemd[1]: Started LSB: Starts the Greyhole daemon..

[root@talos ~]# ps -ef | grep greyhole
root      1542  1541  0 10:35 ?        00:00:00 /bin/sh -c  /usr/bin/greyhole --process-spool --keepalive >/dev/null
root      1543  1542  0 10:35 ?        00:00:00 /bin/bash /usr/bin/greyhole-php /usr/bin/greyhole --process-spool --keepalive
root      1555  1543  3 10:35 ?        00:00:00 /usr/bin/php /usr/bin/greyhole --process-spool --keepalive

[root@talos ~]# greyhole --status
Greyhole daemon is currently stopped.

Filesystems look fine.  I'm not really sure what else to check.

**Comment by gboudreau** [comment]
I would think this would be the problem:
```
Starting Greyhole ... nice: invalid adjustment ‘false’
```

The `nice` level to use is obtained using `greyhole --config daemon_niceness`, which checks in your `greyhole.conf` for the `daemon_niceness` value. I would guess that command returns `false` instead of a number, and since `nice -n false` is not valid, the service fails to start.

I'll publish a fix soon.

**Comment by gboudreau** [comment]
Version 0.15.3 should resolve your issue. You can upgrade using your package manager.

**Comment by crl0901** [comment]
Something is weird with the repo, getting 404 errors when I try to update.

(3/10): epel/x86_64/updateinfo                                                                                                                                    | 1.0 MB  00:00:00     
greyhole/x86_64/primary_db     FAILED                                          
http://www.greyhole.net/releases/rpm/x86_64/repodata/6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found-:-- ETA 
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

(4/10): extras/7/x86_64/primary_db                                                                                                                                | 222 kB  00:00:00     
(5/10): epel/x86_64/primary_db                                                                                                                                    | 6.9 MB  00:00:00     
(6/10): remi-php74/primary_db                                                                                                                                     | 229 kB  00:00:00     
(7/10): updates/7/x86_64/primary_db                                                                                                                               | 5.6 MB  00:00:00     
(8/10): remi-safe/primary_db                                                                                                                                      | 1.9 MB  00:00:01     
(9/10): base/7/x86_64/primary_db                                                                                                                                  | 6.1 MB  00:00:02     
greyhole/x86_64/primary_db     FAILED                                          
http://www.greyhole.net/releases/rpm/x86_64/repodata/6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found-:-- ETA 
Trying other mirror.
http://www.greyhole.net/releases/rpm/x86_64/repodata/6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (Greyhole Repo),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=greyhole ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable greyhole
        or
            subscription-manager repos --disable=greyhole

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=greyhole.skip_if_unavailable=true

failure: repodata/6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3-primary.sqlite.bz2 from greyhole: [Errno 256] No more mirrors to try.
http://www.greyhole.net/releases/rpm/x86_64/repodata/6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found

**Comment by gboudreau** [comment]
Your yum cached metadata seems out of date. The repo doesn't refer to `6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3` : https://www.greyhole.net/releases/rpm/x86_64/repodata/repomd.xml
The checksum I see there for `primary.sqlite.bz2` is `5b58218fe857f4a04bd25be070c4b7a9637f86982166e80026b5c5b27f63d448`

Maybe a `yum clean all` will fix your issue?

**Comment by crl0901** [comment]
Yeah, tried that and tried manually remove /var/cache/yum.  I also tried reinstalling the repo.  Hm, I'll poke around some more.

**Comment by crl0901** [comment]
Actually, looking at the repomd.xml, it's still referring to 6450eb9173e9082119aae4f39cd2d9128c685c0a921640267f3e6b92773ec0c3

**Comment by gboudreau** [comment]
Ah. You're getting an old version of `repomd.xml`
I guess CloudFlare cached the old version. I'll see how I can tell it to not cache this file.
You should see the correct version now.

**Comment by crl0901** [comment]
Yup, that did it, all working now.  Thanks for the help!
