### ISSUE TITLE
Potential Web UI Bugs

### ISSUE THREAD

**Issue by modem7** [gboudreau/Greyhole#261]
Loving the UI at the moment! 

I found 3 potential bugs/things that may need to be addressed in future.

1. The donate field doesn't seem to keep the email that you've entered. The field becomes blank once you reload. 
2. Greyhole config > "Database Connexion" is misspelt. Should be "Connection"
3. Emails, would it be worthwhile having a way to enter SMTP server info for newbies rather than relying on setting up an MTA?

**Comment by gboudreau** [comment]
1. Indeed, there was a Javascript error in the function that should save it.
2. Yep.
3. Maybe. I'll look into how complicated that would be.

**Comment by modem7** [comment]
Having had more of a play with the UI, (it's pretty awesome!), found a couple of things that may be useful as suggestions/reports:

In the Samba shares tab, we see the pie chart as follows:

![image](https://user-images.githubusercontent.com/4349962/111039508-57b47500-8426-11eb-927c-2f67efd00753.png)

But in the Storage pool tab, the pie chart seems to be lower:

![image](https://user-images.githubusercontent.com/4349962/111039527-6ef36280-8426-11eb-8f52-52ef3f0c9c1e.png)

Unsure if this is intentional at all? 

Would it also be possible to have an --iostat tab at all? Would be potentially useful to see what speeds drives are operating at/which drives are active at a glance (especially during balances/fscks)

**Comment by gboudreau** [comment]
Thx for the suggestions. Will look into those when I got some free time.
