### ISSUE TITLE
Issues with file permissions from migration install

### ISSUE THREAD

**Issue by modem7** [gboudreau/Greyhole#262]
Heya,
 
I've just migrated from Amahi (Fedora install) to Ubuntu 20.04.
 
I'm trying to get all folder and file permissions sorted out with the migration but Docker apps and Windows shares are having issues modifying things inside /mnt/samba.
 
I *think* I've read and done the information located here:
https://github.com/gboudreau/Greyhole/wiki/Permissions-Data-Drives, https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally and https://superuser.com/questions/1248077/why-cant-other-users-see-the-files-i-post-to-samba-share/1248235
 
But still no go.

Things directly pointed to the share mount seem to work with no issues.

I've run the support script as well just in case:
http://ix.io/2Rft

This is what occurs when I try to delete using sudo on /mnt/samba.

![gh perm issue1](https://user-images.githubusercontent.com/4349962/109671866-5d7ba200-7b6c-11eb-8c87-aeaa2d127fd8.jpg)

![gh perm issue2](https://user-images.githubusercontent.com/4349962/109671868-5d7ba200-7b6c-11eb-9357-f48cc922b1c9.jpg)

![gh perm issue3](https://user-images.githubusercontent.com/4349962/109671870-5e143880-7b6c-11eb-8036-64b54a4ede7c.jpg)

![gh perm issue4](https://user-images.githubusercontent.com/4349962/109671865-5ce30b80-7b6c-11eb-9ce4-643a8ef0741c.jpg)

I'm not quite sure where I've screwed up in the migration and any help would be fantastic. I suspect a permissions issue, but my knowledge of Linux permissions is scarce at best.

**Comment by gboudreau** [comment]
The lost.mkv file on your share points to a file copy on drive6, not drive5. Check permissions on drive6.
You can also run simple tests, like creating a new file in the same folder, using /mnt/samba, and checking what permission and ownership it gets, and see how that differs from the existing file(s) you can't delete.

For docker apps, your issue is most probably that the IDs of the users used inside the containers are not the same as the ones on the host. eg. if you have a software running as alex in a container, tat user might be UID 500, so when that software tries to access files owned by alex on the host (UID 1000), the UIDs differ, and thus it won't work.
You need to ensure your docker apps are running using a UID or GID that has access to the /mnt/samba folders & files.
To debug, you can connect to the container using `docker exec`, check the UID used to run the process in question, then compare that with the owner of the folder in question inside /mnt/samba, still as seen from inside the container.

**Comment by modem7** [comment]
Thanks for the quick reply! 

I created a test.txt file via windows share and got the following:

![image](https://user-images.githubusercontent.com/4349962/109745220-72d3e900-7bcb-11eb-9aad-37f82f807432.png)

With Docker, I've set the UID and GID to Alex:Docker group (which the user is also part of).
uid=1000(alex) gid=100(users) groups=100(users),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd),997(docker)

If I try to create a file via ssh I get the following:
![image](https://user-images.githubusercontent.com/4349962/109745460-cf370880-7bcb-11eb-81ed-79518424f758.png)

**Comment by gboudreau** [comment]
Not sure why you have `wide links = No` in each share's config... I would remove that.
Also, `unix extensions = yes`, try `no` there.
Then I would try a higher value in `log level`, and `tail -f` the samba logs, while reproducing a permission denied error; the samba logs should tell you more on what is happening.

**Comment by modem7** [comment]
Looks like it was the widelinks/unix extensions

I had previously recreated all of Samba shares (with widelinks = no enabled at the time), so it looks like it didn't take those out. 

Thank you very much! 

As an aside, is there any way of increasing copying performance? It seems a bit slow compared to Fedora - unsure if that's a Ubuntu thing? Unsure if you've come across a similar issue?

**Comment by gboudreau** [comment]
To debug speed issues, I would try to reproduce the problem with the "smallest" possible use-case.
For example, try to write a file using `dd`, directly onto the landing-zone, then onto the equivalent `/mnt/samba` folder, and see how fast it is. If that works as expected on the host, try the same in a docker container.

```bash
file=/opt/samba-shares/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=100 ; rm "$file"
file=/mnt/samba/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=100 ; rm "$file"
```

On my server, I get:
```
gb@fileserver5:~ $ file=/opt/samba-shares/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=200 ; rm "$file"
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 1.18998 s, 176 MB/s
------------------------------------------------------------------------------------------------------------------------------------------------------- 08:34:34
gb@fileserver5:~ $ file=/mnt/samba/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=200 ; rm "$file"
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 1.44933 s, 145 MB/s
------------------------------------------------------------------------------------------------------------------------------------------------------- 08:34:40
gb@fileserver5:~ $ file=/opt/samba-shares/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=200 ; rm "$file"
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 1.20057 s, 175 MB/s
------------------------------------------------------------------------------------------------------------------------------------------------------- 08:34:46
gb@fileserver5:~ $ file=/mnt/samba/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=200 ; rm "$file"
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 1.4333 s, 146 MB/s
------------------------------------------------------------------------------------------------------------------------------------------------------- 08:34:49
gb@fileserver5:~ $ file=/opt/samba-shares/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=200 ; rm "$file"
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 1.23461 s, 170 MB/s
------------------------------------------------------------------------------------------------------------------------------------------------------- 08:35:06
gb@fileserver5:~ $ file=/mnt/samba/GreyholeTests/file1 ; dd if=/dev/zero of="$file" conv=fdatasync bs=1M count=200 ; rm "$file"
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 1.43721 s, 146 MB/s
```

You can also monitor your system while it is copying a large file slowly. I myself use `nmon` for that :
```bash
apt install nmon
echo ldt. | nmon # monitor CPU [l]ong-term, [d]isk and [t]op
```

That should highlight if a disk is saturated, or if the CPU is busy.

**Comment by modem7** [comment]
Ahhah! Thank you for the above, I would have had no idea how to test this! 

This is what I'm getting currently (losing around 100MB/s on average): 

![image](https://user-images.githubusercontent.com/4349962/109824892-2cb17080-7c31-11eb-89ee-016e61d0d50f.png)

and via Docker, we see roughly the same as the /mnt/samba:

![image](https://user-images.githubusercontent.com/4349962/109825010-4d79c600-7c31-11eb-911b-2ad9f1dbc499.png)

Is there any way to set cache=none using the automount script for testing?

**Comment by modem7** [comment]
Closing due to age. I haven't really had a look at it since my last comment.
