### ISSUE TITLE
Lost OS - Wanting to rebuild (advice on approach needed)

### ISSUE THREAD

**Issue by old-square-eyes** [gboudreau/Greyhole#264]
I can't boot off the OMV OS flash drive that greyhole was working symbiotically on in the background. It took me a long time to configure originally... so I know I'm in for a big job.

I have a clone/backup of the USB, and can even boot to Debian after tweaking a newly created USB with boot-repair, and a manual grub boot. But this is on another laptop.

I have tried for days to get this backup booting on my NAS... but some funny business with GPT/UEFI and the motherboard and it just will not work - the mobo refuses to acknowledge it's bootable media :(

Ideally I'd just get this backup restored and carry on with my life. But...

Since I can't seem to do that, I have installed a fresh OMV on another USB, and it boots fine (proving motherboard/bios settings are fine).

What is the best way forward with greyhole? Should I recover my Maria DB (where would I start with that)... or reinstall Greyhole and hope the fsck makes sense of where all the files are (do I need to pause first then hook everything up via config)? I have 5 drives in the array, and the landing zone is on the largest. It "listens" to OMV Samba folders, and OMV is used to mount the drives.

I have a backup of my greyhole config and screenshots of my old OMV config.

**Comment by old-square-eyes** [comment]
Actually, in an amazing turn... I was able to get the restored backup booting on my NAS. First I had to flash the bios, then boot-repair (which had been giving me vram errors) allowed me to progress on that machine. Boot-repair asked me to make tiny unformatted grub boot partition. It worked its magic and I was able to boot into debian. I had a kernel panick first, so booted into advanced mode and selected an older version (is it an older kernel?) and then it booted. I'm now updating.

I haven't reconnected my drioves, but the OMV admin page is on my network, which is a good sign.

**Comment by old-square-eyes** [comment]
Still getting bootloops on 5.10 with "No init found. Try passing init=bootarg." I can still boot into 5.7, but I don't know what that means really. 5.10 is the default, and I have to manually intervente to get up and running.

Is there a tutorial on how to rebuild Greyhole if I have to go with a clean install?

**Comment by gboudreau** [comment]
Here's the wiki page about using your Greyhole storage pool on another OS install : https://github.com/gboudreau/Greyhole/wiki/ReuseStoragePool

**Comment by old-square-eyes** [comment]
I'm permanently booting off 5.7 now, and things seem quite stable. I saw another user on OMV having similar issues with 5.10... so am going to assume it's unrelated to my recovery process.

Can't beleive I'm back up and running. Thanks for the link... I'll read through as I'll probably rebuild this thing at some point (hopefully later , rather than sooner).
