### ISSUE TITLE
Is the Wiki out of date regarding support options?

### ISSUE THREAD

**Issue by POTSandSTOP** [gboudreau/Greyhole#266]
According to [this Greyhole Wiki link](https://github.com/gboudreau/Greyhole/wiki/GetHelp#support-channels), FreshDesk is an option for Greyhole issues. It's been a couple of weeks since I posted there ("remove operation stuck on a filename") but I haven't received a reply. I like using FreshDesk because I don't have to be concerned about posting logs that could have personal info vs. logs posted here which are public.

I could use some help because it's in an infinite loop.

Help?

**Comment by gboudreau** [comment]
Freshdesk is still an option, but I sometimes have other priorities, or miss the notifications for new tickets, or something.
You can post updates on the ticket every week or so, if you still haven't heard back, and still have the issue.

Me being the only person with access to Freshdesk, you're kind of limiting your support options by using that, vs a [discussion](https://github.com/gboudreau/Greyhole/discussions) or issue on Github.
