### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'greyhole'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by mm04926412** [gboudreau/Greyhole#269]
I just installed greyhole fresh and this error keeps popping up no matter what I try to do. The daemon won't start. Am I missing dependancies?

**Comment by gboudreau** [comment]
That error is the MySQL server telling you the username-password provided (from /etc/greyhole.conf) is not valid.
Did you complete step 3 of the [USAGE](https://github.com/gboudreau/Greyhole/blob/master/USAGE) instructions?

In particular:

```bash
mysql -u root -p -e "CREATE DATABASE IF NOT EXISTS greyhole; CREATE USER IF NOT EXISTS greyhole_user@localhost IDENTIFIED BY '89y63jdwe'; GRANT ALL ON greyhole.* TO greyhole_user@localhost;"
mysql -u greyhole_user -p89y63jdwe greyhole < /usr/share/greyhole/schema-mysql.sql
```

**Comment by mm04926412** [comment]
This is confusing to me. The language of the usage document seemed to suggest that I can either use the web based wizard OR I can follow the steps below? Is it a must that I follow the terminal steps?

**Comment by mm04926412** [comment]
Ah ok my fault for some reason I had a bit of a blind spot for the /install part of the web setup. My apologies!
