### ISSUE TITLE
Move or Delete Leave Remnant Files and Folders

### ISSUE THREAD

**Issue by sampper** [gboudreau/Greyhole#271]
When I want to delete or move a file they are not processed correctly.

For example I delete LZ files/a
hdd0/gh/files/a remain

example 2
Move LZ folder files/b to files/c/b
hdd1/gh/files/b remain

at first this does not cause any effect but when I run greyhole fsck it recovers the files I wanted to delete and also cancels the move operations.

files/a and files/b return and files/c folder is empty.

I have configured something wrong?

**Comment by gboudreau** [comment]
Are you modifying those files directly in the LZ?
You should not do that.
All file modifications need to occur through Samba.
On your local server, you need to mount your Samba shares locally, and always access your files through those, never directly on the LZ.
Ref: https://github.com/gboudreau/Greyhole/wiki/MountSharesLocally

**Comment by sampper** [comment]
The files are created, moved and deleted through Samba from a Windows PC. Only fsck is run locally.

I am running Fedora fc33, greyhole, version 0.15.7, for linux-gnu (noarch)

**Comment by gboudreau** [comment]
Try to move or delete files, and see if anything appears in the greyhole daemon log.

Please run this : https://github.com/gboudreau/Greyhole/wiki/GetHelp#gather-system-information
And indicate which share you test with.

**Comment by sampper** [comment]
Vfs objects entries have disappeared from my smb.conf. Must have happened when I upgraded the distro as I had configured the smb.conf and everything was working previously. One share has "vfs objects = " and rest of them not even that. Have to keep eyes on that.

Thank you for the quick reply, I noticed the problem on the generated debug info.
