### ISSUE TITLE
PHP Exception

### ISSUE THREAD

**Issue by bigfoot65** [gboudreau/Greyhole#272]
Hello,

I just started receiving this error today:

May 12 17:21:01 ERROR read_smb_spool: PHP Fatal Error: Uncaught Exception: SQLST
ATE[22007] Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x93\x
9D s...' for column 'full_path' at row 1 in /usr/bin/greyhole:719
Stack trace:
#0 /usr/bin/greyhole(723): DB::execute('INSERT INTO tas...', Array)
#1 /usr/bin/greyhole(3204): DB::insert('INSERT INTO tas...', Array)
#2 /usr/bin/greyhole(4512): DBSpool->insert('unlink', 'Apollo', 'Favorites/Links
...', NULL, NULL)
#3 /usr/bin/greyhole(7701): SambaSpool::parse_samba_spool()
#4 /usr/bin/greyhole(8417): ProcessSpoolCliRunner->run()
#5 {main}
  thrown; BT: greyhole[L719]

I have removed the database and reinstalled  it but still not working.  I don't know where the Farvorites./Links is coming from as I removed that folder from the share.

Any guidance would be greatly appreciated.

**Comment by gboudreau** [comment]
It's having issues inserting into MySQL some info about a delete file operation; its getting that from a file in `/var/spool/greyhole/`
Could you grep all the files in that folder for `Apollo` maybe, or `Favorites/Links` (or both), to try to look for the file operation that is causing issues?
If you find multiple files, you could zip/gzip them up, and attach them here.
(They should only contain file and dir names, so unless that could be sensitive info for you, you should be fine.)

**Comment by bigfoot65** [comment]
Here you go.

[upload.zip](https://github.com/gboudreau/Greyhole/files/6469806/upload.zip)
[list.txt](https://github.com/gboudreau/Greyhole/files/6469807/list.txt)

**Comment by gboudreau** [comment]
1620861501223620:
```
unlink
Apollo
Favorites/Links/Other/mthenw frontail  📝 streaming logs to the browser.URL
```

emojis in filenames...
The `tasks` (and `tasks_completed`) table is encoded as UTF-8, which doesn't support emojis. You'd need to change those tables `full_path` column to be encoded as utf8_mb4 for emojis to be supported.

Removing the `/var/spool/greyhole/1620861501223620` file should resolve this issue.

**Comment by bigfoot65** [comment]
Thanks!  I did as you instructed and works perfectly.

I tired to change the column as you stated and it won't let me.  Says "Specified key was too long; max key length is 1000 bytes" so guess I'll leave it alone.

I have since removed that folder from my share.

Thanks for your assistance and quick response!

**Comment by sampper** [comment]
I ran into same problem, emojis in names block greyhole.

Also got max key length error when modifying tasks table.
I was able to change the tasks table full_path column to utf8_mb4 after changing the engine from MyISAM to InnoDB.

ALTER TABLE tasks ENGINE=InnoDB;
