### ISSUE TITLE
Share is locked...

### ISSUE THREAD

**Issue by uSlackr** [gboudreau/Greyhole#273]
for a couple days now, all I see in the log are "share is locked" messages.  The queue is jammed up

```
Share | Write | Delete | Rename | Check
Docs | 514588 | 162748 | 20946 | 0
```

I restarted the service and the machine.  As you can see from the file names I'd made the mistake of putting prometheus data files on a share.  I've since moved the data files to local disk and _removed these files from the LZ_ (which I'm sure was a bad idea, but I had to try something.  

should I clear the queue and run a fsck to rebuild the shares?
```
May 29 19:54:29 write: Now working on task ID 3695760: write Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/index_tmp_p
May 29 19:54:29 write: Share is locked because another file operation is waiting for a file handle to be released. Skipping.
May 29 19:54:29 write: Now working on task ID 3695761: write Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/index_tmp_po
May 29 19:54:29 write: Share is locked because another file operation is waiting for a file handle to be released. Skipping.
May 29 19:54:29 write: Now working on task ID 3695762: write Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/chunks/000001.tmp
May 29 19:54:29 write: Share is locked because another file operation is waiting for a file handle to be released. Skipping.
May 29 19:54:29 rename: Now working on task ID 3695763: rename Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/chunks/000001.tmp -> Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/chunks/000001
```

**Comment by gboudreau** [comment]
What is the first log lines that appear, after the daemon sleeps. The log lines you show above is just telling you another file operation is causing the share to be locked. The first operation the daemon tries to execute, after sleeping, should give a different error message.
I would guess it is caused by a file operation still marked as pending in MySQL, but I could confirm it with the appropriate logs.

**Comment by uSlackr** [comment]
Here is a section of log before/after sleep


May 29 21:37:12 INFO rmdir: Now working on task ID 3695766: rmdir Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/chunks
May 29 21:37:12 INFO rmdir:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
**May 29 21:37:19 DEBUG sleep: Nothing to do... Sleeping.**
May 29 21:37:29 INFO write: Now working on task ID 3695747: write Docs/docker/config/swag/config/log/nginx/error.log
May 29 21:37:29 INFO write: File created: Docs/docker/config/swag/config/log/nginx/error.log - 1.72MB
May 29 21:37:29 DEBUG write: Loading metafiles for Docs/docker/config/swag/config/log/nginx/error.log ...
May 29 21:37:29 DEBUG write:   Got 0 metadata files.
May 29 21:37:29 DEBUG write: 0 metafiles loaded.
May 29 21:37:29 DEBUG write:   File Docs/docker/config/swag/config/log/nginx/error.log is locked by another process (smbd, PID 3605). Will wait until it's unlocked to work on any file in this share.
May 29 21:37:29 INFO write: Now working on task ID 3695748: write Docs/docker/config/swag/config/log/nginx/access.log
May 29 21:37:29 INFO write:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.

**Comment by uSlackr** [comment]
clicked the wrong button

**Comment by uSlackr** [comment]
here's another section
May 29 21:49:52 INFO rmdir: Now working on task ID 3695766: rmdir Docs/docker/config/prometheus/data/data/01F5PTQ54SKH3MS1Z357F9646H.tmp-for-creation/chunks
May 29 21:49:52 INFO rmdir:   Share is locked because another file operation is waiting for a file handle to be released. Skipping.
**May 29 21:49:59 DEBUG sleep: Nothing to do... Sleeping.**
May 29 21:50:01 DEBUG read_smb_spool: Processing Samba spool...
May 29 21:50:09 INFO write: Now working on task ID 3695747: write Docs/docker/config/swag/config/log/nginx/error.log
May 29 21:50:09 INFO write: File created: Docs/docker/config/swag/config/log/nginx/error.log - 1.72MB
May 29 21:50:09 DEBUG write: Loading metafiles for Docs/docker/config/swag/config/log/nginx/error.log ...
May 29 21:50:09 DEBUG write:   Got 0 metadata files.
May 29 21:50:09 DEBUG write: 0 metafiles loaded.
May 29 21:50:10 DEBUG write:   File Docs/docker/config/swag/config/log/nginx/error.log is locked by another process (smbd, PID 3605). Will wait until it's unlocked to work on any file in this share.

**Comment by gboudreau** [comment]
The lock looks legit.
```
DEBUG write: File Docs/docker/config/swag/config/log/nginx/error.log is locked by another process (smbd, PID 3605). Will wait until it's unlocked to work on any file in this share.
```
Are you running a nginx server that has its error.log on a Greyhole share..?
Pretty sure nginx could open the log files it needs in write mode, and keep the file handle opened, preventing Greyhole from being able to work on this and all future file operations on this share.
Try to stop Samba, and check that the Greyhole daemon is able to continue working on those file operations then.

**Comment by uSlackr** [comment]
I stopped the services writing to the share and it cleared up overnight.

Share	Write	Delete	Rename	Check
Total	0	0	0	0


Thank you!
