### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by modem7** [gboudreau/Greyhole#274]
OS: Ubuntu 20.04

Intermittently, I get the an issue where my locally mounted shares (done via the script) become temporarily unavailable.

![image](https://user-images.githubusercontent.com/4349962/127198096-16408a72-cfe2-4970-befa-b8fc940d8304.png)

This happens quite often post reboots, but also sometimes occurs during standard operations. 

![image](https://user-images.githubusercontent.com/4349962/127198249-bab2959f-7e7f-4dfb-b67b-8c5592a8d331.png)

I've also done: 
`The solution is simply to make sure that the service is stopped (sudo service mount_shares_locally stop or similar), and then to delete the /mnt/samba directory and all it's contents (sudo rmdir /mnt/samba/*). When the service is restarted, everything will mount normally without any issues.`

A few times over the last couple of months to see if it resolved. 

This can play havoc with Docker at times. But I'm unsure where to start looking to investigate this. 

I did not have this particular problem with Fedora, so this behaviour is quite new to me.

**Comment by gboudreau** [comment]
I sometimes have a similar, when Samba restarts / is restarted, as this doesn't re-mount the locally mounted shares. But that gives me a different error (on Debian):

```
gb@fileserver5:~ $ ls -l /mnt/samba/GreyholeTests/
total 0
drwxrwxr-x 2 gb users 0 May 13 20:20 emoji-dir
------------------------------------------------------------------------------------------------------------------------------------------------------- 16:32:49
gb@fileserver5:~ $ sudo systemctl restart samba-greyhole
------------------------------------------------------------------------------------------------------------------------------------------------------- 16:40:15
gb@fileserver5:~ $ ls -l /mnt/samba/GreyholeTests/
ls: cannot access '/mnt/samba/GreyholeTests/': Bad file descriptor
------------------------------------------------------------------------------------------------------------------------------------------------------- 16:40:37
gb@fileserver5:~ $ sudo systemctl restart mount-shares-locally
------------------------------------------------------------------------------------------------------------------------------------------------------- 16:41:04
gb@fileserver5:~ $ ls -l /mnt/samba/GreyholeTests/
total 0
drwxrwxr-x 2 gb users 0 May 13 20:20 emoji-dir
```

Restarting the `mount_shares_locally` script/service doesn't help you?

Also, when this happens, remotely accessing your shares still works? i.e. this is just a problem with your local (CIFS) mounts, and not Samba?

**Comment by modem7** [comment]
Heya, 

Yupper, only CIFS in this case. Samba works perfectly. 

Restarting the script doesn't always help (sometimes it does, but it's intermittent again). 

When it next happens (unfortunately I can't reproduce manually), I can see if there's anything in /var/logs that might be able to give us a further clue.

**Comment by modem7** [comment]
Let's close this for now, the issue hasn't seemed to have materialised again. 

I'll create a new issue if it does!
