### ISSUE TITLE
Spool not processing

### ISSUE THREAD

**Issue by modem7** [gboudreau/Greyhole#286]
Heya, me again! 

I've currently got Greyhole installed on Ubuntu, and for some reason the spool isn't processing. 

![image](https://user-images.githubusercontent.com/4349962/145257123-97e6315d-0bf8-4d88-bd18-6a0dd88abf7c.png)

I've also tried to do `sudo mv /var/spool/greyhole /var/spool/greyhole.bak && sudo mkdir -p /var/spool/greyhole && sudo chmod 777 /var/spool/greyhole && sudo /usr/bin/greyhole --create-mem-spool && sudo service greyhole restart && sudo greyhole --fsck` but to no avail. It just sits on "sleep: Nothing to do... Sleeping."

A fsck deals with things that are in the spool, but then it rises up again. 

Version 0.15.10.

Process spool cron job is also running with no issues from what I can see.

![image](https://user-images.githubusercontent.com/4349962/145258710-9372f9a6-885e-443e-9e35-5c50ae9dc61c.png)

**Comment by modem7** [comment]
Heya, 

Yupper! Tried empty spool (had to clear it again today, 5M this time (usually maxes out if/when it happens which isn't surprising).

Usually when the spool is empty, and everything has been processed as intended, the timings of the log lines are pretty good at 10s. 

`--view-queue` can also take a long time to come up if the spool is large as well. 

I've actually got another one building up as we speak (from a fresh spool as of ~20:00/20:30.

![image](https://user-images.githubusercontent.com/4349962/145477071-358428bc-aed3-40bd-bbc9-e11765b6f449.png)

Time this SS was taken was 21:18.

**Comment by gboudreau** [comment]
There should be a log `Processing Samba spool...` when spool processing starts, either from `--process-spool`, or in the daemon.

If you don't see this log, I see two options : 
- the lock can't be obtained. Try to edit `/usr/bin/greyhole`, to add a log if this happens:

```diff
              chmod('/var/spool/greyhole/mem', 0777);
          }
          if (!DB::acquireLock(ACTION_READ_SAMBA_POOL, 5)) {
+             Log::debug("Processing Samba spool failed. Couldn't acquire DB lock. :(");
              return;
          }
          $new_tasks = 0;
```

- The `find` command used to list spooled files somehow fails. Try to run it manually:

```bash
find -L /var/spool/greyhole -type f -printf "%T@ %p\n" | sort -n | head -n 10000
```

**Comment by modem7** [comment]
Results from `find -L /var/spool/greyhole -type f -printf "%T@ %p\n" | sort -n | head -n 10000`
[spool.txt](https://github.com/gboudreau/Greyhole/files/7688729/spool.txt)

And looks like you've nailed it:
![image](https://user-images.githubusercontent.com/4349962/145482845-6a9d8e32-088d-4d4c-a4ad-4d3a66ca3d93.png)

**Comment by gboudreau** [comment]
It's normal for the daemon to to not be able to acquire the lock, if there is a currently running `--process-spool` process.
This lock is required to prevent two processes from trying to process the spool.
Try to remove the cron that runs `--process-spool`, verify it's not running anymore with `ps`, then check the daemon log.

**Comment by modem7** [comment]
Before disabling the cron job:

![image](https://user-images.githubusercontent.com/4349962/145489911-acedf72d-b517-4fe5-a7da-babc68e08262.png)

After:

![image](https://user-images.githubusercontent.com/4349962/145489944-4fb2c9c5-86f9-4bdb-8aed-03fa4625ed1a.png)

Certainly looks better! Is it worthwhile just keeping that cron job disabled?

**Comment by gboudreau** [comment]
You could, but the cron file is not considered a config file, and thus is overwritten on update.
You could try disabling the daemon, and running `greyhole --process-spool` manually. It should process the spool like the daemon does.
Also try `greyhole --process-spool --keepalive` which should process the spool almost instantly when a new, spool file appears, for up to a minute, before dying.

**Comment by modem7** [comment]
Sweet. 

We'll leave it as is for now with the manual workarounds if need be, and go on from there!

If it still occurs in a future version, we can revisit.

Thank you once again!
