### ISSUE TITLE
logs in UTC

### ISSUE THREAD

**Issue by uSlackr** [gboudreau/Greyhole#288]
Any chance we could get greyhole logs to use the server timezone info vs UTC for the logs?

**Comment by gboudreau** [comment]
Here's how : https://github.com/gboudreau/Greyhole/blob/612106946a773ab193770e78f931ba84bccf6660/USAGE#L78

**Comment by uSlackr** [comment]
Thanks.  I already have this in the UI:
![image](https://user-images.githubusercontent.com/25751399/149221768-c2070ec0-44b0-4403-886a-7b67717c2e10.png)
and this is reflected in the conf file:

```
timezone = America/New_York
```

**Comment by gboudreau** [comment]
And is the issue only in the Web UI? Or is greyhole.log really not logging times in that TZ?

**Comment by uSlackr** [comment]
I cannot tell.  greyhole.log is currently 0 bytes.  The first zipped log greyhole.log.1.gz, has no entries past Jan 11 08:55:11.  Not sure where the log entries in the web UI are coming from.  FWIW, greyhole_err.log ends at the same time as the log.1 file.

Restarting greyhole service did not commit any entries to greyhole.log

**Comment by uSlackr** [comment]
I confirmed it is only an issue in the WebUI.

**Comment by gboudreau** [comment]
I think this would be due to your MySQL server having a different timezone than your Greyhole server...
I have a tentative fix (above).
You can add those lines in your `/usr/share/greyhole/web-app/index.php`, and restart your web UI process, to test this fix.

**Comment by uSlackr** [comment]
Seems to work.  I'll look at setting the mysql container to the correct tz.

![image](https://user-images.githubusercontent.com/25751399/149606127-a97b1d3b-abc5-4902-9ead-23f8858567ba.png)

**Comment by uSlackr** [comment]
And thank you!
