### ISSUE TITLE
scorecard analysis

### ISSUE THREAD

**Issue by laurentsimon** [gboudreau/Greyhole#289]
Hi

(I'm one of the maintainers of scorecard). I saw you created a file scorecards-analysis.yml.

I wanted to point out that the file needs to be created under `.github/workflows/` for GitHub to recognize it as a workflow to run. We'll update the documentation to make this clearer https://github.com/ossf/scorecard-action#installation

Ignore my comment if your intention was not to install scorecard and you only wanted to have a copy of the workflow on your repo.

**Comment by gboudreau** [comment]
Indeed, I used the button on Github.com to install, and I didn't look into where the file was being committed. Thx.
