### ISSUE TITLE
Log Error and --remove problem

### ISSUE THREAD

**Issue by mckinneyg** [gboudreau/Greyhole#291]
I have 2 issues that may be related.

1. Log Issue:
```
2. Feb 15 19:25:26 WARN read_smb_spool: PHP Warning [2]: Error while sending QUERY packet. PID=3169 in /usr/bin/greyhole on line 705; BT: greyhole[L8561] run() => greyhole[L7841] parse_samba_spool() => greyhole[L4381] acquireLock(read_smb_spool,5) => greyhole[L780] getFirstValue(SELECT GET_LOCK(:name, :timeout),array (  'name' => 'read_smb_spool',  'timeout' => 5,)) => greyhole[L737] getFirst(SELECT GET_LOCK(:name, :timeout),array (  'name' => 'read_smb_spool',  'timeout' => 5,)) => greyhole[L729] execute(SELECT GET_LOCK(:name, :timeout),array (  'name' => 'read_smb_spool',  'timeout' => 5,)) => greyhole[L705] execute()
Feb 15 19:25:26 ERROR read_smb_spool: PHP Fatal Error: Uncaught Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /usr/bin/greyhole:719
Stack trace:
#0 /usr/bin/greyhole(729): DB::execute('SELECT GET_LOCK...', Array)
#1 /usr/bin/greyhole(737): DB::getFirst('SELECT GET_LOCK...', Array)
#2 /usr/bin/greyhole(780): DB::getFirstValue('SELECT GET_LOCK...', Array)
#3 /usr/bin/greyhole(4381): DB::acquireLock('read_smb_spool', 5)
#4 /usr/bin/greyhole(7841): SambaSpool::parse_samba_spool()
#5 /usr/bin/greyhole(8561): ProcessSpoolCliRunner->run()
#6 {main}
  thrown; BT: greyhole[L719] 
```

2. When I execute `greyhole --remove=/var/hda/files/drives/Drive2/gh`, I get `Cannot establish connection to the host.`

**Comment by gboudreau** [comment]
Greyhole is (trying to) telling you that your MySQL server is not happy.
Look into your MySQL (or MariaDB) server; check the logs, try to restart it, etc.

**Comment by mckinneyg** [comment]
Restarting MariaDB seems to have stopped the errors in the logs.

But executing greyhole --remove=/var/hda/files/drives/Drive2/gh, is still resulting in "Cannot establish connection to the host." Any suggestions.

**Comment by gboudreau** [comment]
I don't think that error is from Greyhole. Googling a little, it seems to be an error returned when using Webmin to issue commands, and webmin can't for some reason connect to your server to send the commande. Or something along those lines.
Try other commands, like `greyhole -q` or `greyhole -s`, or even totally unrelated commands, like `php -v`.
