### ISSUE TITLE
Fresh install - What to do with simlinks / FSCK doesn't appear to run (WebUI)

### ISSUE THREAD

**Issue by old-square-eyes** [gboudreau/Greyhole#294]
I lost my OS :(

I reinstalled and got OMV up and running. I have recreated all my SAMBA shares in OMV on my NVMe (dedicated LZ), and they are recognised in the new web UI.

1. I have all my simlinks still there. Should I blow those away and let Greyhole rebuild? Or just FSCK? [This seems to imply I can leave the old simlinks](https://github.com/gboudreau/Greyhole/wiki/ReuseStoragePool) `This will take care of re-creating symlinks if needed`. "If needed". 
2. I tried the latter. FSCK doesn't seem to kick off - I get one entry in the logs shown below. Web UI keeps telling me `You will need to restart the Greyhole daemon for your changes to be effective.` I have done that. But the warning comes back. I have also rebooted the machine. Logs don't update in the web UI, when I start FSCK in the web UI it appears to start but no logs are tailed. SSH in, and tail logs shows nothing happening either. I see `Greyhole daemon is currently stopped` in the UI... but that is not the case as I see some arbitrary Greyhole SAMBA spool logs happening in CLI. Though no FSCK.

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/25760491/167269809-120e03f6-ab27-49d7-8222-7c56e74eed39.png">

<img width="622" alt="image" src="https://user-images.githubusercontent.com/25760491/167269828-b482c9ea-bba2-449c-a44b-9df5a0f22576.png">

**Comment by old-square-eyes** [comment]
I also another bug in the UI configuring Greyhole. On first run I only had the option to set number of copes to max. Then on returning to the UI I could choose the correct number for each SAMBA share.

**Comment by gboudreau** [comment]
> 1. I have all my simlinks still there. Should I blow those away and let Greyhole rebuild? Or just FSCK? [This seems to imply I can leave the old simlinks](https://github.com/gboudreau/Greyhole/wiki/ReuseStoragePool) `This will take care of re-creating symlinks if needed`. "If needed".

Just run `greyhole --fsck`  
Ref: https://github.com/gboudreau/Greyhole/wiki/ReuseStoragePool

> 2. I tried the latter. FSCK doesn't seem to kick off - I get one entry in the logs shown below. Web UI keeps telling me `You will need to restart the Greyhole daemon for your changes to be effective.` I have done that. But the warning comes back. I have also rebooted the machine. Logs don't update in the web UI, when I start FSCK in the web UI it appears to start but no logs are tailed. SSH in, and tail logs shows nothing happening either. I see `Greyhole daemon is currently stopped` in the UI... but that is not the case as I see some arbitrary Greyhole SAMBA spool logs happening in CLI. Though no FSCK.

`fsck` in run by the daemon, and your daemon is not running. Samba spool processing is executed using a cron job, so having just those lines logged means the cron runs, but not the daemon.
If you tail the log, and try to run the daemon, you should see new lines logged telling you why the daemon can't run.
Or you can try running `sudo greyhole --daemon` manually, see what happens.

**Comment by old-square-eyes** [comment]
`sudo greyhole --daemon` got things going

**Comment by old-square-eyes** [comment]
Oh dear. The FSCK seems to have filled up my gh drives. I'm sure I had plenty of space before. I guess I needed more to rebuild the pool?

![Imgur](https://i.imgur.com/yzVBvGt.jpg)

**Comment by old-square-eyes** [comment]
I opened up my NVMe LZ to the gh pool. FSCK is running, Fingers crossed.

**Comment by gboudreau** [comment]
fsck doesn't use temporary space - if it is using more space than before, it's because it is creating new file copies.
Look into the log, find when it created a new file copy, and check why.
Maybe it is working with a higher num_copies vs before, or it doesn't see all your pooled drives, and thus thinks some file copies are missing.

**Comment by old-square-eyes** [comment]
Seems a drive became disconnected and it was enough to push it over on the next FSCK. I will close this.
