### ISSUE TITLE
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

### ISSUE THREAD

**Issue by modem7** [gboudreau/Greyhole#301]
Heya, 

The installation script still seems to use apt-key, this is considered deprecated and will throw up warning messages every time one does an apt update in Ubuntu.

`W: https://www.greyhole.net/releases/deb/dists/stable/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

**Comment by modem7** [comment]
@gboudreau To resolve this easily, the following changes need to be made to https://github.com/gboudreau/Greyhole/blob/master/install-greyhole-package.sh#L146-L147

```
echo "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/greyhole-archive-keyring.gpg] https://www.greyhole.net/releases/deb stable main previous before-previous" > /etc/apt/sources.list.d/greyhole.list
curl -fsSL https://www.greyhole.net/releases/deb/greyhole-debsig.asc | sudo gpg --dearmor -o /usr/share/keyrings/greyhole-archive-keyring.gpg
```

With this, you are now not using apt-key, and no further changes are required to get it to work.

**Comment by gboudreau** [comment]
Thx. Merged.

**Comment by modem7** [comment]
No worries! One more thing - just in case (more from an error prevention point of view):

May need to add `mkdir -p /etc/apt/keyrings`

**Comment by gboudreau** [comment]
You mean `/usr/share/keyrings` ?

**Comment by modem7** [comment]
> You mean `/usr/share/keyrings` ?

I do! Blame the Christmas booze for the typo!
