### ISSUE TITLE
logrotate is already installed

### ISSUE THREAD

**Issue by old-square-eyes** [gboudreau/Greyhole#313]
Greyhole is asking me to install logrotate but it's already installed

<img width="481" alt="image" src="https://github.com/gboudreau/Greyhole/assets/25760491/1a8f62af-57b3-494a-b5e7-f84505677bd9">

**Comment by gboudreau** [comment]
What's the error message you get from Greyhole?

**Comment by old-square-eyes** [comment]
@gboudreau I thought it was lost but I recovered the apt logs :) It happened on clean install of Greyhole (logratate was already present), and again on apt upgrade.

```
Log started: 2023-07-02  11:05:44
(Reading database ... 36701 files and directories currently installed.)
Preparing to unpack .../greyhole_0.15.20-1_amd64.deb ...
Unpacking greyhole (0.15.20-1) over (0.15.18-1) ...
Setting up greyhole (0.15.20-1) ...
Warning! logrotate is not installed. You should install logrotate to make sure the Greyhole logs don't fill your root partition.
  Greyhole already installed the necessary conf file for logrotate; simply installing the logrotate package is enough.
Log ended: 2023-07-02  11:05:47
```

**Comment by gboudreau** [comment]
It shows this warning when `man logrotate` returns a non-zero value.
You got logrotate installed, but not `man` maybe..?

**Comment by old-square-eyes** [comment]
Seems like I didn't have `man`

**Comment by gboudreau** [comment]
NBext version will handle this (`man` not being available) better.

**Comment by gboudreau** [comment]
Version 0.5.21 includes this fix.
