### ISSUE TITLE
Greyhole won't start after update - SQL error Can't DROP 'uniqness';

### ISSUE THREAD

**Issue by wtown42** [gboudreau/Greyhole#315]
After upgrading to 0.15.20, Greyhole will no longer start.
I just get this error:
PHP Fatal error:  Uncaught Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'uniqness'; check that column/key exists in /usr/bin/greyhole:734

I get a continuous stream of these error messages as the system keep trying to restart Greyhole.

Any suggestions?

**Comment by gboudreau** [comment]
You MySQL table `du_stats` is missing the index that Greyhole wants to drop and re-create.

You can create it like this, after connecting to your MySQL server:
```sql
ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`(200));
```

Greyhole should then be able to execute the DB migrations it needs.

**Comment by wtown42** [comment]
When I execute that command, I get this error:

mysql> ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`(200));
ERROR 1062 (23000): Duplicate entry 'HomeFiles-Users/walt/Backups/Zeppo3_OneDrive/AppIiednfo/Connecte' for key 'uniqness'
mysql>

**Comment by gboudreau** [comment]
```sql
TRUNCATE du_stats;
ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`(200));
```

**Comment by wtown42** [comment]
That did it, thanks!
