### ISSUE TITLE
No Files shown after reinstall Greyhole

### ISSUE THREAD

**Issue by Grootent** [gboudreau/Greyhole#325]
I have update my ubuntu server from 32 bits to 64 bits.
Therefore I needed to reinstall greyhole.

 - mounted the greyhole storage pool drives.
```
 # / was on /dev/ubuntu-vg/ubuntu-lv during curtin installation
/dev/disk/by-id/dm-uuid-LVM-lqsbu11yvcZUBUwQaN1onYneLGRsHQdD3IPr9cqe4v1jRYjV5tdQgpmBaQgQUBtc / ext4 defaults 0 1
# /boot was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/450adbf7-c548-43f4-99ba-71e74c8f395a /boot ext4 defaults 0 1
# /boot/efi was on /dev/sda1 during curtin installation
/dev/disk/by-uuid/4793-AFDC /boot/efi vfat defaults 0 1
/swap.img       none    swap    sw      0       0
# WD red elements internal drive 2 TB HDD1
UUID=182E6B4408477A23 /var/hda/drives/HDD1 ntfs-3g rw,user,noatime 0 0
# WD elements internal drive 2 TB HDD2
UUID=16AA5FBDAA5F9857 /var/hda/drives/HDD2 ntfs-3g rw,user,noatime 0 0
# WD elements internal drive 1 TB HDD3
UUID=92B6F8D3B6F8B8B5 /var/hda/drives/HDD3 ntfs-3g rw,user,noatime 0 0
```

 - added the shared drives in samba.
```...
[Videos]
path = /var/hda/files/Videos
vfs objects = greyhole
dfree command = /usr/bin/greyhole-dfree
guest ok = No
read only = No
available = Yes
browseable = Yes
writable = Yes
printable = No
create mask = 0770
directory mask = 0770

[Downloads]
path = /var/hda/files/Downloads
comment = Downloads
create mask = 0775
dfree command = /usr/bin/greyhole-dfree
directory mask = 0770
read only = No
available = yes
browseable = yes
writable = yes
force dos attributes = yes
printable = no
force user = fred
vfs objects = greyhole
.....
```

 - performed a `greyhole --fsck`

Then checked on windows machine if I can access the drives.
That is fine and I can see all the folders but no files.

when I add a file it is visible for short time and then it disappears. 

checked user permission all file and folder have root:root
Try to change it with chown command but I'm not able to change ownership.

What is wrong?

Regards 
Fred

**Comment by gboudreau** [comment]
Your problem is permissions of the storage pool drives.  
Ref: https://github.com/gboudreau/Greyhole/wiki/Permissions-Data-Drives

Make sure you're working as root, or use sudo for commands to chown.

I'm not sure how using NTFS drives using `ntfs-3g` affects permissions, but the symptoms you describe mean that the user you are using to connect to Samba from Windows (`fred` I guess) is not allowed to read files and/or folders in your storage pool drives.

You can test that by looking at the symlink of a missing file in your landing zone (eg. `/var/hda/files/Downloads` for the Downloads share), and then, using the `fred` user on ssh, try to navigate all parent folders of that file, on your storage pool drive.

eg. if `/var/hda/files/Downloads/file1` symlink points to `/var/hda/drives/HDD1/gh/Downloads/file1`, then as `fred` (or whatever user you connect with, from Windows), do:

```bash
cd /var/hda/drives/HDD1
ls
cd gh
ls
cd Downloads
ls
md5sum file1
```

**Comment by Grootent** [comment]
Hi,

Thanks for the quick reply.

The storagepool and the landing zone all have root:root (permission 777)
In the directory of the the  landingzone (/var/hda/files) I was able to
change the ownership to fred:users
but for the storagepool (/var/hda/drives/HDD*/gh) I can't change ownership.

I use the chown command as root(sudo) but it has no effect on the
storagepool
"
***@***.***:/var/hda$ ls -l /var/hda/files/Downloads/Test.png
lrwxrwxrwx 1 fred users 42 Jan 16 16:10 /var/hda/files/Downloads/Test.png
-> /var/hda/drives/HDD1/gh/Downloads/Test.png
***@***.***:/var/hda$ ls -l /var/hda/drives/HDD1/gh/Downloads/Test.png
-rwxrwxrwx 1 root root 9553 Sep  6  2022
/var/hda/drives/HDD1/gh/Downloads/Test.png
***@***.***:/var/hda$ sudo chown -v fred:users
/var/hda/drives/HDD1/gh/Downloads/Test.png
changed ownership of '/var/hda/drives/HDD1/gh/Downloads/Test.png' from
root:root to fred:users
***@***.***:/var/hda$ ls -l /var/hda/drives/HDD1/gh/Downloads/Test.png
-rwxrwxrwx 1 root root 9553 Sep  6  2022
/var/hda/drives/HDD1/gh/Downloads/Test.png
"

Regards
Fred

Op vr 19 jan 2024 om 21:54 schreef Guillaume Boudreau <
***@***.***>:

**Comment by gboudreau** [comment]
This is most probably how ntfs-3g behaves on permissions; it simply makes everything 777.
So maybe the problem is the folders containing your storage pool drives.
Try to navigate `/var/hda/drives` using your `fred` user:

```bash
cd /var
ls
cd hda
ls
cd drives
ls
cd HDD1
ls
```

**Comment by Grootent** [comment]
Hi,

this gives the following result

***@***.***:~$ cd /var/hda/drives/HDD1/
***@***.***:/var/hda/drives/HDD1$ ls -l
total 4
drwxrwxrwx 1 root root 4096 Jan  4  2021 gh
***@***.***:/var/hda/drives/HDD1$ whoami
fred
***@***.***:/var/hda/drives/HDD1$

Regards
 Fred

Op za 20 jan 2024 om 14:16 schreef Guillaume Boudreau <
***@***.***>:

**Comment by gboudreau** [comment]
That is not the same thing. You need to check you have read access to all parent folders.

**Comment by Grootent** [comment]
Hi,

I see, sorry, like this.

***@***.***:/var$ ls -l
total 48
drwxr-xr-x  2 root root   4096 Jan 20 00:00 backups
drwxr-xr-x 16 root root   4096 Jan  5 20:36 cache
drwxrwxrwt  2 root root   4096 Aug 10 00:20 crash
drwxr-xr-x  4 root root   4096 Jan  5 21:21 hda
drwxr-xr-x 48 root root   4096 Jan  5 20:36 lib
drwxrwsr-x  2 root staff  4096 Apr 18  2022 local
lrwxrwxrwx  1 root root      9 Aug 10 00:17 lock -> /run/lock
drwxrwxr-x 12 root syslog 4096 Jan 20 00:00 log
drwxrwsr-x  2 root mail   4096 Aug 10 00:17 mail
drwxr-xr-x  2 root root   4096 Jan 17 00:45 opt
lrwxrwxrwx  1 root root      4 Aug 10 00:17 run -> /run
drwxr-xr-x  5 root root   4096 Aug 10 00:22 snap
drwxr-xr-x  6 root root   4096 Jan  4 15:02 spool
drwxrwxrwt  8 root root   4096 Jan 20 23:23 tmp
***@***.***:/var$ cd hda
***@***.***:/var/hda$ ls -l
total 8
drwxr-xr-x  5 root root 4096 Jan  5 15:56 drives
drwxrwxrwx 21 root root 4096 Jan  6 12:38 files
***@***.***:/var/hda$ cd drives
***@***.***:/var/hda/drives$ ls -l
total 12
drwxrwxrwx 1 root root 4096 Aug 24  2013 HDD1
drwxrwxrwx 1 root root 4096 Oct  9  2012 HDD2
drwxrwxrwx 1 root root 4096 Feb  7  2015 HDD3
***@***.***:/var/hda/drives$ cd HDD1
***@***.***:/var/hda/drives/HDD1$ ls-l
ls-l: command not found
***@***.***:/var/hda/drives/HDD1$ ls -l
total 4
drwxrwxrwx 1 root root 4096 Jan  4  2021 gh
***@***.***:/var/hda/drives/HDD1$

Regards
Fred

Op za 20 jan 2024 om 20:23 schreef Guillaume Boudreau <
***@***.***>:

**Comment by gboudreau** [comment]
You could look in the Samba logs `/var/log/samba/*.log` for errors. You might need to change the log level to a higher number (5 or even 10), in smb.conf, to see the permission error. Don't forget to restart smbd when you change its config. With a log level high enough, try to list files in a test folder should log the permission errors.

If you can't find the problem with that, try this command to gather your system info and post the resulting URL in a new comment: https://github.com/gboudreau/Greyhole/wiki/GetHelp#gather-system-information

**Comment by Grootent** [comment]
Hi,

finally I had some time to look at it

***@***.***:~$ ls -l /var/log/samba/
total 1516
drwx------ 5 root root   4096 Jan  4 15:02 cores
-rw-r--r-- 1 root root    810 Jan 31 20:19 log.192.168.178.108
-rw-r--r-- 1 root root  31964 Jan  6 11:26 log.192.168.178.111
-rw-r--r-- 1 root root 194404 Jan  6 11:44 log.192.168.178.17
-rw-r--r-- 1 root root 967264 Jan 27 22:28 log.192.168.178.20
-rw-r--r-- 1 root root   4884 Jan 20 00:49 log.192.168.178.31
-rw-r--r-- 1 root root      0 Jan 31 10:45 log.192.168.178.32
-rw-r--r-- 1 root root      0 Jan  5 09:55 log.192.168.178.70
-rw-r--r-- 1 root root 229394 Jan 20 00:48 log.192.168.178.76
-rw-r--r-- 1 root root   4330 Jan 31 22:08 log.bmp1ks3
-rw-r--r-- 1 root root   1882 Jan 28 00:00 log.grootentraasthome
-rw-r--r-- 1 root root   7126 Jan 25 16:18 log.localhost
-rw-r--r-- 1 root root  10805 Jan 20 00:55 log.nb3016
-rw-r--r-- 1 root root    819 Jan 31 21:16 log.nmbd
-rw-r--r-- 1 root root    285 Jan 21 00:00 log.nmbd.1
-rw-r--r-- 1 root root    264 Jan 18 19:27 log.nmbd.2.gz
-rw-r--r-- 1 root root    314 Jan 14 00:00 log.nmbd.3.gz
-rw-r--r-- 1 root root    254 Jan  5 20:38 log.nmbd.4.gz
-rw-r--r-- 1 root root    507 Jan 27 22:28 log.safrespe
-rw-r--r-- 1 root root   2192 Jan 31 22:12 log.samba-bgqd
-rw-r--r-- 1 root root   1658 Jan 31 22:12 log.smbd
-rw-r--r-- 1 root root    548 Jan 21 00:00 log.smbd.1
-rw-r--r-- 1 root root    712 Jan 20 00:48 log.smbd.2.gz
-rw-r--r-- 1 root root    171 Jan  7 00:00 log.smbd.3.gz
-rw-r--r-- 1 root root    340 Jan  6 11:44 log.smbd.4.gz
-rw-r--r-- 1 root root    524 Jan  7 00:00 log.volumio

look in the log files but could not find any error

changed fstab config to change the owner to fred:users this had no effect.

# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/ubuntu-vg/ubuntu-lv during curtin installation
/dev/disk/by-id/dm-uuid-LVM-lqsbu11yvcZUBUwQaN1onYneLGRsHQdD3IPr9cqe4v1jRYjV5tdQgpmBaQgQUBtc
/ ext4 defaults 0 1
# /boot was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/450adbf7-c548-43f4-99ba-71e74c8f395a /boot ext4 defaults
0 1
# /boot/efi was on /dev/sda1 during curtin installation
/dev/disk/by-uuid/4793-AFDC /boot/efi vfat defaults 0 1
/swap.img       none    swap    sw      0       0
# WD red elements internal drive 2 TB HDD1
UUID=182E6B4408477A23 /var/hda/drives/HDD1 ntfs-3g
defaults,uid=fred,gid=users 0 0
# WD elements internal drive 2 TB HDD2
UUID=16AA5FBDAA5F9857 /var/hda/drives/HDD2 ntfs-3g
defaults,uid=fred,gid=users 0 0
# WD elements internal drive 1 TB HDD3
UUID=92B6F8D3B6F8B8B5 /var/hda/drives/HDD3 ntfs-3g
defaults,uid=fred,gid=users 0 0


on windows created a file on a share.
succeeded but after a second it not visible.
on unbuntu server permissions for this file becomes root:root

smb.conf
[Downloads]
path = /var/hda/files/Downloads
comment = Downloads
create mask = 0775
dfree command = /usr/bin/greyhole-dfree
directory mask = 0770
read only = No
available = yes
browseable = yes
writable = yes
printable = no
force user = fred
vfs objects = greyhole

[NZB]
path = /var/hda/files/NZB
create mask = 0770
dfree command = /usr/bin/greyhole-dfree
directory mask = 0770
read only = no
available = yes
browseable = yes
writable = yes
printable = no
vfs objects = greyhole

[HomeVideo]
path = /var/hda/files/HomeVideo
create mask = 0770
dfree command = /usr/bin/greyhole-dfree
directory mask = 0770
read only = no
available = yes
browseable = yes
writable = yes
printable = no
vfs objects = greyhole

[Games]
path = /var/hda/files/Games
create mask = 0770
dfree command = /usr/bin/greyhole-dfree
directory mask = 0770
read only = no
available = yes
browseable = yes
writable = yes
printable = no
vfs objects = greyhole
Regards Fred

Op zo 21 jan 2024 om 14:47 schreef Guillaume Boudreau <
***@***.***>:

**Comment by Grootent** [comment]
Hi,

Finally my files are back.

after installing the new OS the smb.conf missedsome global options..

by adding the following lines the files appear again
"
 unix extensions = no
wide links = yes

wins support = yes

;   wins server = w.x.y.z

   dns proxy = no
"

Thanks for your time helping me out.

Regards Fred

Op wo 31 jan 2024 om 23:34 schreef Fred Grootentraast ***@***.***>:

**Comment by gboudreau** [comment]
Thanks for the follow-up. I'll update the documentation to mention that those missing lines could result in this behaviour.

Good day.
