### ISSUE TITLE
Greyhole won't start

### ISSUE THREAD

**Issue by spacezorro** [gboudreau/Greyhole#326]
Rebooted my server and Greyhole won't start

#greyhole -S
PHP Fatal error:  Uncaught Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'uniqness'; check that column/key exists in /usr/bin/greyhole:734
Stack trace:
#0 /usr/bin/greyhole(1052): DB::execute('ALTER TABLE `du...')
#1 /usr/bin/greyhole(1088): DB::migrate_large_fullpath()
#2 /usr/bin/greyhole(856): DB::migrate_18_full_path_utf8mb4()
#3 /usr/bin/greyhole(694): DB::migrate()
#4 /usr/bin/greyhole(8472): DB::connect(false)
#5 /usr/bin/greyhole(8430): CommandLineHelper->getRunner()
#6 /usr/bin/greyhole(8691): CommandLineHelper->processCommandLine()
#7 {main}
  thrown in /usr/bin/greyhole on line 734

**Comment by spacezorro** [comment]
It's getting hung up on 
    $q = "ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`(200))";

Here is the current du_stats
mysql> describe greyhole.du_stats;
+-----------+---------------------+------+-----+---------+-------+
| Field     | Type                | Null | Key | Default | Extra |
+-----------+---------------------+------+-----+---------+-------+
| share     | varchar(255)        | NO   |     | NULL    |       |
| full_path | text                | NO   |     | NULL    |       |
| depth     | tinyint(3) unsigned | NO   |     | NULL    |       |
| size      | bigint(20) unsigned | NO   |     | NULL    |       |
+-----------+---------------------+------+-----+---------+-------+
4 rows in set (0.00 sec)

**Comment by gboudreau** [comment]
You can `DELETE FROM du_stats`, it will be re-populated automatically on the next weekly fsck.
then try to create the index using the ALTER TABLE, and then try again to start Greyhole.

**Comment by spacezorro** [comment]
This worked.

mysql> DELETE FROM du_stats;
Query OK, 13413 rows affected (0.03 sec)

mysql> ALTER TABLE `du_stats` ADD UNIQUE KEY `uniqness` (`share`(64),`full_path`(200));
Query OK, 0 rows affected (0.02 sec)
Records: 0  Duplicates: 0  Warnings: 0

I started greyhole and fired off a fsck just because.

**Comment by spacezorro** [comment]
Thanks.
