### ISSUE TITLE
VFS files to support Samba 4.19

### ISSUE THREAD

**Issue by jkrehm-cvna** [gboudreau/Greyhole#331]
I just upgraded to the latest Ubuntu LTS and it installed Samba 4.19. That has broken Greyhole because *.so files are only available for 4.18 and below.

Is it possible to get the 4.19 files uploaded to Github?

**Comment by gboudreau** [comment]
Yeah, I'll look into it, but until then, you should be able to compile it yourself with this command: `/usr/share/greyhole/build_vfs.sh current`

If that fails (or not), please let me know.

**Comment by jkrehm-cvna** [comment]
Brilliant, I'll use `build_vfs.sh` right now. Thank you!

**Comment by jkrehm-cvna** [comment]
That worked. I'll close this ticket since my issue is resolved. If/when you have time to upload the 4.19 files, then thank you for that, too.
