### ISSUE TITLE
Rename bug when editing MS Office files

### ISSUE THREAD

**Issue by lixer007** [gboudreau/Greyhole#74]
When I edit and save MS Office files stored in greyhole via samba share, greyhole removes the original file and leaves a <random>.tmp files in place.

Here is the debug log: http://pub.pommepause.com/greyhole-debug-74.log

**Comment by gboudreau** [comment]
This issue should be resolved by d162fab546357f088c4553275d2cc335f3e7afdb.
I tested with Word and Excel documents, and while opening and editing such files logged a lot of unnecessary tasks (file operations), the end result was always OK.
