### ISSUE TITLE
Complete Management UI

### ISSUE THREAD

**Issue by gboudreau** [gboudreau/Greyhole#8]
Create a complete UI to manage Samba shares, users, and Greyhole configuration.
The UI should allow end-users to easily manage hard drives & partitions, shares & users.
Easy to follow wizards should be created for operations that are more involved (add new drive).

**Comment by modem7** [comment]
Hey guys,

Any update on this? Even something as "simple" as Amahi's UI would be fantastic for starters as it allows us to leverage the Samba setup and do simple tweaks.

**Comment by gboudreau** [comment]
No, nothing new on this front.

**Comment by gboudreau** [comment]
Playing with Bootstrap and chart.js. Might come up with something usable at some point.
Not sure I'll persevere until wizards are created though...  

![image](https://user-images.githubusercontent.com/370329/91650614-ac2a7100-ea4f-11ea-9994-931d303c40f0.png)

**Comment by bigfoot65** [comment]
Very nice!

I'd love to see a Web UI (Greyhole Config) for Greyhole.  It's the one
thing I feel has been missing for too long.

Many users without much linux experience use it.

I've tried to make my own in PHP, but I am not very good with it.

If you need testers down the road for this, I am happy to assist.

ßîgƒooτ65
Amahi Applications Manager

Amahi <https://www.amahi.org> - Powerful, Simple Home Server

**Comment by modem7** [comment]
That looks uber sexy I have to say!

**Comment by gboudreau** [comment]
The [dev/web-ui](https://github.com/gboudreau/Greyhole/tree/dev/web-ui) branch is in a working state now. If you'd like to try it, to this on your Greyhole server:
```bash
sudo cp /etc/greyhole.conf /etc/greyhole.conf.bak # because the new UI could eat your greyhole.conf!!
git clone --single-branch --branch dev/web-ui https://github.com/gboudreau/Greyhole.git ./Greyhole-New-Web-UI
sudo php -S 0.0.0.0:8012 ./Greyhole-New-Web-UI/web-app/index.php
```

And in your web browser: http://server_ip_address:8012

Changing any control in the UI should change your greyhole.conf, and prompt you to restart the daemon, if needed.
It's not yet possible to add or remove storage pool drives or samba shares, or pool groups.

You can monitor changes to your .conf (versus your backed-up copy) in almost real-time with this command:
```bash
while true; do printf "\033c" ; diff --color /etc/greyhole.conf.bak /etc/greyhole.conf; sleep 1; done
```

**Comment by bigfoot65** [comment]
Do I need to run this from a specific directory?

It cloned the repo in my home directory.

When I tried to connect, it gave me a database connect error.

BTW, I am testing this on a Amahi 11 test VM so it's a bare basic setup.

ßîgƒooτ65
Amahi Applications Manager

Amahi <https://www.amahi.org> - Powerful, Simple Home Server

**Comment by gboudreau** [comment]
> Do I need to run this from a specific directory? It cloned the repo in my home directory. When I tried to connect, it gave me a database connect error. BTW, I am testing this on a Amahi 11 test VM so it's a bare basic setup.

It is assuming a working Greyhole install. In your case, I would guess there is either no /etc/greyhole.conf, or the DB info specified in there are not working.

**Comment by bigfoot65** [comment]
Yea I didn't quite have my settings right for the daemon to run.

Got it now though.  Looking nice.

ßîgƒooτ65
Amahi Applications Manager

Amahi <https://www.amahi.org> - Powerful, Simple Home Server

**Comment by gboudreau** [comment]
Added Dark mode, status section, tweaked UX and UI here and there, new dialog to add a drive to the storage pool:

![image](https://user-images.githubusercontent.com/370329/91672499-10573e80-eafd-11ea-834d-be14a6931a0c.png)

![image](https://user-images.githubusercontent.com/370329/91672536-38df3880-eafd-11ea-8fb6-043a8541cd0c.png)

**Comment by bigfoot65** [comment]
Nice.  Looking good.

I have not tried on my production server, but that will be next.

ßîgƒooτ65
Amahi Applications Manager

Amahi <https://www.amahi.org> - Powerful, Simple Home Server

**Comment by bigfoot65** [comment]
Have you considered making the interface tabbed, versus one long screen?

Just a thought as lately I have been doing some html coding with tabs and
like how it looks and works.

I've created a few Amahi apps with tabs.

ßîgƒooτ65
Amahi Applications Manager

Amahi <https://www.amahi.org> - Powerful, Simple Home Server

**Comment by gboudreau** [comment]
I've decided to try to use a different license for the web UI. Using the web UI (past the initial setup) will require a donation.  
Details: https://github.com/gboudreau/Greyhole/wiki/Admin-Web-UI

Next, I'll try to create a walkthrough for initial setup.

Some screenshots of the current state of things:
![image](https://user-images.githubusercontent.com/370329/92415846-c7b90a00-f128-11ea-82fc-f60a6a85747c.png)
![image](https://user-images.githubusercontent.com/370329/92415263-229d3200-f126-11ea-86b7-41c17782b8de.png)
![image](https://user-images.githubusercontent.com/370329/92415289-38aaf280-f126-11ea-9dd9-5029cbda5b3a.png)
![image](https://user-images.githubusercontent.com/370329/92415459-f209c800-f126-11ea-8308-a673a9db08d2.png)
![image](https://user-images.githubusercontent.com/370329/92415317-50827680-f126-11ea-91f7-830ccd6b862b.png)

**Comment by modem7** [comment]
Heya,

That looks great!

Could you post the donate link here for us if possible please?

I haven't yet installed the latest version

**Comment by gboudreau** [comment]
> Could you post the donate link here for us if possible please?

- Github sponsor (monthly donation, ala-Patreon): use the button at the top of this screen (https://github.com/sponsors/gboudreau)
- Paypal (one-time donation) : https://www.greyhole.net/#donate

Of note: I didn't package and release 0.15 yet, which would include this. Still playing a little with it every day. Should be released in the upcoming week.

**Comment by gboudreau** [comment]
0.15.0 has been released, and contains this.

I added a [wizard for initial setup](https://github.com/gboudreau/Greyhole/wiki/Initial-Setup-Web-Wizard):

<kbd><img src="https://user-images.githubusercontent.com/370329/92997751-7a031f80-f4e3-11ea-8b95-6a514dcc8e25.png" alt="Step 1" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/370329/92997770-b46cbc80-f4e3-11ea-80a7-67a6af210ca7.png" alt="Step 2" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/370329/92997779-c8b0b980-f4e3-11ea-9cb6-a161c735f10a.png" alt="Step 3" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/370329/92997784-d5cda880-f4e3-11ea-9587-2a19e5299fcb.png" alt="Step 4" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/370329/92997797-eb42d280-f4e3-11ea-8af7-9ee91f627e79.png" alt="Step 5" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/370329/92997798-f72e9480-f4e3-11ea-9ddf-eef2fe2a9fac.png" alt="Step 6" /></kbd>

<kbd><img src="https://user-images.githubusercontent.com/370329/92997803-06154700-f4e4-11ea-909d-c46fc1e1d0c3.png" alt="Done" /></kbd>

**Comment by gboudreau** [comment]
Closing this issue now. Yay.
